### ISSUE TITLE
Start a Release Review

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/glassfish#22606]
Passing **Release Review** is a required step before making a first public release. Deadline for passing the review is Nov 30th, 2018. Release review takes some time to complete, so it makes sense initiating it as soon as possible.

- [x] Start Release Review
- [x] Update [Release Review Tracker](https://wiki.eclipse.org/EE4J_Projects_Release_Review_Tracker)

Additional information:

- [How to submit a release review](https://wiki.eclipse.org/How_to_release_first_versions_of_EE4J_components)
- [Eclipse Handbook](https://wiki.eclipse.org/Development_Resources/HOWTO/Release_Reviews)

**Comment by m0mus** [comment]
**Eclipse GlassFish**: https://projects.eclipse.org/projects/ee4j.glassfish

**Comment by m0mus** [comment]
IP Log submission is blocked because initial contribution IP check has not been finished.

**Comment by candrews** [comment]
Will Glassfish 5.1 run on the latest version of Java (which is currently 8u191)? See #22601

I ask as that seems like a very big deal :-)
