### ISSUE TITLE
5.1.0-RC1 release is missing some embedded packages

### ISSUE THREAD

**Issue by candrews** [eclipse-ee4j/glassfish#22616]
I see that 5.1.0-RC1 was released, here's the main zip: https://repo1.maven.org/maven2/org/glassfish/main/distributions/glassfish/5.1.0-RC1/glassfish-5.1.0-RC1.zip

Some component packages of Glassfish were updated for this release, while others were not. For example, https://repo1.maven.org/maven2/org/glassfish/main/extras/glassfish-embedded-shell-frag/ was updated was updated.

These packages I'd expect to be updated were not:
 * https://repo1.maven.org/maven2/org/glassfish/main/extras/glassfish-embedded-web/
* https://repo1.maven.org/maven2/org/glassfish/main/extras/glassfish-embedded-all/
* https://repo1.maven.org/maven2/org/glassfish/main/extras/embedded/

Can you please update all of these (and any I've missed)?

IMHO, this is a blocking issue for https://github.com/eclipse-ee4j/glassfish/issues/22606

**Comment by candrews** [comment]
#22604 says that Glassfish 5.1 (final release already?) has been released to the OSSRH staging repository and it does not have this issue fixed.
https://oss.sonatype.org/content/groups/staging/org/glassfish/main/extras/ is missing `glassfish-embedded-web`, `glassfish-embedded-all`, and `embedded`

**Comment by romain-grecourt** [comment]
@vinayvishal can you comment on that ?

**Comment by vinayvishal** [comment]
@romain-grecourt , If you remember, embedded profile was disabled since the beginning. That is why these artefacts are not there. Do we want to enable embedded profile too? I am not sure why it was disabled in first place.

**Comment by candrews** [comment]
Any news on this? IMHO, it's important that the next Glassfish release include the same embedded support that prior releases have.

**Comment by romain-grecourt** [comment]
@vinayvishal Yes, we do want to enable the embedded profiles. Let me know if you run into issues.

**Comment by vinayvishal** [comment]
> @vinayvishal Yes, we do want to enable the embedded profiles. Let me know if you run into issues.

@romain-grecourt , sure, I will do it soon and publish the updated artefacts to staging repository.

**Comment by candrews** [comment]
5.1.0-RC2 publishes these artifacts resolving this issue.
