### ISSUE TITLE
LDAP Booster Pack (ldapbp) module is being built as a non-glassfish jar

### ISSUE THREAD

**Issue by pjs102** [eclipse-ee4j/glassfish#22635]
## Environment Details
* GlassFish Version (and build number): 5.1.0-RC1
* JDK version: 1.8.0
----------
## Problem Description
The ldapbp module is being built as a non glassfish jar file, which means that its packages are not being exported for use by any corresponding service.  In glassfish 4 a repackaged version of the jar was shipped that exported the com.sun.jndi.ldap.* packages. 

Please update the eclipse-ee4j\glassfish\appserver\ldapbp\pom.xml and add `<packaging>glassfish-jar</packaging>` to the pom file.

**Comment by romain-grecourt** [comment]
It's only about OSGi metadata in the manifest file, glassfish-jar packaging has a lot more stuff in it.
