### ISSUE TITLE
Incorrect jsf bundles

### ISSUE THREAD

**Issue by edbratt** [eclipse-ee4j/glassfish#22698]
After a build, the modules directory (glassfish5/glassfish/modules) contains the following jsf related JAR files:
- javax.servlet.jsp.jar
- javax.servlet.jsp.jstl.jar

I suspect these should be changed to jakarta.servlet...
Please investigate and correct and/or confirm this is proper, as needed.
Eclipse GlassFish 5.1, build from 1/7/2019.

**Comment by Cousjava** [comment]
Bundles are correct when I try building, and should have been fixed in #22649 and #22658.
