### ISSUE TITLE
webservice scripts reference javax jars

### ISSUE THREAD

**Issue by romain-grecourt** [eclipse-ee4j/glassfish#22690]
## Environment Details
* GlassFish Version (and build number): 5.1.0-SNAPSHOT

----------

## Problem Description

All files under `appserver/webservices/webservices-scripts/src/main/resources/glassfish/bin/` do reference jar files that have been renamed:
- javax.xml.rpc-api.jar
- javax.mail.jar

These occurrences should be replaced with their new `jakarta.` equivalent.

## Steps to reproduce

Use any of the webservice scripts inside the bin folder of the full distribution.

## Impact of Issue

The webservices scripts are not working.

**Comment by romain-grecourt** [comment]
@lukasj @m0mus @edbratt

**Comment by m0mus** [comment]
@romain-grecourt I see that the PR is merged. Can this issue be closed?

**Comment by lukasj** [comment]
@romain-grecourt thanks for fixing!

**Comment by romain-grecourt** [comment]
@m0mus Yes, closing it now.
