### ISSUE TITLE
CTS ServletTCK httpupgradehandler#upgradeTest fails with Interrupted Exception

### ISSUE THREAD

**Issue by anajosep** [eclipse-ee4j/glassfish#22696]
Test Name:
com/sun/ts/tests/servlet/api/javax_servlet_http/httpupgradehandler#upgradeTest
Error logs:
[ServletTestUtil] Scanning response for search string: 'TCKHttpUpgradeHandler.init' starting at index location: 0
[ServletTestUtil] Found search string: 'TCKHttpUpgradeHandler.init' at index '286' in the server's response
01-06-2019 20:23:57: ==============Received first expected response!

[ServletTestUtil] Scanning response for search string: 'onDataAvailable' starting at index location: 0
[ServletTestUtil] Found search string: 'onDataAvailable' at index '246' in the server's response
[ServletTestUtil] Scanning response for search string: 'Hello' starting at index location: 261
[ServletTestUtil] Found search string: 'Hello' at index '264' in the server's response
01-06-2019 20:23:57: ==============Received second expected response!

[ServletTestUtil] Scanning response for search string: 'onDataAvailable' starting at index location: 0
[ServletTestUtil] Found search string: 'onDataAvailable' at index '246' in the server's response
[ServletTestUtil] Scanning response for search string: 'World' starting at index location: 261
[ServletTestUtil] Found search string: 'World' at index '333' in the server's response
01-06-2019 20:23:57: ==============Received third expected response!

result: Error. Program `/opt/jdk1.8.0_192/jre/bin/java' interrupted! (timed out?)
## Environment Details
* GlassFish Version (and build number):https://jenkins.eclipse.org/glassfish/job/glassfish/job/EE4J_8/70/
Git Revision: 0426f495c1c04f74625570dcb46c45662a52d890
Git Branch: EE4J_8
Build Date: Fri Jan  4 23:01:56 UTC 2019
* JDK version: JDK8u192
* OS: CentOS
* Database: JavaDB

----------

## Problem Description
The test hangs and finally gets killed by an interrupted Exception.

## Steps to reproduce
run the standalone TCK for servlet against the latest Eclipse GlassFish 5.1.0

## Impact of Issue
With TCK failure, GlassFish does not comply to Servlet Specification and cannot be released.

**Comment by bhatpmk** [comment]
The test here had issue, which is fixed now.
