### ISSUE TITLE
"InvalidTransactionException: Invalid transaction passed to resume() call" happens because the GlobalTIDs are the same

### ISSUE THREAD

**Issue by caim2015** [eclipse-ee4j/glassfish#22701]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* GlassFish Version (and build number):4.0
* JDK version:8

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"
Our application construction is as the follows：
Invoke BMT stateless session bean from two CMT stateless session bean with global transactions. 

This exception happens in the BMT when at the same time we send multiple requests to the two CMT.
<pre>
[#|2019-01-07T16:07:51.180+0800|WARNING|||_ThreadID=1374;_ThreadName=p: thread-pool-1; w: 82;|javax.ejb.EJBException: javax.transaction.InvalidTransactionException: Invalid transaction passed to resume() call.
    at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2035)
    at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:1999)
    at com.sun.ejb.containers.EJBObjectInvocationHandler.invoke(EJBObjectInvocationHandler.java:213)
    at com.sun.ejb.containers.EJBObjectInvocationHandlerDelegate.invoke(EJBObjectInvocationHandlerDelegate.java:79)
    at com.sun.proxy.$Proxy183.doTest3(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor63.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie.dispatchToMethod(ReflectiveTie.java:147)
    at com.sun.corba.ee.impl.presentation.rmi.ReflectiveTie._invoke(ReflectiveTie.java:182)
    at com.sun.corba.ee.impl.protocol.CorbaServerRequestDispatcherImpl.dispatchToServant(CorbaServerRequestDispatcherImpl.java:538)
    at com.sun.corba.ee.impl.protocol.CorbaServerRequestDispatcherImpl.dispatch(CorbaServerRequestDispatcherImpl.java:200)
    at com.sun.corba.ee.impl.protocol.CorbaMessageMediatorImpl.handleRequestRequest(CorbaMessageMediatorImpl.java:1726)
    at com.sun.corba.ee.impl.protocol.CorbaMessageMediatorImpl.handleRequest(CorbaMessageMediatorImpl.java:1534)
    at com.sun.corba.ee.impl.protocol.CorbaMessageMediatorImpl.handleInput(CorbaMessageMediatorImpl.java:1037)
    at com.sun.corba.ee.impl.protocol.giopmsgheaders.RequestMessage_1_2.callback(RequestMessage_1_2.java:226)
    at com.sun.corba.ee.impl.protocol.CorbaMessageMediatorImpl.handleRequest(CorbaMessageMediatorImpl.java:755)
    at com.sun.corba.ee.impl.protocol.CorbaMessageMediatorImpl.dispatch(CorbaMessageMediatorImpl.java:552)
    at com.sun.corba.ee.impl.protocol.CorbaMessageMediatorImpl.doWork(CorbaMessageMediatorImpl.java:2437)
    at com.sun.corba.ee.impl.orbutil.threadpool.ThreadPoolImpl$WorkerThread.performWork(ThreadPoolImpl.java:510)
    at com.sun.corba.ee.impl.orbutil.threadpool.ThreadPoolImpl$WorkerThread.run(ThreadPoolImpl.java:553)
Caused by: javax.transaction.InvalidTransactionException: Invalid transaction passed to resume() call.
    at com.sun.enterprise.transaction.JavaEETransactionManagerSimplified.resume(JavaEETransactionManagerSimplified.java:1078)
    at com.sun.ejb.containers.BaseContainer.postInvokeTx(BaseContainer.java:4920)
    at com.sun.ejb.containers.BaseContainer.postInvoke(BaseContainer.java:2028)
    ... 20 more
|#]
</pre>
By debug,the reason for the exception is that the same GlobalTIDs are generated in the two CMT.
After the same GlobalTIDs generated and transferred to the BMT,
cause to the same transaction object can be in different thread in the BMT.
That is to say,in one thread transaction state is changed to rollback,another thread's transaction state also be  changed to rollback.
This can cause the above exception.

The following is the GlobalTID generation code in CMT.
You can see that GlobalTID consists of "TIDTemplate" and "localTID".

TransactionState.java
<pre>
private static final byte[] generateTID(long localTID) {
    if(TIDTemplate==null){  *1
    synchronized(TransactionState.class){

            if(TIDTemplate==null){
                String serverName = Configuration.getServerName();
                int nameLength = (serverName == null ? 0 : serverName.length());
            TIDTemplate = new byte[nameLength+8];  *2

                long epochNumber    = new Date().getTime(); 
                TIDTemplate[4] = (byte) epochNumber; 
                TIDTemplate[5] = (byte)(epochNumber >> 8); 
                TIDTemplate[6] = (byte)(epochNumber >> 16); 
                TIDTemplate[7] = (byte)(epochNumber >> 24); 

                for( int i = 0; i < nameLength; i++ )
                    TIDTemplate[i+8] = (byte) serverName.charAt(i); *3
    }

    }

}
    byte[] result = new byte[TIDTemplate.length]; *4
System.arraycopy(TIDTemplate, 4, result, 4, TIDTemplate.length-4);*4

    result[0] = (byte) localTID; *4
    result[1] = (byte)(localTID >> 8); *4
    result[2] = (byte)(localTID >> 16); *4
    result[3] = (byte)(localTID >> 24); *4

    return result;*4
}
</pre>
I find that there is a bug when at the same time multiple requests are sent.
Code *1 does not be contained in "synchronized".
At Code *2 TIDTemplate'value is initialized as [0,0,0,0,0,...].
Before Code *3 is executed,another thread reachs.
At Code *1 because the TIDTemplate is not null, 
directly with the wrong TIDTemplate[0,0,0,0,0,...] , GlobalTID is generated.

Because we hava two CMTs,when at the same time we send multiple requests,
at some point in time localTID can be the same.

So,in the two CMT,
the same GlobalTID can be generated with the same localTID and the same TIDTemplate[0,0,0,0,0,...].

**Comment by smillidge** [comment]
Please provide a buildable test case that demonstrates the issue

**Comment by caim2015** [comment]
Sorry for the late replay.
the issue happens at a certain time,so we provided the way of the debug.
steps:
1.install the glassfish 4.1
  
2.start domain,open the console.

3.new cluster1 instance1
  new cluster2 instance2
  new cluster3 instance3
  new cluster4 instance4
  
4.set debug Enabled and port on the above of the cluster2 cluster3 cluster4 

5.deploy the client.war on the cluster1
  deploy the cmt1.jar on the cluster2
  deploy the cmt2.jar on the cluster3
  deploy the bmt.jar on the cluster4
  
5.start all the clusters.

6.set breakpoints.
TransactionState#generateTID(long localTID)	
LINE858 if(TIDTemplate==null){			
LINE865 long epochNumber = new Date().getTime();

EJBContainerTransactionManager#postInvokeTx(EjbInvocation)	
LINE470

JavaEETransactionManagerSimplified#resume(Transaction)	
LINE994 int status = tobj.getStatus();
LINE999 throw new InvalidTransactionException

										
7.http://localhost:28080/client/SimpleServlet?testejb=cmt1  access two times by browser.		

8.there are two threads be suspended at the breakpoint LINE858 in the process of cluster2.
  at this time,one of the threads(supposed thread A1)"localTID" is [2],
  the other(supposed thread B1) is [3].
  
9.let the thread A1 go to the LINE865.
  at this time,"TIDTemplate" is set to be [0,0,0,0,0,...].

10.let the thread B1 continue to run.
   at this time,there is a thread(supposed thread C) be suspended at the breakpoint LINE470 in the process of cluster4.
   continue to run again,JavaEETransactionManagerSimplified#resume is invoked,suspended at theLINE994.
   
11.set breakpoints.
TransactionFactoryImpl#recreate(PropagationContext)	
LINE272  CoordinatorImpl subordinate =  RecoveryManager.getCoordinator(globalTID); 
LINE425  subordinate.setPermanent(); 
  
TopCoordinator#rollback(boolean)	
LINE2313   if (!temporary &&!tranState.setState(TransactionState.STATE_ROLLED_BACK)) {
   
11.http://localhost:28080/client/SimpleServlet?testejb=cmt2  access two times by browser. 
  like the step of [8.] there are two threads be suspended at the breakpoint LINE858 in the process of cluster3.
  at this time,one of the threads(supposed thread A2)"localTID" is [2],
  the other(supposed thread B2) is [3].
  
12.let the thread A2 go to the LINE865.
   at this time,"TIDTemplate" also be set to be [0,0,0,0,0,...].

13.let the thread B2 continue to run.
   at this time,there is a thread(supposed thread D) be suspended at the breakpoint LINE272 in the process of cluster4.
   becauce the globalTID is the same,"subordinate" can be gotten at the "RecoveryManager.getCoordinator".
   
13.let the thread D continue to run.   
   "subordinate" is not null,so it is suspended at the breakpoint LINE425 subordinate.setPermanent().   
   in the subordinate.setPermanent(),falg "temporary" is set to "false".
   
14.let the thread D continue to run. 
   it is suspended at the breakpoint LINE2313.
   becauce "temporary" is "false",tranState.setState(TransactionState.STATE_ROLLED_BACK) is invoked.
   
15.after the tranState.setState(TransactionState.STATE_ROLLED_BACK) ended,
   let the thread C continue to run.
   it is suspended at the breakpoint LINE999,so the issue is reproduced.
  
If you fail to reproduce,pleace restart the cluster2 and cluster3,try again following the steps 6~15.
[app.zip](https://github.com/eclipse-ee4j/glassfish/files/3039084/app.zip)

**Comment by caim2015** [comment]
Hi,do you reproduce the bug?
What do you think about this？
Look forward to your feedbacks!

**Comment by smillidge** [comment]
I haven't had the time as this is an open source project worked on in spare time. I noticed the bug report is against 4.0 as 4.0 was not transitioned to the Eclipse Foundation does the same bug occur on the latest 5.1 release?

**Comment by caim2015** [comment]
> 
> 
>  does the same bug occur on the latest 5.1 release?

Yes,
Now we hava tested and verified that the same bug can occur on the latest 5.1 release.

**Comment by caim2015** [comment]
About this issue,we think that TransactionState#generateTID(double checked locking) should be fixed. 
We have two solutions.
solution1 add a 'TIDTemplateCompleted' flag **1.

`static byte [] TIDTemplate=null;
    static volatile boolean TIDTemplateCompleted = false; **1

    private static final byte[] generateTID(long localTID) {
        if(TIDTemplate==null  || !TIDTemplateCompleted){  **2
        synchronized(TransactionState.class){
                if(TIDTemplate==null){
                    String serverName = Configuration.getServerName();
                    int nameLength = (serverName == null ? 0 : serverName.length());
                TIDTemplate = new byte[nameLength+8];

                    long epochNumber    = new Date().getTime();
                    TIDTemplate[4] = (byte) epochNumber;
                    TIDTemplate[5] = (byte)(epochNumber >> 8);
                    TIDTemplate[6] = (byte)(epochNumber >> 16);
                    TIDTemplate[7] = (byte)(epochNumber >> 24);

                    for( int i = 0; i < nameLength; i++ )
                        TIDTemplate[i+8] = (byte) serverName.charAt(i);

                    TIDTemplateCompleted = true; **3
        }
        }
    }
        byte[] result = new byte[TIDTemplate.length];
    System.arraycopy(TIDTemplate, 4, result, 4, TIDTemplate.length-4);

        result[0] = (byte) localTID;
        result[1] = (byte)(localTID >> 8);
        result[2] = (byte)(localTID >> 16);
        result[3] = (byte)(localTID >> 24);

        return result;
    }`

solution2 add volatile keyword in 'TIDTemplate' **1,and add a temporary 'TIDTemplate' **2.

`volatile static byte [] TIDTemplate=null;**1

	private static final byte[] generateTID(long localTID) {
        if(TIDTemplate==null){
        synchronized(TransactionState.class){
                if(TIDTemplate==null){
                    String serverName = Configuration.getServerName();
                    int nameLength = (serverName == null ? 0 : serverName.length());
                byte[] TIDTemplateTemp = new byte[nameLength+8]; **2

                    long epochNumber    = new Date().getTime();
                    TIDTemplateTemp[4] = (byte) epochNumber;   **3
                    TIDTemplateTemp[5] = (byte)(epochNumber >> 8);  **3
                    TIDTemplateTemp[6] = (byte)(epochNumber >> 16);  **3
                    TIDTemplateTemp[7] = (byte)(epochNumber >> 24);  **3

                    for( int i = 0; i < nameLength; i++ )
                        TIDTemplateTemp[i+8] = (byte) serverName.charAt(i);

                TIDTemplate = TIDTemplateTemp; **4

        }
        }
    }
        byte[] result = new byte[TIDTemplate.length];
    System.arraycopy(TIDTemplate, 4, result, 4, TIDTemplate.length-4);

        result[0] = (byte) localTID;
        result[1] = (byte)(localTID >> 8);
        result[2] = (byte)(localTID >> 16);
        result[3] = (byte)(localTID >> 24);

        return result;
    }`
