### ISSUE TITLE
5.1.0-RC2 depends on org.glassfish.mq:mq-distribution:5.1.3 which doesn't exist

### ISSUE THREAD

**Issue by candrews** [eclipse-ee4j/glassfish#22717]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* GlassFish Version (and build number): 5.1.0-RC2
* JDK version: n/a
* OS: n/a
* Database: n/a

----------

## Problem Description
Glassfish depends on org.glassfish.mq:mq-distribution:5.1.3 which doesn't exist in Maven. Note that version 5.1.3 doesn't exist: https://repo1.maven.org/maven2/org/glassfish/mq/mq-distribution/

See https://github.com/eclipse-ee4j/glassfish/blob/5.1.0-RELEASE/appserver/pom.xml#L92
This issue was introduced in https://github.com/eclipse-ee4j/glassfish/pull/22659 by @arjantijms 

## Steps to reproduce
Use maven to depend on Glassfish, like this:
```
<build>
       	<plugins>
                <plugin>
                  <groupId>org.glassfish.embedded</groupId>
                  <artifactId>maven-embedded-glassfish-plugin</artifactId>
                  <version>5.1</version>
                  <configuration>
                  <dependencies>
                    <dependency>
                      <groupId>org.glassfish.main.extras</groupId>
                      <artifactId>glassfish-embedded-all</artifactId>
                      <version>5.1.0-RC2</version>
                    </dependency>
                  </dependencies>
                </plugin>
        </plugins>
</build>
```
The result is a dependency resolution error like this:
```
[ERROR] Failed to execute goal org.glassfish.embedded:maven-embedded-glassfish-plugin:5.1:run (default-cli) on project PRPS_Application: Execution default-cli of goal org.glassfish.embedded:maven-embedded-glassfish-plugin:5.1:run failed: Plugin org.glassfish.embedded:maven-embedded-glassfish-plugin:5.1 or one of its dependencies could not be resolved: Could not find artifact org.glassfish.mq:mq-distribution:zip:5.1.3 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```

## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"
This issue blocks the use of Glassfish from Maven.

**Comment by romain-grecourt** [comment]
This is an oversight, OpenMQ 5.1.3 wasn't released to Maven Central ; it is still in OSSRH staging https://oss.sonatype.org/content/repositories/staging/org/glassfish/mq/mq-distribution/5.1.3/

@senivam is taking care of that.
CC @m0mus

**Comment by candrews** [comment]
5.1.3 is now in Maven resolving this issue.

http://central.maven.org/maven2/org/glassfish/mq/mq-distribution/5.1.3/

Thank you!

**Comment by arjantijms** [comment]
@romain-grecourt 
>This is an oversight, OpenMQ 5.1.3 wasn't released to Maven Central ; it is still in OSSRH staging

It wasn't an oversight, OpenMQ 5.1.3 has a dependency on `org.glassfish.hk2:hk2-inhabitant-generator:2.5.0` which isn't available in Maven Central.

So the OpenMQ 5.1.3 that someone has released now is probably broken.

**Comment by m0mus** [comment]
This commit updates config-generator version in OpenMQ to 5.0.1. OpenMQ 5.1.3 released yesterday includes this commit. There should be no problem. 
@senivam please confirm.

**Comment by senivam** [comment]
prior to 5.1.4-RC1 generation (which introduced hk2.config-generator version upgrade to 5.1.0-RC2) the version of hk2.config-generator was 

`<hk2.config-generator.version>5.0.1</hk2.config-generator.version>`

**Comment by romain-grecourt** [comment]
@arjantijms `mq-distribution` is the only Maven artifact of OpenMQ and it does not have any transitive dependencies. If that is correct then there is nothing broken, right ?
