### ISSUE TITLE
quicklook test fail on simple bv servlet

### ISSUE THREAD

**Issue by PatrickHuang888** [eclipse-ee4j/glassfish#22727]
## Environment Details
* GlassFish Version (and build number):
5.1.0
* JDK version:
1.8
* OS:
linux
* Database:
none
----------

## Problem Description
```console
  [testng] FAILED: test_BV_10
   [testng] java.lang.AssertionError: Unable to find match for regex (?s)(?m).*case3: ConstraintViolation: message: must not be null propertyPath: listOfString.* in output from request to http://localhost:8080/simple-bv-servlet/test/bv_10 expected [true] but found [false]

 [testng] FAILED: test_BV_20
   [testng] java.lang.AssertionError: Unable to find match for regex (?s)(?m).*case0: ConstraintViolation: message: must not be null propertyPath: listOfString.*<list element>.* in output from request to http://localhost:8080/simple-bv-servlet/test/bv_20 expected [true] but found [false]
```
## Steps to reproduce
mvn -f appserver/tests/quicklook/pom.xml test -Dglassfish.home=appserver/distributions/glassfish/target/stage/glassfish5/glassfish

**Comment by romain-grecourt** [comment]
This test is known to work only with US locale.
Can you try to export `LANG=C` and run this test again.

BTW, why are you trying to run the quicklook test on a release version ? This codebase has passed many tests as part of the release process.

**Comment by PatrickHuang888** [comment]
Yes, using LANG=C can pass the tests.
and I just tried some quicklook test first as a tasting of tests to  get familiar of tests module.
