### ISSUE TITLE
Could not resolve dependencies

### ISSUE THREAD

**Issue by roghib** [eclipse-ee4j/glassfish#22721]
[ERROR] Failed to execute goal on project **dol**: Could not resolve dependencies for project org.glassfish.main.deployment:dol:glassfish-jar:5.0.1-SNAPSHOT: Failure to find jakarta.transaction:jakarta.transaction-api:jar:1.3.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

**Comment by pzygielo** [comment]
Did you follow instructions at [Building](https://github.com/eclipse-ee4j/glassfish/tree/EE4J_8#building), especially `-P staging` option?

**Comment by pzygielo** [comment]
Is your clone up to date? Current EE4J (2902690f) references transaction-api version 1.3.2.

**Comment by roghib** [comment]
<groupId>jakarta.transaction</groupId>
<artifactId>jakarta.transaction-api</artifactId>
<version>1.3.2</version>

add version

**Comment by roghib** [comment]
and also
[ERROR] Failed to execute goal on project amx-javaee: Could not resolve dependencies for project org.glassfish.main.common:amx-javaee:glassfish-jar:5.0.1-SNAPSHOT: Failure to find jakarta.transaction:jakarta.transaction-api:jar:1.3.1

**Comment by edbratt** [comment]
Are you trying to build Eclipse GlassFish, or Java EE GlassFish? -- 
There should be no dependencies on anything 5.0.1, in Eclipse GlassFish. 
If that exists, there is a problem. (I just did a quick search for 
5.0.1-SNAPSHOT and came up empty handed.) I believe the correct artifact 
ought to be 5.1.0-RC2 or something similar.

**Comment by roghib** [comment]
Thank you sir
I maybe wrong but I doubt it
the problem occurred after I cloned it and installed it
I just trying to install it using maven

**Comment by romain-grecourt** [comment]
This error happens in the Master branch. Looks like `jakarta.transaction:jakarta.transaction-api:1.3.1` was in OSSRH staging but the staging retention policy made the artifact disappear.

For now use the EE4J_8 branch, it shall be merged back to master shortly.
