### ISSUE TITLE
adminjsf.js  display errors 

### ISSUE THREAD

**Issue by jee2017** [eclipse-ee4j/glassfish#22737]
## Environment Details
* GlassFish Version (and build number):5.1.0-SNAPSHOT
* JDK version:1.8.0-161
* OS: windows
* Database:

----------

## Problem Description
Uncaught TypeError: table.initAllRows is not a function
    at Object.initAllRows (adminjsf.js:2068)
    at <anonymous>:1:124

adminjsf.js:2353 Uncaught ReferenceError: webui is not defined
    at Object.handleResponse [as onComplete] (adminjsf.js:2353)
    at XMLHttpRequest.AjaxEngine.req.xmlReq.onreadystatechange (jsf.js.jsf?ln=javax.faces:1)

## Steps to reproduce
Turn to http://localhost:4848/common/index.jsf
 sign in ,and  click Domain,and click Applications Configuration,and try to  delete Additional  Properties

## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"
can not  delete Applications Configuration  Additional  Properties

**Comment by jee2017** [comment]
5.0 versions did not have this problem

**Comment by bshannon** [comment]
@jee2017 Did you close this because it has been fixed?

**Comment by jee2017** [comment]
> @jee2017 Did you close this because it has been fixed?

Not yet. 
 
Some JavaScript codes throw  exception.

Such as ：
1.webui/suntheme/common.body = new webui/suntheme/body('_common_index.jsf', '/common/index.jsf',null,null,'com_sun_webui_util_FocusManager_focusElementId');

（in http://localhost:4848/common/index.jsf）Error:Invalid left-hand side in assignment

2. webui.suntheme.hyperlink.submit = admingui.woodstock.hyperLinkSubmit;

（in adminjsf.js）Error: Uncaught ReferenceError: webui is not defined

**Comment by bshannon** [comment]
I don't understand.  If it's not fixed, why did you close it?

**Comment by jee2017** [comment]
Sorry， I thought I could solve this problem before, and I tried several times, but failed. Can you please help me ?

**Comment by jee2017** [comment]
Global scopes are no longer recommended  by modern DOJO. But adminjsf.js still uses  global scopes, and it causes problems. Will it be fixed later?

**Comment by bshannon** [comment]
@arjantijms is this something you could help with?  If so, please reopen this bug.

Thanks.

**Comment by karlkras** [comment]
@arjantijms agreed this is a major headache and needs to be addressed:
```
```
![glassfishjs](https://user-images.githubusercontent.com/6694224/79903593-32f77f00-83c8-11ea-8312-3b83e030fb54.png)
