### ISSUE TITLE
ignoreJspFragmentErrors does not work

### ISSUE THREAD

**Issue by caim2015** [eclipse-ee4j/glassfish#22757]
## Environment Details
* GlassFish Version (and build number):V4 or V5
* JDK version:JDK8
----------

## Problem Description
My test sample is very simple.
Only two JSPs.
1.moto.jsp
<pre>
<%@ page contentType="text/html; charset=utf-8" %>
<%@ page pageEncoding="utf-8" %>
<%
    String s_sheet = "../../StyleSheet/style.css";
    String str = "aaa";
%>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
 <title>moto.jsp</title>
 <link rel="stylesheet" type="text/css" href="<%=s_sheet%>" />
</head>
<body>
 <%@ include file="./b/button.jsp"%>
</body>
</html>
</pre>
2.button.jsp
<pre>
<%@ page contentType="text/html; charset=utf-8" %>
<%@ page pageEncoding="utf-8" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">

<% if ("aaa".equals(str)){ %>
　　<button class="button" type="submit">Button</button>
<% } %>
</pre>
When I deploy my sample,[Precompile JSPs]is selected from Web Console, I get this error：
<pre>
PWC6197: An error occurred at line: 6 in the jsp file: /page/b/button.jsp
PWC6199: Generated servlet error:
cannot find symbol
  symbol:  variable  str
  location: class org.apache.jsp.page.b.button_jsp
</pre>
In order to ignore this error, I set "ignoreJspFragmentErrors" to true.
but it does not work.

[sample_NO.zip](https://github.com/eclipse-ee4j/glassfish/files/3280614/sample_NO.zip)

**Comment by caim2015** [comment]
When I change 'relative' path to 'absolute' path like the following,it becomes work.
The precompilation error is successfully ignored.
<pre>
<%@ include file="./b/button.jsp"%>
↓
<%@ include file="/page/b/button.jsp"%>
</pre>

As we all know,in the JSP Include directive using 'relative' and 'absolute' path both are valid.
So,I think resolve the name of the file make a mistake in the GF.

**Comment by nitind** [comment]
The JSP specification recommends the `.jsp` extension be used only for files corresponding to top level JSP files, forming a complete JSP page when processed. What happens if you use `.jspf` for the fragment file name and change nothing else?

**Comment by caim2015** [comment]
> 
> 
> The JSP specification recommends the `.jsp` extension be used only for files corresponding to top level JSP files, forming a complete JSP page when processed. What happens if you use `.jspf` for the fragment file name and change nothing else?

If `.jsp` is changed to `.jspf`, the error do not happen.
Because even if [Precompile JSPs] is selected,  the "button.jspf" is not be precompiled.
Only the `.jsp`  , `.jspx` files are precompile targets.
<pre>
button.jsp
↓
button.jspf

<%@ include file="./b/button.jsp"%>
↓
<%@ include file="./b/button.jspf"%>
</pre>
