### ISSUE TITLE
making Glassfish Nucleus HK2 Modules buildable with JDK11

### ISSUE THREAD

**Issue by rlfnb** [eclipse-ee4j/glassfish#22754]
## Environment Details
* GlassFish Version (and build number): git master
* JDK version: "11.0.2" 2019-01-15 LTS
* OS: Linux 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64 GNU/Linux
* Database: NONE

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"
Tried to build with Java11 and Maven 3.5.4 Glassfish master to find out what exactly is missing ATM to support migration towards Java11
`
# my current fork, lifted the source/target version and added the jaxb api to pom
git clone git@github.com:rlfnb/glassfish.git && cd glassfish 
export JAVA_HOME=/usr/lib/jvm/jdk-11.0.2 && export PATH=$JAVA_HOME/bin:/usr/bin:/bin:/home/rlfnb/java/apache-maven-3.5.4/bin
mvn -Pstaging install
.... omitted for readability .....
[ERROR] Failed to execute goal org.glassfish.build:command-security-maven-plugin:1.0.10:check (default-check) on project config-types: Error loading config beans: java.lang.RuntimeException: org.apache.maven.plugin.MojoExecutionException: Error analyzing java/lang/Object: IllegalArgumentException -> [Help 1]
`
I have no idea, what the plugin does and who's maintaining it. https://github.com/javaee/command-security-maven-plugin is already archived, so is it still needed at all? Can I remove it from nucleus/parent/pom.xml? If not, where's the new codebase to make the plugin java11 aware?

## Impact of Issue
Solving this issue might make the HK2 module at least compilable with Java11

[//]: # "Please choose one each Type, Component, and Priority label"
Glassfish, HK2, Blocker

**Comment by Cousjava** [comment]
The maintained version of the plugin is now at https://github.com/eclipse-ee4j/glassfish-security-plugin. To make it Java 11 aware asm needs to be upgraded, which I have made a PR for at https://github.com/eclipse-ee4j/glassfish-security-plugin/pull/7

**Comment by rlfnb** [comment]
all works fine now and glassfish builds completely with Java11 and Maven 3.5.4 as long as the new glassfish-security-plugin is used. Maybe, one someone (@Cousjava ) can take care of it and release it, so its available via central repo as well?

**Comment by rlfnb** [comment]
Any news here or can I disable the org.glassfish.build:command-security-maven-plugin safely and PR it?

**Comment by hs536** [comment]
command-security-maven-plugin 1.0.11 using asm 7.1 has already been published to Maven Central:  
https://mvnrepository.com/artifact/org.glassfish.build/command-security-maven-plugin/1.0.11

**Comment by Cousjava** [comment]
Fixed by #23029
