### ISSUE TITLE
Suspicious implementation of EnvironmentProperty.hasAValue method

### ISSUE THREAD

**Issue by pzygielo** [eclipse-ee4j/glassfish#22763]
## Environment Details
* GlassFish Version (and build number): current master (4e96e31c36b132b66080a8a5c94534d559735115)
* JDK version: n/a
* OS: n/a
* Database: n/a

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
Suspicious implementation of `EnvironmentProperty.hasAValue` method:
https://github.com/eclipse-ee4j/glassfish/blob/eac66d65e6a8eccedaaf40fac0e514d12c71e314/appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/EnvironmentProperty.java#L293-L295

It returns `false` for Properties constructed **with** value, that `setValue` was never called on:
https://github.com/eclipse-ee4j/glassfish/blob/4e96e31c36b132b66080a8a5c94534d559735115/appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/EnvironmentProperty.java#L105-L110

**Comment by bshannon** [comment]
Yes, it looks weird.  I would need to understand how `hasAValue` and `isSetValueCalled` are used to determine whether it's a bug, as well as understanding the use of the no-args constructors vs. the constructors that take a value.
