### ISSUE TITLE
Description of property is lost

### ISSUE THREAD

**Issue by pzygielo** [eclipse-ee4j/glassfish#22762]
## Environment Details
* GlassFish Version (and build number): current master (4e96e31c36b132b66080a8a5c94534d559735115)
* JDK version: n/a
* OS: n/a
* Database: n/a

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
Constructor
https://github.com/eclipse-ee4j/glassfish/blob/eac66d65e6a8eccedaaf40fac0e514d12c71e314/appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/RoleReference.java#L53-L57
calls super, but there at second position is value, not description:
https://github.com/eclipse-ee4j/glassfish/blob/eac66d65e6a8eccedaaf40fac0e514d12c71e314/appserver/deployment/dol/src/main/java/com/sun/enterprise/deployment/EnvironmentProperty.java#L95-L97

**Comment by bshannon** [comment]
Yes, it looks like a bug.
