### ISSUE TITLE
how to configure  pom file for openJDK11

### ISSUE THREAD

**Issue by 141801** [eclipse-ee4j/glassfish#22761]
enviroment  openJDK11   Apache Maven 3.6.1  

I run mvn -Pstaging install  successfuly in JDK8 enviromennt
But when I run it in openJDK11 enviroment,I got the error as follows

<pre>
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project tiger-types: Compilation failure: Compilation failure:
[ERROR] Source option 5 is no longer supported. Use 6 or later.
[ERROR] Target option 1.5 is no longer supported. Use 1.6 or later.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :tiger-types
</pre>
I found the problem  is  "Your project uses maven-compiler-plugin with an old version which defaults to Java 5." from  https://github.com/jflex-de/jflex/issues/400  but I don't know how to solve the problem ,  it says that just adding the code

`
 <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
            <source>1.6</source>
            <target>1.6</target>
        </configuration>
    </plugin>
`

 in  pom.xml   but which pom.xml ?  I added  in the  pom.xml under glassfish-master but It not works

**Comment by 141801** [comment]
sovled by changing  1.5 to 1.6 in file  ./nucleus/hk2/tiger-types/pom.xml

**Comment by h-hub** [comment]
Hi, Is this the correct way to fix the issue?
- shouldn't it be mentioned in the READ.ME ?
- Can't we change the java version and fix the issue? instead of editing the POM ?

**Comment by romain-grecourt** [comment]
Feel free to submit a PR.

**Comment by h-hub** [comment]
Hi, I will submit a PR. Thanks.

**Comment by hygino82** [comment]
it does not work here

**Comment by arjantijms** [comment]
GlassFish now builds correctly with JDK11. The TCK certification, using JDK 11, also succeeded.
