### ISSUE TITLE
JAX-RS application not working on embedded glassfish

### ISSUE THREAD

**Issue by k2sd** [eclipse-ee4j/glassfish#22772]
## Environment Details
* GlassFish Version (and build number): 5.1.0
* JDK version: 8u211
* OS: Windows8.1

## Problem Description
Some JAX-RS applications don't work correctly with embedded glassfish.
If accessing the endpoint of the app, http status 404 is always returned.

## Steps to reproduce
Attached 2 files to reproduce the problem.  App.java in
"embeddedtest.zip" runs an embedded glassfish and just deploy war
file.  "testapp.war" is a tiny JAX-RS hello world application.

[reproduce.zip](https://github.com/eclipse-ee4j/glassfish/files/3360660/reproduce.zip)

After deploying the application, you can call it, like:

`curl http://localhost:8881/hello`

Expected output is just

```
Hello World
```

But it always returns http status 404. I guess some JAX-RS applications fail to be deployed with embedded glassfish server, but I can find no message on
the server.log.  The version 4.1.2 or 5.0 of embedded server works fine.

## Impact of Issue
some JAX-RS war applications might be unreacheable with embedded server.

**Comment by smillidge** [comment]
Fixed by #22773
