### ISSUE TITLE
Glassfish 4.1/Grizzly Out of Memory error

### ISSUE THREAD

**Issue by vinod489** [eclipse-ee4j/glassfish#22777]
We are experiencing out of memory and high CPU usage frequently in our applications running on glassfish 4.1. We analyzed the heap dump and found that 70% of the heap is retained by grizzly threads.

![image](https://user-images.githubusercontent.com/22427862/61529983-645dab80-aa40-11e9-97d6-25b12a22eb94.png)

We are in the process of upgrading the glassfish to 5. Want to know if the above issue was already fixed in the grizzly framework used in glassfish 4.1. Please let me know if any other info is required.

## Environment Details
* GlassFish Version (and build number): Glassfish 4.1 build 13
* JDK version: Zulu Open JDK 1.8.0_192
* OS: Linux 2.6.18-402.el5

**Comment by Cousjava** [comment]
The issue was fixed by eclipse-ee4j/grizzly/pull/2053, there has not been a release of grizzly since that point and so is not included in Glassfish.

**Comment by vinod489** [comment]
Thanks for the reply. Could you please let us know if there is any workaround for this issue or can we prepare and apply a patch with this fix? Please let me know if any other info is required.

**Comment by smillidge** [comment]
This project develops Eclipse GlassFish from version 5.1 onwards. Can you reproduce the issue on Eclipse GlassFish 5.1?

**Comment by Cousjava** [comment]
Grizzly was updated in GlassFish in #23003 which included the fix for this issue.
