### ISSUE TITLE
HttpTunnelServlet missing in imqhttp(s).war

### ISSUE THREAD

**Issue by mheydem** [eclipse-ee4j/glassfish#22774]
The imqhttp.war and imqhttps.war are delivered with glassfish in directory mq\lib.
When trying to deploy imqhttp(s).war multiple ClassNotFoundException: com.sun.messaging.jmq.httptunnel.tunnel.servlet.HttpTunnelServlet are thrown.

Opened duplicate in openmq project. (Possibly it is not a glassfish bug)
https://github.com/eclipse-ee4j/openmq/issues/479#issue-466859644

## Environment Details
* GlassFish Version (and build number): Release 5.1.0
* JDK version: openjdk version "1.8.0_202", Corretto-8.202.08.2
* OS: Windows 10

----------

## Problem Description
The imqhttp(s).war is missing the entire package com.sun.messaging.jmq.httptunnel
which usually contains the HttpTunnelServlet servlet.
The servlet class HttpTunnelServlet is expected to be there as specified in web.xml.

## Impact of Issue
It is not possible to tunnel mq via http(s)

**Comment by mheydem** [comment]
Payara 5.192 is also missing com.sun.messaging.jmq.httptunnel.tunnel.servlet.HttpTunnelServlet in imqhttp(s).war resp imqservlet.ajr.

**Comment by mheydem** [comment]
It is an openmq issue eclipse-ee4j/openmq#479
This could be left open until fixed for tracking.

**Comment by pzygielo** [comment]
Could you reopen this issue, (and close it when newer OpenMQ is integrated to glassfish) or add explicit comment that it will not be fixed, please?

**Comment by mheydem** [comment]
Hi @pzygielo @arjantijms. I could not find the fix in Glassfish 6 Milestone 1.
Actually it should be already integrated. What am I overlooking?
This issue results in complete fail of jms http(s) bridge.

**Comment by pzygielo** [comment]
@mheydem could you verify that released GF6 contains expected classes, please?
If so - please close the issue.
