### ISSUE TITLE
GF5.1 - Admin GUI 'theme' resources not available

### ISSUE THREAD

**Issue by c-jack** [eclipse-ee4j/glassfish#22775]
#### Environment 1
* GlassFish Version (and build number): 5.1 (default-private)
* JDK version:  OpenJDK 1.8.0_212
* OS:  Windows 10
* Database: Oracle XE

#### Environment 2
* GlassFish Version (and build number): 5.1 (default-private)
* JDK version:  Java SE 1.8.0_201-b09
* OS:  MacOS 10.14.3 (Mojave)
* Database: MySQL 8.0.16

----------

## Problem Description
The Admin GUI does not appear to deploy correctly, as core resources are not available.

The Admin GUI fails to find:
-  `json.js` at `http://localhost:4848/theme/META-INF/json/json.js`, and;
- `com_sun_faces_ajax.js` at `http://localhost:4848/theme/META-INF/com_sun_faces_ajax.js`

This results in further dependency issues in resources it _can_ find, such as `http://localhost:4848/resource/common/js/adminjsf.js` (which consequently reports issues such as `tree.clearAllHighlight is not a function`, which I expect is due to the missing js dependencies).

## Steps to reproduce
- Download Glassfish 5.1 from `https://www.eclipse.org/downloads/download.php?file=/glassfish/glassfish-5.1.0.zip`
- Start the default domain `domain1` for consistency (can recreate on any domain)
- Observe JS errors in browser at `http://localhost:4848`

*Important notes*
- As per the above information, this has been replicated with freshly downloaded builds on not only two very different laptops and Operating Systems, but also multiple other PCs by colleagues.
- This has been reproduced on the latest updated browsers for Opera, Firefox, Safai, Internet Explorer, and Edge (including cache clearing/resetting as per 101)
- Navigating to resource path directly produces a 404 for affected files.
- `/theme/META-INF/dojo/dojo.js` and `theme/META-INF/prototype/prototype.js` *are* accessible, suggesting that this is affecting only the two specific files.
- Both Glassfish `4.1.2` and `3.1.2.2 (build 5)` do not suffer with the same `json.js` issue, but have the same issue with `com_sun_faces_ajax.js` not being available.
- The `com_sun_faces_ajax.js` has historically been linked with OpenJDK compatibility, however on MacOS (using Version 8 Update 211 of the Oracle JDK build), the same issue is present on GF 5.1.
- The same issue is referenced [here, in issue #22739](https://github.com/eclipse-ee4j/glassfish/issues/22739#issuecomment-475599617), but seems to be unrelated to that issue and the fix (as is the linked comment).
- **This issue does not exist in versions prior to Glassfish 5.0.1**, as referenced in this unresolved but (seemingly) identical closed issue: https://github.com/eclipse-ee4j/glassfish/issues/22737

## Impact of Issue
The Admin GUI is basically non-functional.  Pages such as 'JDBC Connection Pools' have errors that make administration impossible.

**Comment by c-jack** [comment]
Note that `json.js` *is* available at `theme/META-INF/json2_0/json.js` 
as per the structure of `install/applications/_admingui/WEB-INF/extra/json-2.0.jar`

**Comment by karlkras** [comment]
Is there any work being done on this stuff? We've got a 5.1.0 build with a useless admin GUI.

**Comment by mferretti** [comment]
same here: just installed 5.1 and got the exactly same problem
