### ISSUE TITLE
com.sun.mail:jakarta.mail:jar:1.6.4 failed

### ISSUE THREAD

**Issue by 141801** [eclipse-ee4j/glassfish#22783]
ERROR] Failed to execute goal on project container-common: Could not resolve dependencies for project org.glassfish.main.common:container-common:glassfish-jar:5.1.0-SNAPSHOT: Failed to collect dependencies at com.sun.mail:jakarta.mail:jar:1.6.4: Failed to read artifact descriptor for com.sun.mail:jakarta.mail:jar:1.6.4: Could not transfer artifact com.sun.mail:jakarta.mail:pom:1.6.4 from/to sonatype-nexus-staging (https://oss.sonatype.org/content/repositories/staging): Not authorized by proxy -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :container-common

**Comment by bshannon** [comment]
It looks like something is preventing you from accessing the staging repository:

> Could not transfer artifact com.sun.mail:jakarta.mail:pom:1.6.4 from/to sonatype-nexus-staging (https://oss.sonatype.org/content/repositories/staging): Not authorized by proxy 

Perhaps your Maven proxy configuration is not correct?

**Comment by 141801** [comment]
Thanks for your reply.
but I still don't know the problem of my mvn proxy setting 
![image](https://user-images.githubusercontent.com/42635299/62184671-01eaa080-b39a-11e9-85e7-71760db8e236.png)

I went back to  864800f commit as build sucessfully  
![image](https://user-images.githubusercontent.com/42635299/62184737-46763c00-b39a-11e9-9c95-a36befffa1f9.png)

**Comment by bshannon** [comment]
That's before the update to Jakarta Mail 1.6.4, which is only available from the staging repository.
Note that the request URL uses https, but your proxy configuration is for http.  Maven only
supports one proxy configuration at a time.  What I need to do is to add the http proxy configuration
such as what you have, but then when running Maven I use:

    mvn -Dhttps.proxyHost=proxyhost -Dhttps.proxyPort=8080

My proxy doesn't require username and password, so I don't know how to specify those
on the command line.
