### ISSUE TITLE
GlassFish fails to build from scratch

### ISSUE THREAD

**Issue by bshannon** [eclipse-ee4j/glassfish#22782]
I tried to build Eclipse GlassFish in an environment where I had
never built GlassFish before (empty local Maven repository).

The build failed with this:

[ERROR] Plugin org.glassfish.main.hk2:config-generator:5.1.0-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact org.glassfish.main.hk2:config-generator:jar:5.1.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException

I needed to build nucleus/hk2 first, then the build succeeded.

I think the problem is the plugin configuration in nucleus/pom.xml
where it references the version of org.glassfish.main.hk2:config-generator
that's going to be built by this project.  That doesn't work.

**Comment by bshannon** [comment]
@romain-grecourt you probably know the right way to fix this dependency.

**Comment by romain-grecourt** [comment]
Did you do a `mvn clean install` or just `mvn install` ?

**Comment by bshannon** [comment]
mvn clean; mvn install

**Comment by romain-grecourt** [comment]
The failure occurred with the `clean` right ?
IIRC the trick about building and using the plugin in the same build is that is only works with install.

**Comment by bshannon** [comment]
Yes, the failure occurred with clean.  Isn't it a bug if "mvn clean" doesn't work?
Isn't there a better way to break this loop?

**Comment by romain-grecourt** [comment]
The only way to break this loop is to move the plugin out of the workspace. Since this was moved out of HK2 we'd need to find a new place for the old HK2 config.

**Comment by bshannon** [comment]
Sigh, ok, I'll update my build scripts.  :-(
