### ISSUE TITLE
maven repository error

### ISSUE THREAD

**Issue by Jpmadan84** [eclipse-ee4j/glassfish#22811]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* GlassFish Version (and build number):5.1.0-SNAPSHOT
* JDK version:1.8.0_211
* OS:Windows 10
*Maven version: 3.6.1

On downloading the latest source code version from GIT and executed following command, error comes.

Steps to reproduce: 
1) Download the glassfish source code version as mentioned above and 
2) Execute following step
command: mvn package -DskipTests

Error: [ERROR] Failed to execute goal on project hk2-config: Could not resolve dependencies for project org.glassfish.main.hk2:hk2-config:glassfish-jar:5.1.0-SNAPSHOT: Failure to find org.glassfish:jakarta.el:jar:3.0.3 in https://repo.maven.apache.org/maven2

Observation: When I go to maven2 central in https://repo.maven.apache.org/maven2, I do not find the version 3.0.3 of org.glassfish:jakarta.el:jar. The latest present there is 3.0.2 as of now which I guess is the reason of this error.

----------

**Comment by bshannon** [comment]
You didn't follow the instructions [here](https://github.com/eclipse-ee4j/glassfish/blob/master/README.md).
You need to use the staging profile when building the currently-under-development sources.

Try that and let me know if you still have problems.

**Comment by Jpmadan84** [comment]
Sorry. Yes that solved the problem.
