### ISSUE TITLE
How to Access glassfish log location from the deplyed war

### ISSUE THREAD

**Issue by krishnakittu** [eclipse-ee4j/glassfish#22815]
glassfish 5.1

How to get the glassfish log location in the deployed War.

**Comment by bshannon** [comment]
I assume you want to do this independent of where GlassFish is installed
or what domain you're running in...  Good question!  There's probably an
environment variable or System property that will give you the base directory
for the domain.

**Comment by krishnakittu** [comment]
I can able to get the logs location by property **${com.sun.aas.instanceRoot}/logs/server.log**  , It is the default location. But here if anyone changes the log setting from glassfish UI configuration --> server config -> Log File. How can i read that value.

**Comment by bshannon** [comment]
I don't know.  You may have to read and parse the domain.xml to find the configuration.
A reasonable enhancement might be to set another property to the location of the log file.

What do you want to do with the log file when you find it?

**Comment by krishnakittu** [comment]
I want to display it on ui for the admin of the application. So that error will be easily rectified  without taking rdc of the server if possible. I already displayed my deployed war logs in  browser. If unexpected error comes it is displayed on server logs. So for this reason I want to display the same on browser

**Comment by krishnakittu** [comment]
Bshannon can we expect this in further releases.

**Comment by bshannon** [comment]
I can't commit to anything.  It will depend on whether someone in this project decides
to add this, or someone in the community submits a pull request for this feature.
If it's important to you, you might want to look into what it would take to make GlassFish
define a new property with the log file location after reading the domain.xml file.
Looking at how the other properties are set might get you started.  If you submit a
pull request, I'll evaluate it.

**Comment by smillidge** [comment]
This class manages the Logging config https://github.com/eclipse-ee4j/glassfish/blob/master/nucleus/common/common-util/src/main/java/com/sun/common/util/logging/LoggingConfigImpl.java 

You can parse the looging.properties file and look for the `com.sun.enterprise.server.logging.GFFileHandler.file` property

**Comment by krishnakittu** [comment]
Thanks smilllidge. Great support . I am closing this ticket now.
