### ISSUE TITLE
Microprofile OpenAPI does not scann external libraries?

### ISSUE THREAD

**Issue by rsoika** [eclipse-ee4j/glassfish#22822]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* GlassFish Version : Payara 5.192
* JDK version: openjdk:8u171-jdk
* OS: Docker Image payara/server-full
* Database: none

----------

## Problem Description

I have a question concerning Microprofile OpenAPI and external libraries. 

I have a web application including a library with jax-rs classes. Running on Payara 5.192 the server ignore my classes from the library located in /WEB-INF/lib and does not publish any information under /openapi

 JAX-RS classes which are part of the project itself (WEB-INF/classes/) are detected correctly. 
Same application running on OpenLiberty works out of the box.

I did not found any mp.property to define the treatment of external libraries. I tried for example the config option 'mp.openapi.scan.packages' but without any changed behavior.

Is there a rule or definition how to define a common behavior in different servers?

## Steps to reproduce
 * Deploy Web Application containing JAX-RS classes in external jar located in WEB-INF/lib/

**Comment by romain-grecourt** [comment]
GlassFish does not implement any Microprofile config properties.

- Can you actually reproduce this against GlassFish 5 instead of Payara.
- Can you provide a reproducer or steps to reproduce ?

**Comment by rsoika** [comment]
I currently have no way to verify that on Glassfish.

I have created a reproducer app here:
https://github.com/rsoika/glassfish-issue-22822

**Comment by smillidge** [comment]
Payara is not GlassFish I would recommend raising this issue on the Payara project.
