### ISSUE TITLE
How to set Default web_module through Deployment of war

### ISSUE THREAD

**Issue by krishnakittu** [eclipse-ee4j/glassfish#22832]
## Environment Details
* GlassFish Version (and build number):5.1
* JDK version:1.8
* OS:ubuntu

I have a 10 application deployed in app server. Whenever i am undeploying and deploying the application which is default web module the settings are lost. On each deployment i need to set the default web-module through admin console. Is there any way to set automatically default module while deployment itself.

**Comment by krishnakittu** [comment]
Team can you please give any thoughts on this

**Comment by krishnakittu** [comment]
HI 
Any one please give me the solution to achieve this.

**Comment by smillidge** [comment]
set the context root to '/' ? Is that what you are trying to achieve?
