### ISSUE TITLE
"InjectionException: Wrong invocation type" happend when create UIComponent in EJBapp

### ISSUE THREAD

**Issue by caim2015** [eclipse-ee4j/glassfish#22833]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* GlassFish Version (and build number):V4.0
* JDK version:8
* OS:windows or linux
* Database:none

----------

## Problem Description
I run the application on GlassFish 4.0, but I get this error:
<pre>
[2019-09-06T10:36:20.076+0800] [glassfish 4.0] [SEVERE] [] [javax.enterprise.resource.webcontainer.jsf.application] [tid: _ThreadID=25 _ThreadName=http-listener-1(5)] [timeMillis: 1567737380076] [levelValue: 1000] [[
  Unable to invoke @PostConstruct annotated method on instance javax.faces.HtmlInputText
com.sun.faces.spi.InjectionProviderException: com.sun.enterprise.container.common.spi.util.InjectionException: Wrong invocation type
	at org.glassfish.faces.integration.GlassFishInjectionProvider.invokePostConstruct(GlassFishInjectionProvider.java:231)
	at com.sun.faces.application.ApplicationImpl.newThing(ApplicationImpl.java:1752)
	at com.sun.faces.application.ApplicationImpl.createComponentApplyAnnotations(ApplicationImpl.java:1917)
	at com.sun.faces.application.ApplicationImpl.createComponent(ApplicationImpl.java:928)
	at bean.EJB1.doTest1(EJB1.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
	at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
	at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4695)
	at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:630)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	at com.sun.ejb.EjbInvocation.proceed(EjbInvocation.java:582)
	at org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.ejb.containers.interceptors.AroundInvokeInterceptor.intercept(InterceptorManager.java:883)
	at com.sun.ejb.containers.interceptors.AroundInvokeChainImpl.invokeNext(InterceptorManager.java:822)
	...
Caused by: com.sun.enterprise.container.common.spi.util.InjectionException: Wrong invocation type
	at org.glassfish.faces.integration.GlassFishInjectionProvider.getNamingEnvironment(GlassFishInjectionProvider.java:262)
	at org.glassfish.faces.integration.GlassFishInjectionProvider.invokePostConstruct(GlassFishInjectionProvider.java:229)
	... 95 more
</pre>
Here is the GF source.
https://github.com/javaee/glassfish/blob/master/appserver/web/jsf-connector/src/main/java/org/glassfish/faces/integration/GlassFishInjectionProvider.java
<pre>
	private JndiNameEnvironment getNamingEnvironment() 
246          throws InjectionException { 
247         ComponentInvocation inv = invokeMgr.getCurrentInvocation(); 
248 
 
249         if (inv != null) { 
250 
 
251             if (inv.getInvocationType()== ComponentInvocation.ComponentInvocationType.SERVLET_INVOCATION) { **
252 
 
253                 JndiNameEnvironment componentEnv = (JndiNameEnvironment) 
254                      inv.jndiEnvironment; 
255 
 
256                 if (componentEnv != null) { 
257                     return componentEnv; 
258                 } else { 
259                     throw new InjectionException("No descriptor registered for " + " current invocation : " + inv); 
260                 } 
261             } else { 
262                 throw new InjectionException("Wrong invocation type"); 
263             } 
264         } else { 
265             throw new InjectionException("null invocation context"); 
266         } 
267     } 
</pre>
When I debug,I find my invocationType is "EJB_INVOCATION",so the InjectionException("Wrong invocation type") is thrown.

Here are my questions:
Why the EjbInvocation is not supported?
## Steps to reproduce
In my EJBapplication, I create the UIComponent of HtmlInputTextas as follows:
     
EJBapp demo code:
<pre>
   @Stateless(mappedName="ejb1")
public class EJB implements EJB1Remote{
	
	public void doTest1() {
		
		try { 
     
		FacesContext context = FacesContext.getCurrentInstance();
		HtmlInputText uiComponent = (HtmlInputText) context.getApplication().createComponent(HtmlInputText.COMPONENT_TYPE);
			
		} catch (Exception e) {
			System.out.println("**********" + e);
			throw new RuntimeException (e.getMessage());
		}
	}
}
</pre>

**Comment by caim2015** [comment]
Why the EjbInvocation is not supported?
Please give some thoughts on this.

**Comment by smillidge** [comment]
This project only develops Eclipse GlassFish. Your issue references GlassFish v4 which is not an eclipse project. Can you reproduce on Eclipse GlassFish 5.1?

**Comment by caim2015** [comment]
> 
> 
> This project only develops Eclipse GlassFish. Your issue references GlassFish v4 which is not an eclipse project. Can you reproduce on Eclipse GlassFish 5.1?

yes,I can by the following EJBapp demo code:
<pre>
@Stateless(mappedName="ejb1")
@TransactionManagement(TransactionManagementType.CONTAINER)
public class EJB1
  implements EJB1Remote
{
  public void doTest1()
  {
    try
    {
      FacesContext context = FacesContext.getCurrentInstance();

      ProtectedBean protectedBean = new ProtectedBean();

      ApplicationAssociate associate = ApplicationAssociate.getInstance(context.getExternalContext());
      InjectionProvider injectionProvider = associate.getInjectionProvider();

      injectionProvider.invokePostConstruct(protectedBean);
    }
    catch (Exception e)
    {
      throw new RuntimeException(e.getMessage());
    }
  }
}
</pre>
reproduce step:
1.deploy the app;
2.access http://193.160.33.137:81/webJSF/index.jsf 
3.click [Submit]

app:
[toGF.zip](https://github.com/eclipse-ee4j/glassfish/files/3696253/toGF.zip)

**Comment by smillidge** [comment]
Can you explain what you are trying to do with this code. I don't have the whole application source. Do you think there is a bug in GlassFish?

**Comment by caim2015** [comment]
At first,I created a JSF UIComponent in my servlet(Web) like following:

demo1
<pre>
import javax.faces.component.html.HtmlInputText;
import javax.faces.context.FacesContext;
   
public class MyServlet extends HttpServlet {   
	
    protected void doPost(HttpServletRequest request, HttpServletResponse response)   
    throws ServletException {   
        response.setContentType("text/html;charset=UTF-8");   
        PrintWriter out = response.getWriter();   
        try { 
        	
        	FacesContext context = FacesContext.getCurrentInstance();
        	HtmlInputText uiComponent = (HtmlInputText) context.getApplication().createComponent(HtmlInputText.COMPONENT_TYPE);
           ...  
             
        } catch (Exception e) {
			// TODO 自動生成された catch ブロック
			e.printStackTrace();
		} 
    }
</pre>

It works fine in GFV4.0.

After,I created the same JSF UIComponent in my EJB app,"InjectionException: Wrong invocation type" happend. 

demo2:
<pre>
import javax.faces.component.html.HtmlInputText;
import javax.faces.context.FacesContext;

@Stateless(mappedName="ejb1")
public class EJB implements EJB1Remote{
	
	public void doTest1() {		
		try {      
		FacesContext context = FacesContext.getCurrentInstance();
		HtmlInputText uiComponent = (HtmlInputText) context.getApplication().createComponent(HtmlInputText.COMPONENT_TYPE);
			
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
</pre>

By debuging source,
I find that [GlassFishInjectionProvider.getNamingEnvironment()] is called by the JSF source[ ApplicationImpl.createComponent()].
<pre>
Thread[http-listener-1(1)] (suspend (GlassFishInjectionProvider at 249 line breakpoint))    
    GlassFishInjectionProvider.getNamingEnvironment() 行: 249    -->GF source
    GlassFishInjectionProvider.invokePostConstruct(Object) 行: 229   -->GF source 
    ApplicationImpl.newThing(String, ApplicationInstanceFactoryMetadataMap<String,Object>) 行: 1752    -->JSF source
    ApplicationImpl.createComponentApplyAnnotations(FacesContext, String, String, boolean) 行: 1917    -->JSF source
    ApplicationImpl.createComponent(String) 行: 928  -->JSF source
    ...
</pre>
	
Here is the GF source.
https://github.com/javaee/glassfish/blob/master/appserver/web/jsf-connector/src/main/java/org/glassfish/faces/integration/GlassFishInjectionProvider.java
<pre>
	private JndiNameEnvironment getNamingEnvironment() 
246          throws InjectionException { 
247         ComponentInvocation inv = invokeMgr.getCurrentInvocation(); 
248 
 
249         if (inv != null) { 
250 
 
251             if (inv.getInvocationType()== ComponentInvocation.ComponentInvocationType.SERVLET_INVOCATION) { **
252 
 
253                 JndiNameEnvironment componentEnv = (JndiNameEnvironment) 
254                      inv.jndiEnvironment; 
255 
 
256                 if (componentEnv != null) { 
257                     return componentEnv; 
258                 } else { 
259                     throw new InjectionException("No descriptor registered for " + " current invocation : " + inv); 
260                 } 
261             } else { 
262                 throw new InjectionException("Wrong invocation type"); 
263             } 
264         } else { 
265             throw new InjectionException("null invocation context"); 
266         } 
267     } 
</pre>

In my servlet app,invocationType is "SERVLET_INVOCATION",so it works fine.
In Ejb servlet app,invocationType is "EJB_INVOCATION",so the InjectionException("Wrong invocation type") is thrown.

Why the EjbInvocation is not supported?
Is it the reason for JSF is a web-based application framework ?

**Comment by smillidge** [comment]
Why would you one to create a text component in a Remote EJB call?

**Comment by caim2015** [comment]
> 
> 
> Why would you one to create a text component in a Remote EJB call?

In our EJB application the information of textbox,pulldownList...are stored in the DataBase. 
When the information read from the DataBase is  textbox do the operation(create a text component).

**Comment by caim2015** [comment]
Hi, smillidge,
Is it wrong to create a text component in a Remote EJB call?
