### ISSUE TITLE
error in glassfish - When I'm deploying my application

### ISSUE THREAD

**Issue by lakshitha1629** [eclipse-ee4j/glassfish#22844]
Please help me to fix this (error in glassfish - When I'm deploying my application)

(glassfish 4.1,Windows 8,netbeans 8.2)

HTTP Status 500 - Internal Server Error

Type Exception report

message Internal Server Error

description The server encountered an internal error that prevented it from fulfilling this request.

exception java.lang.RuntimeException: Error in multipart initialization

**Comment by bshannon** [comment]
This project is only supporting GlassFish 5.x, can you reproduce your problem with Eclipse GlassFish 5.1?  If you can, we'll need a lot more detail about what you're doing.  Can you include the code that's failing, and the server log file showing the failure?  A complete reproducible example application would be ideal.

**Comment by lakshitha1629** [comment]
#bshannon this the old project. it's work on my old laptop

**Comment by bshannon** [comment]
Sorry, I don't understand.  If it's working for you, can we close this issue?

**Comment by smillidge** [comment]
Closing the issue as against an old version of GlassFish. If you still experience the problem on Eclipse GlassFish 5.1 or above please request us to reopen the issue.
