### ISSUE TITLE
Release more frequently

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/glassfish#22841]
I hope Glassfish will apply a roll-up release by a monthly update or a quarter update like OpenLiberty.

And tag a LTS like version  for production use.

**Comment by smillidge** [comment]
This is now a community project at Eclipse Foundation therefore needs more contributors to have a regular release schedule. Are you able to help?

**Comment by hantsy** [comment]
I wish there are some opportunities to contribute a project like Glassfish, but I am not sure what is the fist step to get know with it.

**Comment by russgold** [comment]
I’d suggest that the first step would be to look at the various issues raised, to see what needs to be done.

**Comment by gerdogdu** [comment]
Can we close this issue?
