### ISSUE TITLE
Glassfish is starting the cluster node, domain.xml file is corrupted when the system is powered off at this time.

### ISSUE THREAD

**Issue by edamtrong1178** [eclipse-ee4j/glassfish#22856]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* GlassFish Version (and build number): 5
* JDK version: jdk1.8.0_212
* OS: Ubuntu 16
* Database: MySQL 5.7

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"
I have an issue related to the system is powered off and GF is starting. After the system is up again, then start Glassfish.
 => domain.xml file in cluster node has been corrupted with error:
com.sun.enterprise.universal.xml.MiniXmlParserException: "Xml Parser Error: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Premature end of file.
Check this file, it is empty.
## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"
1. Start domain.
2. Start cluster ./asadmin --port [portNumber] start-cluster [clustername]
3. Simulate the system is powered off ( as trigger to a power outage event)
4. Wait system back again, and start Glassfish as step 1,2.
Error: com.sun.enterprise.universal.xml.MiniXmlParserException: "Xml Parser Error: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Premature end of file.

## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"

[//]: # "Please choose one each Type, Component, and Priority label"
Is there any way to prevent this with a GF configuration?

**Comment by smillidge** [comment]
I am not aware of how to prevent this with a uncontrolled power down.

**Comment by edamtrong1178** [comment]
Hi,
As my observation, when starting GF instance, it seems GF has replaced domain.xml.bak to domain.xml  to load  the configuration. And if a trigger power off occurs at this time, domain.xml will be corrupted and domain.xml.bak has been gone. This makes GF impossible restore the configuration when starting again and the parsing XML exception is thrown.
Please let me know if i'm wrong :)
In my opinion, GF should keep the domain.xml.bak while starting and able to load the configuration from this file if domain.xml is corrupted.

**Comment by smillidge** [comment]
Thanks for the detailed observation. As Eclipse GlassFish is a community project we'd welcome a PR to fix the issue.
