### ISSUE TITLE
Rationalise Open Issues

### ISSUE THREAD

**Issue by smillidge** [eclipse-ee4j/glassfish#22875]
Last year we had a discussion on rationalising the open issues to get them to a manageable level. 
https://www.eclipse.org/lists/glassfish-dev/msg00053.html 

One of the things agreed was;

Close all issues filed against a version before 5.1 with a comment that if the issue is reproducible on 5.x then request the issue reopened.

**Comment by hs536** [comment]
I agree. I think closing them once is an effective way to clarify the issues that really need to be addressed.

**Comment by smillidge** [comment]
OK I will start closing issues when I have time.

**Comment by smillidge** [comment]
I created a GitHub action to mark all issues over 365 days old as stale. This should trigger a comment subsequently followed by closing the issue after 7 days

**Comment by gerdogdu** [comment]
Is it possible to decrease the 365 to some more reasonable day? Such as 90?
