### ISSUE TITLE
Consider splitting some GlassFish repositories off into separate projects.

### ISSUE THREAD

**Issue by bshannon** [eclipse-ee4j/glassfish#22870]
The Eclipse GlassFish project has a very large number of repositories.  Some of them
(e.g., hk2) evolve independently of GlassFish, with their own version number and release
schedule, making release reviews confusing at best as the review may only apply to a
subset of the repositories.

After the Eclipse GlassFish 5.1 release, we should consider splitting some of these
repositories off into their own projects.

**Comment by smillidge** [comment]
Transferring over to the Eclipse GlassFish project repo

**Comment by bshannon** [comment]
I'd love to see a proposal for what we can reasonably split out of the GlassFish project.

Should the criteria be anything that has its own release schedule and version number?

**Comment by smillidge** [comment]
I think that may be a little severe I think things that have a life outside of GlassFish may be better. 

My first thought was HK2 in the first instance. Are there other things you were thinking of?

**Comment by bshannon** [comment]
Here's an out-of-date list of source code repositories associated with the GlassFish project:

* https://github.com/eclipse-ee4j/bvtck-porting
* https://github.com/eclipse-ee4j/cditck-porting
* https://github.com/eclipse-ee4j/ditck-porting
* https://github.com/eclipse-ee4j/glassfish
* https://github.com/eclipse-ee4j/glassfish-build-maven-plugin
* https://github.com/eclipse-ee4j/glassfish-cdi-porting-tck
* https://github.com/eclipse-ee4j/glassfish-copyright-plugin
* https://github.com/eclipse-ee4j/glassfish-doc-plugin
* https://github.com/eclipse-ee4j/glassfish-fighterfish
* https://github.com/eclipse-ee4j/glassfish-ha-api
* https://github.com/eclipse-ee4j/glassfish-hk2
* https://github.com/eclipse-ee4j/glassfish-hk2-extra
* https://github.com/eclipse-ee4j/glassfish-jsftemplating
* https://github.com/eclipse-ee4j/glassfish-logging-annotation-processor
* https://github.com/eclipse-ee4j/glassfish-maven-embedded-plugin
* https://github.com/eclipse-ee4j/glassfish-repackaged
* https://github.com/eclipse-ee4j/glassfish-security-plugin
* https://github.com/eclipse-ee4j/glassfish-shoal
* https://github.com/eclipse-ee4j/glassfish-spec-version-maven-plugin
* https://github.com/eclipse-ee4j/glassfish-woodstock

Most of the Maven plugins probably don't need to be in the GlassFish repo.
Certainly hk2 doesn't.  Perhaps some of the others.

**Comment by smillidge** [comment]
I'm not that familiar with the maven plugins. Which of the above are used outside of the GlassFish project?

**Comment by smillidge** [comment]
So of the above I assume;

- *-porting are GlassFish project only to help run the TCK?
- fighterfish, ha-api, jsftemplating, logging-annoation-processor, repackaged, shoal and woostock are pretty much GlassFish specific?
- The rest are maven plugins?
Is that correct?

**Comment by bshannon** [comment]
> So of the above I assume;
> 
>     * *-porting are GlassFish project only to help run the TCK?
Yes.
> 
>     * fighterfish, ha-api, jsftemplating, logging-annoation-processor, repackaged, shoal and woostock are pretty much GlassFish specific?
Yes, although some of them had higher aspirations.
>     * The rest are maven plugins?
Yes.  The copyright plugin and the spec-version plugin are definitely used outside of GlassFish.

**Comment by smillidge** [comment]
Should these plugins then move to the platform project as they seem a bit similar to the parent pom?

**Comment by bshannon** [comment]
The real problem here is that Eclipse manages by project but GitHub manages by repo.
Doing a release of a repo requires an Eclipse project release.  It just seems crazy and
confusing to do a GlassFish or Jakarta EE Platform project release in order to release
a bug fix to the copyright plugin.

Other than having them each be their own project, which seems like overkill, I'm not sure
there's a right answer.

**Comment by smillidge** [comment]
Closing as HK2 has been split out the rest can stay
