### ISSUE TITLE
JSP compilation sometimes fails because the Hashset is no guarantees as to the order of the set

### ISSUE THREAD

**Issue by caim2015** [eclipse-ee4j/glassfish#22891]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* GlassFish Version (and build number):V4.1.1 or V5.1
* JDK version:1.8

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"
app:
[toGF.zip](https://github.com/eclipse-ee4j/glassfish/files/4217846/toGF.zip)
test.jsp
<pre>
	<HEAD>
		<META http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<META name="GENERATOR" content="FUJITSU PAGE EDITOR 3.0">
		<%@ page contentType="text/html; charset=UTF-8" %>
		<%@ page import="test.Profile" %>
		<TITLE>MyJsp</TITLE>
	</HEAD>
	<BODY>		
		<%= Profile.KEY1%>
		<br>
		<%= Profile.KEY2%>
	</BODY>
</pre>

WEB-INF\classes\test\Profile.class
<pre>
package test;

public class Profile {	
	public static final String KEY1 = "a";
	public static final String KEY2 = "b";
}
</pre>

WEB-INF\lib\jar.jar\test\Profile.class
<pre>
package test;

public class Profile {	
	public static final String KEY1 = "a";
}
</pre>
In this Profile.class,variable 'KEY2' is not defined.

Steps:
1.deploy the demo.war to [server].
2.http://ip:port/demo/test.jsp access

It works fine.
But,when we rename 'demo.war',for example 'demo2.war',at the same steps deploy and access,
We get the following error.JSP compilation failed.
<pre>
PWC6197: An error occurred at line: 15 in the jsp file: /test.jsp
PWC6199: Generated servlet error:
cannot find symbol
  symbol  : variable KEY2
  location: class test.Profile
</pre>

Why the same app has different results?
We analyze GF code through debug,find a problem.
https://github.com/javaee/glassfish/blob/master/appserver/web/war-util/src/main/java/org/glassfish/web/loader/WebappClassLoader.java
<pre>
/**
     * Returns the search path of URLs for loading classes and resources.
     * This includes the original list of URLs specified to the constructor,
     * along with any URLs subsequently appended by the addURL() method.
     * @return the search path of URLs for loading classes and resources.
     */
    @Override
    public synchronized URL[] getURLs() {

        if (repositoryURLs != null) {
            return repositoryURLs;
        }

        URL[] external = super.getURLs();

        int filesLength = files.length;
        int jarFilesLength = jarRealFiles.length;
        int length = filesLength + jarFilesLength + external.length;
        int i;

        try {

            ArrayList<URL> urls = new ArrayList<URL>();
            for (i = 0; i < length; i++) {
                if (i < filesLength) {
                    urls.add(i, getURL(files[i]));
                } else if (i < filesLength + jarFilesLength) {
                    urls.add(i, getURL(jarRealFiles[i - filesLength]));
                } else {
                    urls.add(i, external[i - filesLength - jarFilesLength]);
                }
            }

            repositoryURLs = removeDuplicate(urls); ***

        } catch (MalformedURLException e) {
            repositoryURLs = new URL[0];
        }

        return repositoryURLs;

    }

    @SuppressWarnings("unchecked")
    private URL[] removeDuplicate(ArrayList<URL> urls) { ***
        HashSet h = new HashSet(urls); 
        urls.clear();
        urls.addAll(h);
        return urls.toArray(new URL[urls.size()]);
    }
</pre>
The Hashset is no guarantees as to the order of the set in the removeDuplicate() above.
Before invoking removeDuplicate(),the order of 'urls' is:
[
.../applications/demo/WEB-INF/classes/
.../applications/demo/WEB-INF/lib/jar.jar
]

but,the case of 'demo2.war',in removeDuplicate()'s return value,the order of 'urls' becomes:
[
.../applications/demo2/WEB-INF/lib/jar.jar
.../applications/demo2/WEB-INF/classes/
]

'WEB-INF/lib/jar.jar' is in front of '/WEB-INF/classes/',
So,when compiling the referenced class file is 'WEB-INF\lib\jar.jar\Profile.class'.
compilation fails as in this Profile.class variable 'KEY2' is not defined.

We think the use of HashSet is not suitable.It's a bug.
LinkedHashSet provides the order of insertion.How about using LinkedHashSet?

**Comment by bshannon** [comment]
Sounds right to me.  Can you submit a Pull Request with the required change?

**Comment by caim2015** [comment]
> 
> 
> Sounds right to me. Can you submit a Pull Request with the required change?

Thank you for your reply.
Now，I have submitted the PR.
https://github.com/caim2015/glassfish/pull/2

**Comment by gerdogdu** [comment]
Is anybody can merge this and close?
