### ISSUE TITLE
Update Maven Bundle plug-in to latest version

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/glassfish#22921]
In order to support JDK 11, the Maven Bundle plug-in should be updated to the latest version. This is not 100% trivial as GlassFish uses a rather old version now, and various things have changed throughout the years.

**Comment by romain-grecourt** [comment]
Upgrading the bundle plugin version has always been hard to do. The subtle changes to the OSGi metadata can result in a lot of issues.

**Comment by hs536** [comment]
> In order to support JDK 11, the Maven Bundle plug-in should be updated to the latest version.

What is the problem if we don't do this?

**Comment by smillidge** [comment]
@arjantijms are you going to attempt this for 6.1 or shall I take off the 6.1 milestone?

**Comment by arjantijms** [comment]
This has been done in one of the commits.
