### ISSUE TITLE
GlassFish 6.0 needs Eclipse Branding

### ISSUE THREAD

**Issue by smillidge** [eclipse-ee4j/glassfish#22930]
GlassFish 6 should be branded Eclipse GlassFish and the references changed in the product details and images on the console.

README.txt needs updating and the default home page also needs branding.

**Comment by smillidge** [comment]
Suggestions from @gerdogdu below

Logo
Current logo:
White plain text with GlassFish(TM) Server Open Source Edition

About Section (Clicking About button):
•  GlassFish Server Open Source Edition 5.1.0 (build XYZ)
Copyright © 2005,2018, Oracle and/or its affiliates. All rights reserved.
This program and the accompanying materials are made available under the terms of the Eclipse Public License v. 2.0, which is available at http://www.eclipse.org/legal/epl-2.0.
This Source Code may also be made available under the following Secondary Licenses when the conditions for such availability setforth in the Eclipse Public License v. 2.0 are satisfied: GNU General Public License, version 2 with the GNU Classpath Exception, which is available at https://www.gnu.org/software/classpath/license.html.
SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

Glassfish - Common Tasks
•	GlassFish News link : https://blogs.oracle.com/theaquarium/
•	Open Source Documentation Set : https://javaee.github.io/glassfish/
•	Quick Start Guide : https://javaee.github.io/glassfish/
•	Administration Guide : https://javaee.github.io/glassfish/
•	Application Development Guide : https://javaee.github.io/glassfish/
•	Application Deployment Guide : https://javaee.github.io/glassfish/

**Comment by gerdogdu** [comment]
Hi
Do you have any suggestion for this? It is great to see Jakarta EE related logo and other stuff in Jakarta EE9 M1 release admin console. Advice?

**Comment by smillidge** [comment]
We have to check with Eclipse about using Jakarta EE logo directly on the product.

**Comment by smillidge** [comment]
I wasn't planning on doing that.

**Comment by gerdogdu** [comment]
But, Glassfish - Common Tasks all points to old Oracle links. At least we can correct javaee.github.io with EE4J links.

**Comment by smillidge** [comment]
Feel free dev freeze is tomorrow

**Comment by gerdogdu** [comment]
I have updated links. Can you please check PR https://github.com/eclipse-ee4j/glassfish/pull/23091
to merge them?
