### ISSUE TITLE
AWS EC2 TCP Cluster with nodes on different hosts creates JSESSIONID on each request

### ISSUE THREAD

**Issue by leonardocelati** [eclipse-ee4j/glassfish#22961]
## Environment Details
* GlassFish Version (and build number): 5.1.0 Full Profile
* JDK version: 1.8
* OS: AWS Linux 2 (deployed on AWS EC2)
* Database: Aurora DB

----------

## Problem Description
The cluster is hosted on AWS and is composed by a DAS and two instances. Each of them on a dedicated EC2 AWS linux 2 instance. 
AWS doesn't fully support multicast, so the cluster is configured with tcp broadcast.
When an JEE applications is deployed on the cluster a JSESSIONID is created on each request when accessing a secured page or a page that needs a session such as JSF with Primefaces with certain scope such as @ViewScope.
The issue is always present, if you leave only one node in the cluster (i.e instance2), everything goes back to normal behavior and the JSESSIONID is maintained between client requests.
The instance stack traces show nothing wrong, on the opposite everything seems to work correctly.

Instance 2 sees the cluster

```
[2020-04-16T09:11:43.201+0000] [glassfish 5.1] [INFO] [view.window.view.change] [ShoalLogger] [tid: _ThreadID=37 _ThreadName=GMS ViewWindowThread Group-my-cluster] [timeMillis: 1587028303201] [levelValue: 800] [[
  GMS1092: GMS View Change Received for group: my-cluster : Members in view for ADD_EVENT(before change analysis) are :
1: MemberId:instance1, MemberType: CORE, Address: 10.0.20.9:9090:230.30.1.1:9090:cluster:instance1
2: MemberId:instance2, MemberType: CORE, Address: 10.0.10.14:9090:230.30.1.1:9090:cluster:instance2
3: MemberId: server, MemberType: SPECTATOR, Address: 10.0.10.4:9090:230.30.1.1:9090:my-cluster:server
]]
```

Instance 1 also

```
[2020-04-16T09:11:43.136+0000] [glassfish 5.1] [INFO] [view.window.view.change] [ShoalLogger] [tid: _ThreadID=45 _ThreadName=GMS ViewWindowThread Group-my-cluster] [timeMillis: 1
587028303136] [levelValue: 800] [[
  GMS1092: GMS View Change Received for group: my-cluster : Members in view for ADD_EVENT(before change analysis) are :
1: MemberId:instance1, MemberType: CORE, Address: 10.0.20.9:9090:230.30.1.1:9090:my-cluster:instance1
2: MemberId:instance2, MemberType: CORE, Address: 10.0.10.14:9090:230.30.1.1:9090:my-cluster:instance2
3: MemberId: server, MemberType: SPECTATOR, Address: 10.0.10.4:9090:230.30.1.1:9090:my-cluster:server
]]

```

The DAS is confirming the cluster is working as expected

```
[2020-04-16T12:52:59.360+0000] [glassfish 5.1] [FINER] [] [ShoalLogger] [tid: _ThreadID=55 _ThreadName=GMS InDoubtPeerDetector Thread for Group-my-cluster] [timeMillis: 1587041579360] [levelValue: 400] [CLASSNAME: com.sun.enterprise.mgmt.HealthMonitor$InDoubtPeerDetector] [METHODNAME: processCacheUpdate] [[
  processCacheUpdate : instance2 's state is aliveandready]]
```
```
[2020-04-16T12:52:59.359+0000] [glassfish 5.1] [FINER] [] [ShoalLogger] [tid: _ThreadID=55 _ThreadName=GMS InDoubtPeerDetector Thread for Group-my-cluster] [timeMillis: 1587041579359] [levelValue: 400] [CLASSNAME: com.sun.enterprise.mgmt.HealthMonitor$InDoubtPeerDetector] [METHODNAME: processCacheUpdate] [[
  processCacheUpdate : instance1 's state is aliveandready]]
```

## Steps to reproduce
Configure a cluster with nodes on different host and specify a DISCOVERY_URI_LIST where uri-list is a list of three IP address, first the DAS and following the two nodes.

asadmin create-cluster --properties GMS_DISCOVERY_URI_LIST=uri-list my-cluster

Apply relevant tags and property to glassfish-web.xml in the web app.

```
<session-config>	
   <session-manager persistence-type="replicated">
     <manager-properties>
         <property name="relaxCacheVersionSemantics" value="true"/>
      </manager-properties>
   </session-manager>	
   <cookie-properties>
      <property name="cookieDomain" value="mydomain.com" />
      <property name="cookiePath" value="/myapp" />
   </cookie-properties>
</session-config>
```

Add <distributable/> in web.xml descriptor and deploy with 

`asadmin deploy --target my-cluster --availabilityenabled true myapp.ear`

## Impact of Issue
If verified it has important impact as the cluster is invalidating the JSESSIONID and log out the user from any protected page.

**Comment by smillidge** [comment]
How are you accessing the clustered nodes? They must be accessed via some load balancer as your browser will associate the JSESSIONID cookie with a host name. So if you access each node directly then a JSESSIONID will be created for each host.

**Comment by leonardocelati** [comment]
The nodes are accessed trough the load balancer.

One further detail, the cluster is hosted on AWS.
Things I have tried. If I leave only one node in the cluster by removing all the other nodes from the target group, then the JSESSIONID is maintained between requests.
If I later rejoin the other nodes to the cluster, then the problem is there again, even if the response comes from the same node.

**Comment by smillidge** [comment]
Closing this as it is a request for configuration advice. Please reopen if you suspect there is a bug in GlassFish.
