### ISSUE TITLE
TypeError: table.getAllSelectedRowsCount is not a function

### ISSUE THREAD

**Issue by tannancun** [eclipse-ee4j/glassfish#22967]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* GlassFish Version (and build number):5.1
* JDK version:Oracle JDK 1.8.0_91
* OS: windows 10
* Database:

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"

[//]: # "Please choose one each Type, Component, and Priority label"

**Comment by smillidge** [comment]
This issue gives no information. Can you expand or it will be closed.

**Comment by leonardocelati** [comment]
I can provide further info, as I am having this issue as well :-)

This is happening all the times when you use the web console in Safari, Chrome or Firefox.
In the instances panel, when you flag the checkbox of an instance you get a JS popup with the same exact message, and the buttons in the page are not enabled, but for sure there are other sections where this is happening when you flag a checkbox.

But let's wait for the reporter...

**Comment by gerdogdu** [comment]
This will be fixed in 5.1.1 release.
