### ISSUE TITLE
Cannot build glassfish 5.1.0

### ISSUE THREAD

**Issue by karlkras** [eclipse-ee4j/glassfish#22962]
## Environment Details
* GlassFish Version (and build number):
5.1.0 
* version information:
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T11:41:47-07:00)
Maven home: C:\apache-maven-3.6.0\bin\..
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_201\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

* Database:
MySql ?

----------

## Problem Description
Following the build instructions after clone: 
`mvn -Pstaging install`

getting test failures shown in the attached log.

[org.jvnet.libpam.UnixUserTest.txt](https://github.com/eclipse-ee4j/glassfish/files/4500854/org.jvnet.libpam.UnixUserTest.txt)

I'm assuming a missing dependency, but the instructions say nothing about needing anything other than the JDK ?

## Impact of Issue
Can't get a clean build for installable artifacts.

**Comment by karlkras** [comment]
and noticed this too on just cloning:
```
Resolving deltas: 100% (25005/25005), done.
error: unable to create file appserver/tests/v2-tests/appserv-tests/devtests/ee/admin/mbeanapi/deployment/com/sun/enterprise/admin/mbeanapi/deployment/samples/SOAPtoJMSMessageSampleClient/simple-client/src/java/samples/jms/soaptojms/ReceiveSOAPMessageWithJMS.java: Filename too long
error: unable to create file appserver/tests/v2-tests/appserv-tests/devtests/ee/admin/mbeanapi/deployment/com/sun/enterprise/admin/mbeanapi/deployment/samples/SOAPtoJMSMessageSampleClient/simple-client/src/java/samples/jms/soaptojms/SOAPMessageWithJMSClient.java: Filename too long
error: unable to create file appserver/tests/v2-tests/appserv-tests/devtests/ee/admin/mbeanapi/deployment/com/sun/enterprise/admin/mbeanapi/deployment/samples/SOAPtoJMSMessageSampleClient/simple-client/src/java/samples/jms/soaptojms/SendSOAPMessageWithJMS.java: Filename too long
error: unable to create file appserver/tests/v2-tests/appserv-tests/devtests/ee/admin/mbeanapi/deployment/com/sun/enterprise/admin/mbeanapi/deployment/samples/SOAPtoJMSMessageSampleClient/simple-client/src/java/samples/jms/soaptojms/ServiceLocatorException.java: Filename too long
Checking out files: 100% (31748/31748), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
```

**Comment by pzygielo** [comment]
> well, the above `Filename too long` errors can be resolved if you check out the project into a root directory. Anything more than a couple directories deep will result in this problem.

But this is MS feature - consult [Naming Files, Paths, and Namespaces](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file), esp. [Enable Long Paths in Windows 10, Version 1607, and Later](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#enable-long-paths-in-windows-10-version-1607-and-later).

**Comment by karlkras** [comment]
> But this is MS feature - consult [Naming Files, Paths, and Namespaces](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file), esp. [Enable Long Paths in Windows 10, Version 1607, and Later](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#enable-long-paths-in-windows-10-version-1607-and-later).

Thanks @pzygielo , great information!

**Comment by arjantijms** [comment]
> I was also able to get a build by ignoring that test

Thanks for the update!

>  the resulting 5.1.0 image is still broken (admin UI) with failing JavaScript and inability to define jdbc resources.

Can you create a new issue for that then? As the build itself is fixed, I'm going to close this one. Thx!
