### ISSUE TITLE
Add back FighterFish

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/glassfish#22994]
FighterFish was removed for GlassFish 6.0.0. Since this is functionality that is still in used, it should be added back when the time and resources are available to do that.

It was removed here: https://github.com/eclipse-ee4j/glassfish/pull/22993 The PR done there should be reverted, and them the work started at https://github.com/eclipse-ee4j/glassfish-fighterfish/pull/44 continued.

Note that to fully finish this work in the most official way, a new OSGi Enterprise API should be released by the OSGi alliance. Their current version references javax.* packages.

**Comment by jGauravGupta** [comment]
Also, the `osgitest/basicosgi` Quicklook test should be enabled back, It is currently failing due to missing FighterFish component. See https://github.com/eclipse-ee4j/glassfish/pull/23071

**Comment by smillidge** [comment]
Also https://github.com/eclipse-ee4j/glassfish/pull/23074 should be undone
