### ISSUE TITLE
Cannot add a Glassfish Connection Pool via web admin page

### ISSUE THREAD

**Issue by izomezzo** [eclipse-ee4j/glassfish#23024]
## Environment Details
* GlassFish Version (and build number): 5.1.0 (build default-private)
* JDK version: 1.8.0_191
* OS: Windows 10
* Database: MySQL

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"
When adding a new property to a Connection Pool an error is returned: 
HTTP Status 500 - Internal Server Error
type Exception report
messageInternal Server Error
descriptionThe server encountered an internal error that prevented it from fulfilling this request.
exception
java.lang.IllegalStateException: getOutputStream() has already been called for this response
note The full stack traces of the exception and its root causes are available in the GlassFish Server Open Source Edition 5.1.0 logs.

## Steps to reproduce
In the Glassfish admin webpage add a Connection Pool with pool name MySQLPool and resource type java.sql.DataSource, Database Driver Vendor as MySQL, click Next. Under Additional Properties
select Add Property.

## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"
I'm unable to add a Connection Pool to the Glassfish server

[//]: # "Please choose one each Type, Component, and Priority label"
Type: N/A Component: Glassfish 5.1.0, Priority: low

**Comment by izomezzo** [comment]
Hi I have managed to get around this by reloading the page after submitting, so it seems the properties are added/removed but requires a refresh to actually see it.

**Comment by gerdogdu** [comment]
This will be fixed in release 5.1.1.

**Comment by ptorresi** [comment]
I use version 6.0.0 and the error still keeps happening. It does not allow adding new properties showing error page HTTP status 500
But if the pool is saved with the default properties when I edit it I can add new properties.
my server is ubuntu 20.04

**Comment by rdsanchezdu** [comment]
> Hi I have managed to get around this by reloading the page after submitting, so it seems the properties are added/removed but requires a refresh to actually see it.
