### ISSUE TITLE
Publish successful builds of master to Eclipse Downloads

### ISSUE THREAD

**Issue by smillidge** [eclipse-ee4j/glassfish#23022]
For other projects it would be good if we publish the results of a successful master build from Jenkins to Eclipse downloads.

See https://www.eclipse.org/lists/jakartaee-platform-dev/msg01801.html for background info.

This should be labelled as a SNAPSHOT release in downloads somehow in the zip filename.

**Comment by jGauravGupta** [comment]
Jenkins Job (https://ci.eclipse.org/glassfish/job/GlassFish-Publish-Build/) is ready to copy the GlassFish artifacts to Eclipse download folder (https://download.eclipse.org/ee4j/glassfish/).

**Comment by smillidge** [comment]
I've added a nightly periodic trigger so we upload a nightly into downloads. Should we create a separate job and add `-nightly` as a suffix?
