### ISSUE TITLE
Docker CI image for JDK 11

### ISSUE THREAD

**Issue by hs536** [eclipse-ee4j/glassfish#23031]
If we merge the following PRs, GlassFish will only run with JDK 11.
https://github.com/eclipse-ee4j/glassfish/pull/23019
So we need a docker image for CI with both JDK 8 and JDK 11 installed so that devtests can run on JDK 11.

**Comment by hs536** [comment]
I can modify the Jenkinsfile, but I don't know how to create a docker image in the Eclipse infra. So I need help from someone who knows what to do.

**Comment by smillidge** [comment]
I think the base image may have a bunch of jdks on it as normally you can select the JDK in the job?

**Comment by hs536** [comment]
I created and push the docker image for CI containing both JDK 8 and JDK 11 in a container(*) as `ee4jglassfish/ci:tini-jdk-8.252-11.0.7`.
 - Build GlassFish -> JDK8
 - Run devtests -> JDK11
*) if we define each container divided into images of each JDK in one Pod, then k8s will always require resources to keep both containers up and running, and k8s will not be able to do enough parallel processing.

The default JDK is 8, and only when running devtests, enable JDK 11 by rewriting JAVA_HOME (and PATH) in Jenkinsfile.
draft changes) https://github.com/eclipse-ee4j/glassfish/pull/23019/commits/48024888f60c857dacede611deec3922661ac9f5

I'll try to work with this image.

**Comment by smillidge** [comment]
@hs536 is this still relevant. If so are you going to change the Jenkins file in master to reference the new image?

**Comment by hs536** [comment]
@smillidge 
The fix proposed in this issue have already been merged into master. but it has become redundant, so I created a PR to fix it.
https://github.com/eclipse-ee4j/glassfish/pull/23384
