### ISSUE TITLE
Fix Admin Console JavaScript Errors

### ISSUE THREAD

**Issue by gerdogdu** [eclipse-ee4j/glassfish#23036]
In 5.1.0-BRANCH, because for updating DOJO, webui.suntheme.* does not work and gives an error webui is not defined in browsers and also having some other javascript problems. This issue tracks these type of errors and probably needs also merge with 6.x branch.

**Comment by gerdogdu** [comment]
Can you please add this to 5.1.1 Milestone?

**Comment by aaabdallah** [comment]
Kindly note that I second gerdogdu's request. There are still many installations that are unable to move to later versions of Glassfish due to migration issues. The UI issue is difficult for many users.
