### ISSUE TITLE
Simple JavaScript Error in webui-jsf-suntheme-4.0.2.16.jar

### ISSUE THREAD

**Issue by gerdogdu** [eclipse-ee4j/glassfish#23038]
There is a simple type error in common.js (instead of using this, it simply use thi) in webui-jsf-suntheme-4.0.2.16.jar. How can we update it? Please track this issue as 5.1.1

**Comment by hs536** [comment]
webui-jsf-suntheme is one of the woodstock modules:
https://github.com/eclipse-ee4j/glassfish-woodstock/tree/master/woodstock-webui-jsf-suntheme

**Comment by gerdogdu** [comment]
We can not use master which depends on jakarta.*. 
What can we do?

**Comment by hs536** [comment]
@smillidge @arjantijms I'd like to create a non-jakarta-ized branch of woodstock for future releases of GF 5.X, is that okay?
@gerdogdu Could you tell me which commit should we create branches from?

**Comment by smillidge** [comment]
I'm fine with that

**Comment by gerdogdu** [comment]
Hi @hs536 
Actually, I did not commit anything to webui-jsf-suntheme. I have just unzip dependency webui-jsf-suntheme-4.0.2.16.jar and update the javascript file common.js and zip again.

Here is the updated method in common.js under javascript/common.js (**thi to this**)

```
setVisibleElement: function(element, visible) {
        if (element == null || visible == null) {
            return false;
        }
        if (visible) {
            this.stripStyleClass(element,
                props.hiddenClassName);
        } else {
            **this**.addStyleClass(element,
                props.hiddenClassName);
        }
    }
```

Where is the repository for 4.0.2.16 to commit this change?
Regards.
Gurkan

**Comment by gerdogdu** [comment]
I looked to the repository https://github.com/eclipse-ee4j/glassfish-woodstock/tree/master/woodstock-webui-jsf-suntheme, there exists two branches master and 5.0.0-M1. But these are different javascript files from 4.0.2.16. (common.js files are not the same and don't see any problem in 5.0.0-M1 common.js).

**Comment by hs536** [comment]
Hi @gerdogdu 
I created 4.1.0 branch from https://github.com/eclipse-ee4j/glassfish-woodstock/commit/60372f220f0685eba8e39f1515d1091ced49ab61 .
You can create a pull request for this branch.
