### ISSUE TITLE
Please upgrade Mojarra to address mojarra/issues#4725 JSF/other Jakarta EE 9 Platform TCK failures 

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/glassfish#23106]
Please upgrade to a newer version of Mojarra that has a fix for [mojarra/issues#4725](https://github.com/eclipse-ee4j/mojarra/issues/4725) to address various ```Unable to parse document 'WEB-INF/faces-config.xml'``` failures in Jakarta EE 9 Platform TCK.  

I see about 39,392 of these failure messages in the TCK test output (the total number of Platform TCK failures is around 4,276, so not 39k failures).  By the way, we are still running with JDK 8.

I am adding this tracking issue as a reminder that the upgrade is needed.

Thanks!

**Comment by arjantijms** [comment]
Assigned myself to remind me this needs doing, but if someone else wants to do it, feel free.

**Comment by smillidge** [comment]
Is there a mojarra release available to upgrade to?

**Comment by gerdogdu** [comment]
I think I have fixed this issue but needs a Mojarra release right?

**Comment by smillidge** [comment]
Yes

**Comment by smillidge** [comment]
@arjantijms any news on a mojarra release?

**Comment by arjantijms** [comment]
@gerdogdu @smillidge thanks for your patience. It's now been staged here: https://jakarta.oss.sonatype.org/content/repositories/staging/org/glassfish/jakarta.faces/3.0.0-RC3/

**Comment by smillidge** [comment]
Fixed by #23119
