### ISSUE TITLE
java.util.ServiceConfigurationError: jakarta.websocket.ContainerProvider: Provider org.glassfish.tyrus.container.grizzly.client.GrizzlyContainerProvider not found

### ISSUE THREAD

**Issue by gurunrao** [eclipse-ee4j/glassfish#23105]
Websocket TCK tests fails with following exception:
java.util.ServiceConfigurationError: jakarta.websocket.ContainerProvider: Provider org.glassfish.tyrus.container.grizzly.client.GrizzlyContainerProvider not found
---------------------------------------
## Environment Details
* GlassFish Version (and build number): 6.0 M1
* JDK version:1.8
* OS:linux
* Database:Derby
------------------------------
Full stack trace:
 Exception: java.util.ServiceConfigurationError: jakarta.websocket.ContainerProvider: Provider org.glassfish.tyrus.container.grizzly.client.GrizzlyContainerProvider not found
[javatest.batch] 	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
[javatest.batch] 	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
[javatest.batch] 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
[javatest.batch] 	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
[javatest.batch] 	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
[javatest.batch] 	at jakarta.websocket.ContainerProvider.getWebSocketContainer(ContainerProvider.java:46)
[javatest.batch] 	at com.sun.ts.tests.websocket.ee.jakarta.websocket.containerprovider.metainf.LibrariedQuestionaire.getContainerProviderName(LibrariedQuestionaire.java:29)
[javatest.batch] 	at com.sun.ts.tests.websocket.ee.jakarta.websocket.containerprovider.metainf.WSCServer.onMessage(WSCServer.java:35)
[javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[javatest.batch] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javatest.batch] 	at java.lang.reflect.Method.invoke(Method.java:498)
[javatest.batch] 	at org.glassfish.tyrus.core.AnnotatedEndpoint.callMethod(AnnotatedEndpoint.java:553)
[javatest.batch] 	at org.glassfish.tyrus.core.AnnotatedEndpoint.access$100(AnnotatedEndpoint.java:66)
[javatest.batch] 	at org.glassfish.tyrus.core.AnnotatedEndpoint$WholeHandler$1.onMessage(AnnotatedEndpoint.java:652)
[javatest.batch] 	at org.glassfish.tyrus.core.TyrusSession.notifyMessageHandlers(TyrusSession.java:559)
[javatest.batch] 	at org.glassfish.tyrus.core.TyrusEndpointWrapper.onMessage(TyrusEndpointWrapper.java:855)
[javatest.batch] 	at org.glassfish.tyrus.core.TyrusWebSocket.onMessage(TyrusWebSocket.java:196)
[javatest.batch] 	at org.glassfish.tyrus.core.frame.TextFrame.respond(TextFrame.java:115)
[javatest.batch] 	at org.glassfish.tyrus.core.ProtocolHandler.process(ProtocolHandler.java:819)
[javatest.batch] 	at org.glassfish.tyrus.core.TyrusWebSocketEngine$TyrusReadHandler.handle(TyrusWebSocketEngine.java:539)
[javatest.batch] 	at org.glassfish.tyrus.servlet.TyrusHttpUpgradeHandler.onDataAvailable(TyrusHttpUpgradeHandler.java:149)
[javatest.batch] 	at org.apache.catalina.connector.InputBuffer$ReadHandlerImpl.processDataAvailable(InputBuffer.java:422)
[javatest.batch] 	at org.apache.catalina.connector.InputBuffer$ReadHandlerImpl.onDataAvailable(InputBuffer.java:387)
[javatest.batch] 	at org.glassfish.grizzly.http.io.InputBuffer.invokeHandler(InputBuffer.java:1019)
[javatest.batch] 	at org.glassfish.grizzly.http.io.InputBuffer.invokeHandlerOnProperThread(InputBuffer.java:1012)
[javatest.batch] 	at org.glassfish.grizzly.http.io.InputBuffer.append(InputBuffer.java:907)
[javatest.batch] 	at org.glassfish.grizzly.http.server.HttpServerFilter.handleRead(HttpServerFilter.java:224)
[javatest.batch] 	at org.glassfish.grizzly.filterchain.ExecutorResolver$9.execute(ExecutorResolver.java:88)
[javatest.batch] 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeFilter(DefaultFilterChain.java:248)
[javatest.batch] 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.executeChainPart(DefaultFilterChain.java:181)
[javatest.batch] 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.execute(DefaultFilterChain.java:121)
[javatest.batch] 	at org.glassfish.grizzly.filterchain.DefaultFilterChain.process(DefaultFilterChain.java:99)
[javatest.batch] 	at org.glassfish.grizzly.ProcessorExecutor.execute(ProcessorExecutor.java:51)
[javatest.batch] 	at org.glassfish.grizzly.nio.transport.TCPNIOTransport.fireIOEvent(TCPNIOTransport.java:510)
[javatest.batch] 	at org.glassfish.grizzly.strategies.AbstractIOStrategy.fireIOEvent(AbstractIOStrategy.java:82)
[javatest.batch] 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.run0(WorkerThreadIOStrategy.java:83)
[javatest.batch] 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy.access$100(WorkerThreadIOStrategy.java:34)
[javatest.batch] 	at org.glassfish.grizzly.strategies.WorkerThreadIOStrategy$WorkerThreadRunnable.run(WorkerThreadIOStrategy.java:101)
[javatest.batch] 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:535)
[javatest.batch] 	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:515)
[javatest.batch] 	at java.lang.Thread.run(Thread.java:748)
[javatest.batch] 06-26-2020 22:23:24:  ERROR: [WebValidatorBase] Unable to find the following search string in the server's response: 'com.sun.ts.tests.websocket.ee.jakarta.websocket.containerprovider.metainf.TCKWebSocketContainer' at index: 0

**Comment by gerdogdu** [comment]
Which TCK test are you getting this exception?

**Comment by gurunrao** [comment]
thanks @gerdogdu for looking into the issue.
We are seeing failures with WebSocket TCK. 
The test name is "getWebSocketContainerOnServerTest_from_standalone"
More details of test run can be found here - https://ci.eclipse.org/jakartaee-tck/job/standalonetck-nightly-build-run-master/65/junit-reports-with-handlebars/test-summary/8989e1e8-361f-40d8-94dc-d93451426fa0.html
