### ISSUE TITLE
Failed when running GF 6.0.0.M1 with JDK 11

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/glassfish#23102]
## Environment Details
* GlassFish Version (and build number):  6.0.0.M1 
* JDK version: 11
* OS: Windows 10 64bit
* Database: No

>java -version
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
----------

## Problem Description
n>asadmin start-domain
Waiting for domain1 to start .Error starting domain domain1.
The server exited prematurely with exit code 1.
Before it died, it produced the following output:

-Djava.endorsed.dirs=D:\appsvr\glassfish6\glassfish/modules/endorsed;D:\appsvr\glassfish6\glassfish/lib/endorsed is not supported. Endorsed standards and standalone APIs
in modular form will be supported via the concept of upgradeable modules.
OpenJDK 64-Bit Client VM warning: Ignoring option MaxPermSize; support was removed in 8.0
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

Command start-domain failed.

**Comment by hs536** [comment]
6.0.0.M1 still work on JDK 8.

**Comment by scottmarlow** [comment]
I believe that the -Djava.endorsed.dirs options must be removed for running on JDK11 (glassfish6\glassfish/lib/endorsed jars could be added to the classpath if they are needed).  

Are there other changes needed for running on JDK11?

**Comment by arjantijms** [comment]
@scottmarlow There are quite some changes needed indeed. Many concern replacing classes that have been removed and opening up modules to allow illegal access (actually, it would be even better to find replacements for illegal access, but for JDK 11 that will suffice).

See here for some idea of what the JDK 11 work entails: https://github.com/eclipse-ee4j/glassfish/pull/23019

**Comment by scottmarlow** [comment]
thanks @arjantijms that gives me a better idea of what the work entails.

**Comment by smillidge** [comment]
Latest nightly builds all run with JDK 11.
