### ISSUE TITLE
Deployment Client is missing in 6.0.0.M1

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/glassfish#23103]
https://mvnrepository.com/artifact/org.glassfish.main.deployment/deployment-client

## Environment Details
* GlassFish Version (and build number):6.0.0.M1
* JDK version: 11
* OS: Windows 10

The reason is deployment-client is not updated for 6.0.0.M1.

**Comment by gerdogdu** [comment]
AFAIK, Glassfish 6 will not support JSR-88 (Deployment) therefore this issue can be mark as invalid or closed.

**Comment by hantsy** [comment]
@gerdogdu Oh, bad news. Is there any replacement of Cargo maven plugin in future ?

**Comment by smillidge** [comment]
JSR-88 is not part of Jakarta EE 9
