### ISSUE TITLE
securityapi tck failures with glassfish 6 M1

### ISSUE THREAD

**Issue by gurunrao** [eclipse-ee4j/glassfish#23112]
All the tests for securityapi tck are failing with  latest run with
glassfish6. secuirtyapi TCK test used to pass with 8.0, post that only
package renaming has been done, without any modification to test logic.
CI run - https://ci.eclipse.org/jakartaee-tck/job/standalonetck-nightly-build-run-master/65/junit-reports-with-handlebars/test-summary/97886d2f-eefd-4686-9e48-0c52f293a156.html
------------------------------------------------------------------------------------------
## Environment Details
* GlassFish Version : 6 M1
* JDK version: 1.8
* OS: Linux
* Database: Derby
--------------------------------------------------------------------------------------------
Most of the errors are as follows:
----------------------------------------------------------------------------------------------------
org.glassfish.deployment.common.DeploymentException: CDI deployment
failure:Exception List with 2 exceptions:
Exception 0 :
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied
dependencies for type SecurityContext with qualifiers @Default
   at injection point [BackedAnnotatedField] @Inject private
com.sun.ts.tests.securityapi.securitycontext.callerdata.Servlet.securityContext
   at
com.sun.ts.tests.securityapi.securitycontext.callerdata.Servlet.securityContext(Servlet.java:0)

     at
org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:378)
     at
org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:290)
     at
org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:143)
     at
org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:164)
     at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:526)
     at
org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:64)
     at
org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:62)
     at
org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
     at
org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at java.lang.Thread.run(Thread.java:748)
Exception 1 :
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied
dependencies for type SecurityContext with qualifiers @Default
   at injection point [BackedAnnotatedField] @Inject private
com.sun.ts.tests.securityapi.securitycontext.callerdata.Servlet2.securityContext
   at
com.sun.ts.tests.securityapi.securitycontext.callerdata.Servlet2.securityContext(Servlet2.java:0)

     at
org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:378)
     at
org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:290)
     at
org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:143)
     at
org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:164)
     at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:526)
     at
org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:64)
     at
org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:62)
     at
org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
     at
org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at java.lang.Thread.run(Thread.java:748)

     at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:212)
     at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:107)
     at
org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:304)
     at
com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:472)
     at
com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:195)
     at
org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:467)
     at
com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:516)
     at
com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:512)
     at java.security.AccessController.doPrivileged(Native Method)
     at javax.security.auth.Subject.doAs(Subject.java:360)
     at
com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:511)
     at
com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:542)
     at
com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:534)
     at java.security.AccessController.doPrivileged(Native Method)
     at javax.security.auth.Subject.doAs(Subject.java:360)
     at
com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:533)
     at
com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1441)
     at
com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:86)
     at
com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1823)
     at
org.glassfish.deployment.autodeploy.AutoOperation.run(AutoOperation.java:140)
     at
org.glassfish.deployment.autodeploy.AutoDeployer.deploy(AutoDeployer.java:573)
     at
org.glassfish.deployment.autodeploy.AutoDeployer.deployAll(AutoDeployer.java:460)
     at
org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:388)
     at
org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:379)
     at
org.glassfish.deployment.autodeploy.AutoDeployService$1.run(AutoDeployService.java:209)
     at java.util.TimerThread.mainLoop(Timer.java:555)
     at java.util.TimerThread.run(Timer.java:505)
Caused by: org.jboss.weld.exceptions.DeploymentException: Exception List
with 2 exceptions:
Exception 0 :
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied
dependencies for type SecurityContext with qualifiers @Default
   at injection point [BackedAnnotatedField] @Inject private
com.sun.ts.tests.securityapi.securitycontext.callerdata.Servlet.securityContext
   at
com.sun.ts.tests.securityapi.securitycontext.callerdata.Servlet.securityContext(Servlet.java:0)

     at
org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:378)
     at
org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:290)
     at
org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:143)
     at
org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:164)
     at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:526)
     at
org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:64)
     at
org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:62)
     at
org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
     at
org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at java.lang.Thread.run(Thread.java:748)
Exception 1 :
org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied
dependencies for type SecurityContext with qualifiers @Default
   at injection point [BackedAnnotatedField] @Inject private
com.sun.ts.tests.securityapi.securitycontext.callerdata.Servlet2.securityContext
   at
com.sun.ts.tests.securityapi.securitycontext.callerdata.Servlet2.securityContext(Servlet2.java:0)

     at
org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:378)
     at
org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:290)
     at
org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:143)
     at
org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:164)
     at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:526)
     at
org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:64)
     at
org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:62)
     at
org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
     at
org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at java.lang.Thread.run(Thread.java:748)

     at
org.jboss.weld.bootstrap.ConcurrentValidator.validateBeans(ConcurrentValidator.java:72)
     at
org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:487)
     at
org.jboss.weld.bootstrap.WeldStartup.validateBeans(WeldStartup.java:496)
     at
org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:93)
     at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:203)
     ... 26 more
     Suppressed: org.jboss.weld.exceptions.DeploymentException:
WELD-001408: Unsatisfied dependencies for type SecurityContext with
qualifiers @Default
   at injection point [BackedAnnotatedField] @Inject private
com.sun.ts.tests.securityapi.securitycontext.callerdata.Servlet.securityContext
   at
com.sun.ts.tests.securityapi.securitycontext.callerdata.Servlet.securityContext(Servlet.java:0)

         at
org.jboss.weld.bootstrap.Validator.validateInjectionPointForDeploymentProblems(Validator.java:378)
         at
org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:290)
         at
org.jboss.weld.bootstrap.Validator.validateGeneralBean(Validator.java:143)
         at
org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:164)
         at
org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:526)
         at
org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:64)
         at
org.jboss.weld.bootstrap.ConcurrentValidator$1.doWork(ConcurrentValidator.java:62)
         at
org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:62)
         at
org.jboss.weld.executor.IterativeWorkerTaskFactory$1.call(IterativeWorkerTaskFactory.java:55)
         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
         at
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
         at
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
         at java.lang.Thread.run(Thread.java:748)
     Suppressed: org.jboss.weld.exceptions.DeploymentException:
WELD-001408: Unsatisfied dependencies for type SecurityContext with
qualifiers @Default
   at injection point [BackedAnnotatedField] @Inject private
com.sun.ts.tests.securityapi.securitycontext.callerdata.Servlet2.securityContext
   at
com.sun.ts.tests.securityapi.securitycontext.callerdata.Servlet2.securityContext(Servlet2.java:0)

**Comment by arjantijms** [comment]
@gurunrao I finally found what went wrong. I'll do a PR to fix it. Thanks for your patience!

**Comment by arjantijms** [comment]
@gurunrao see #23112

**Comment by gurunrao** [comment]
@arjantijms thank you so much.

**Comment by smillidge** [comment]
@gurunrao did #23113 fix the errors. This should be in GlassFish nightly now

**Comment by gurunrao** [comment]
Errors are fixed. closing the issue.
