### ISSUE TITLE
Servlet TCK failures with glassfish 6

### ISSUE THREAD

**Issue by gurunrao** [eclipse-ee4j/glassfish#23114]
Test Name: GetMajorVersionTest
Test Failure details: 
-----------------------------------------------------------------
getMajorVersion() returned 4
Expected ServletContext.getMajorVersion() -> 5 
Test FAILED
-----------------------------------------------------------------

Test Name: test7
Test Failure details: 
--------------------------------------------------------------------------------------------------------
Unexpected Status Code received from server.  Expected '404' received '401'
--------------------------------------------------------------------------------------------------------

Test Name: test7_anno
Test failure details:
--------------------------------------------------------------------------------------------------------
Unexpected Status Code recieved from server.  Expected '404' received '401'
--------------------------------------------------------------------------------------------------------

Test Name: signatureTest
Test failure details:
--------------------------------------------------------------------------------------------------------
Missed Annotations

jakarta.servlet.ServletRequest:         getRealPath(java.lang.String):anno 0 java.lang.Deprecated()
--------------------------------------------------------------------------------------------------------
signatureTest - should pass, if latest servlet-api is included with glassfish 6.

Detailed logs of Servlet TCK failures with glassfish 6 can be found at 
https://ci.eclipse.org/jakartaee-tck/job/standalonetck-nightly-build-run-master/67/junit-reports-with-handlebars/test-summary/b679496e-5ad9-4dfe-a236-9d06c3567129.html

**Comment by smillidge** [comment]
We are using 5.0.0-M1 what else should we be using for the signature test?

**Comment by gurunrao** [comment]
The 5.0.0-M1 doesn't have latest changes for servlet API i.e - https://github.com/eclipse-ee4j/servlet-api/blob/07ff26e91928aa031ba0a8cd512d7267e8c22a85/api/src/main/java/jakarta/servlet/ServletRequest.java#L358

Without the changes mentioned above signature test is failing with Servlet TCK. 

More details/discussion on failure can be found at comment section for commit - https://github.com/eclipse-ee4j/jakartaee-tck/commit/722e04e9b12153ba882ecdf0acf090e0c3c13480

**Comment by smillidge** [comment]
OK we need someone from the servlet team to do a new milestone release.

**Comment by gurunrao** [comment]
@smillidge - will the new milestone from servlet, have fix for all 4 failures mentioned in the bug.

**Comment by smillidge** [comment]
no but it will fix the signature test. I'm not involved on the servlet api. I will get someone to look at the other test failures on the GlassFish side.

**Comment by arjantijms** [comment]
@gurunrao @smillidge with the latest PR (not yet merged into master), GlassFish 6 now fully passes the TCK:

https://ci.eclipse.org/servlet/job/2_servlet-run-tck-against-staged-build/lastSuccessfulBuild/artifact/servlet-tck/bin/summary.txt

**Comment by gurunrao** [comment]
thanks a lot @arjantijms

**Comment by arjantijms** [comment]
You're welcome @gurunrao 

Do you know who's responsible for putting the final Servlet TCK with sha and sig etc in https://download.eclipse.org/jakartaee/servlet/5.0/ ?

Can you do that?

**Comment by gurunrao** [comment]
@arjantijms  - Alwin should be able to provide details on SHA.
