### ISSUE TITLE
Websocket signature Test failing

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/glassfish#23128]
## Environment Details
* GlassFish Version (and build number): 6.0.0 (commit de45126e7085ebc98b8914ab56a7b3dbef0794a2)
* JDK version: 8

----------

## Problem Description
Signature Test Fails due to update in Websocket api jar. The latest https://github.com/eclipse-ee4j/websocket-api/releases/tag/2.0.0-RELEASE need to be used in glassfish.

The problem is  reproducible  when websocket signature test is run against glassfish.

Stacktrace in test :

Missing Methods
---------------

jakarta.websocket.Decoder:              method public void jakarta.websocket.Decoder.destroy()
--- affected jakarta.websocket.Decoder$TextStream,jakarta.websocket.Decoder$Text,jakarta.websocket.Decoder$BinaryStream,jakarta.websocket.Decoder$Binary
jakarta.websocket.Decoder:              method public void jakarta.websocket.Decoder.init(jakarta.websocket.EndpointConfig)
--- affected jakarta.websocket.Decoder$TextStream,jakarta.websocket.Decoder$Text,jakarta.websocket.Decoder$BinaryStream,jakarta.websocket.Decoder$Binary
jakarta.websocket.Encoder:              method public void jakarta.websocket.Encoder.destroy()
--- affected jakarta.websocket.Encoder$TextStream,jakarta.websocket.Encoder$Text,jakarta.websocket.Encoder$BinaryStream,jakarta.websocket.Encoder$Binary
jakarta.websocket.Encoder:              method public void jakarta.websocket.Encoder.init(jakarta.websocket.EndpointConfig)
--- affected jakarta.websocket.Encoder$TextStream,jakarta.websocket.Encoder$Text,jakarta.websocket.Encoder$BinaryStream,jakarta.websocket.Encoder$Binary

**Comment by smillidge** [comment]
Is this released to jakarta.oss?

**Comment by smillidge** [comment]
OK just checked and there is a 2.0.0 on jakarta.oss. I will raise a PR to include it.

**Comment by smillidge** [comment]
@alwin-joseph I've made a PR to update to the latest version of the WebSocket api. If this doesn't fix it then it is an upstream issue with the api project.

**Comment by alwin-joseph** [comment]
> @alwin-joseph I've made a PR to update to the latest version of the WebSocket api. If this doesn't fix it then it is an upstream issue with the api project.

Thanks will wait for PR merge.
