### ISSUE TITLE
Create a weekly Jenkins build and publish to downloads

### ISSUE THREAD

**Issue by smillidge** [eclipse-ee4j/glassfish#23137]
From the platform call this week. 

In the platform committer team, this morning, we decided we would like to produce more stable GlassFish builds which would live for a few weeks (maybe a set that would rotate over the past three or four). Steve intends to have these available for folks to use Mondays. The intent is to provide a stable basis for other component teams to do their work, when it involves something requiring the GlassFish compatible implementation.
As that discussion progressed, we also suggested that it would be good to run the full Platform TCK against this build -- We recognize this is unlikely to be passing the Platform TCK, but we can use these results to track issues and perform work that is split between component APIs, compatible implementations, and the full platform.
As I see it, we will want to 

	generate a completed GlassFish build -- uploaded to a "well known location" -- Steve/GlassFish
	use that build for a Jakarta 9 full Certification (TCK + required external TCKs) run -- Alwin or Scott/TCK
	provide both the build and the Platform TCK kit versions and results for general view and use -- Alwin or Scott/TCK

**Comment by jGauravGupta** [comment]
Jenkins Job (https://ci.eclipse.org/glassfish/view/GlassFish/job/glassfish_weekly_build/) is ready to copy the GlassFish artifacts to the Eclipse download folder (https://download.eclipse.org/ee4j/glassfish/weekly/) and rotational cleanup of artifacts older than 3 weeks.

**Comment by smillidge** [comment]
Thanks @jGauravGupta
