### ISSUE TITLE
Outstanding TCK Test failures in jsp test suite

### ISSUE THREAD

**Issue by smillidge** [eclipse-ee4j/glassfish#23146]
https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-run-900/2/junit-reports-with-handlebars/test-summary/f7b4ded6-5228-4f83-8fa1-c6307d605ce4.html

**Comment by smillidge** [comment]
All issues are related to missing Mail resources which should be fixed by the update in the mail command in the TCK https://github.com/eclipse-ee4j/jakartaee-tck/pull/409

**Comment by smillidge** [comment]
@gurunrao could you rerun the TCK for JSP now you have changed the name of the mail command?

**Comment by gurunrao** [comment]
@smillidge Alwin fixed the issue, will trigger build with jsp, ejb30_bb, appclient testsuite, once ongoing nightly runs are complete at CI.

**Comment by smillidge** [comment]
If the nightly includes the above suites I can take the status from there.

**Comment by gurunrao** [comment]
Not sure if nightly had picked up the fix, hence have triggered a new pipeline here - https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-grao/job/master/23/

**Comment by gurunrao** [comment]
For jsp, applicient testsuite - https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-grao/job/master/23/testReport/
When running ejb30_bb testsuite was run, there was an error in jenkins. Hence started - https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-grao/job/master/24/

**Comment by smillidge** [comment]
OK looks like 100% pass! Thanks for your help. I will close this for now.
