### ISSUE TITLE
FacesServlet is not called for jsf facelet pages if war is deployed as part of ear

### ISSUE THREAD

**Issue by javaone199** [eclipse-ee4j/glassfish#23153]
Glassfish5: JSF FacesServlet is not called.

example.ear
--------------
    example_ejb.jar
    example_web.war

    META-INF/application.xml

META-INF/application.xml
-----------------------------

<application xmlns="http://xmlns.jcp.org/xml/ns/javaee"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/application_8.xsd"
             version="8">
    
    <module>
        <ejb>example_ejb.jar</ejb>
    </module>
    
    <module>
        <web>
            <web-uri>example_web.war</web-uri>
            <context-root>example_web</context-root>
        </web>
    </module>

    <library-directory>lib</library-directory>
</application>

example_web.war
--------------------

WEB-INF/web.xml
home.xhtml

WEB-INF/web.xml
--------------------

<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_4_0.xsd" 
         version="4.0">

    <servlet>
        <display-name>Faces Servlet</display-name>
        <servlet-name>Faces Servlet</servlet-name>
        <servlet-class>javax.faces.webapp.FacesServlet</servlet-class>
        <load-on-startup>1</load-on-startup>
    </servlet>

    <servlet-mapping>
        <servlet-name>Faces Servlet</servlet-name>
        <url-pattern>*.xhtml</url-pattern>
    </servlet-mapping>
    
</web-app>

Deployed example.ear to Glassfish5, successful. But

http://localhost:8080/example_web/home.xhtml

HTTP Status 404 - Not Found

Set breakpoint in FacesServlet.java, the service() method is not called in debug mode.

Glassfish 5.1
Java 8
Windows 10

**Comment by smillidge** [comment]
Can you provide a reproducible test case as a simple GitHub project that we can use to see if there is a GlassFish problem?

**Comment by smillidge** [comment]
Closed due to inactivity. If you provide a link to a test case demonstrating a bug in GlassFish we will reopen
