### ISSUE TITLE
Outstanding failures in connector testsuite with glassfish 6 web profile.

### ISSUE THREAD

**Issue by gurunrao** [eclipse-ee4j/glassfish#23177]
264 connector testsuite tests fail with glassfish 6 web profile. These testcases pass with glassfish 6 full profile.

## Environment Details
* GlassFish Version (and build number):6 nightly build Web profile.
* JDK version:1.8
* OS:Linux
* Database:Derby

Run Log and glassfish logs can be downloaded from here - https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-grao/job/master/3/artifact/connector-results.tar.gz
file  "/root/run_cts.log" inside archive has run details.
directory  "/root/vi/glassfish6/glassfish/domains/domain1/logs/" has glassfish server logs.

Run logs can also be viewed here - https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck-grao/branches/master/runs/3/nodes/40/steps/90/log/?start=0

Exception stack-trace seen with tests failure is as follows:
------------------------------------------------------------------------
org.apache.catalina.LifecycleException: java.lang.IllegalArgumentException: [com.sun.ts.tests.common.connector.whitebox.TSConnectionFactory] is not an allowed property value type
   [runcts] OUT => [javatest.batch] 5060:  	at org.apache.catalina.core.StandardContext.start(StandardContext.java:5537)
   [runcts] OUT => [javatest.batch] 5061:  	at com.sun.enterprise.web.WebModule.start(WebModule.java:516)
   [runcts] OUT => [javatest.batch] 5062:  	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:877)
   [runcts] OUT => [javatest.batch] 5063:  	at org.apache.catalina.core.ContainerBase.access$000(ContainerBase.java:120)
   [runcts] OUT => [javatest.batch] 5064:  	at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:144)
   [runcts] OUT => [javatest.batch] 5065:  	at org.apache.catalina.core.ContainerBase$PrivilegedAddChild.run(ContainerBase.java:134)
   [runcts] OUT => [javatest.batch] 5066:  	at java.security.AccessController.doPrivileged(Native Method)
   [runcts] OUT => [javatest.batch] 5067:  	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:858)
   [runcts] OUT => [javatest.batch] 5068:  	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:644)
   [runcts] OUT => [javatest.batch] 5069:  	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:2020)
   [runcts] OUT => [javatest.batch] 5070:  	at com.sun.enterprise.web.WebContainer.loadWebModule(WebContainer.java:1666)
   [runcts] OUT => [javatest.batch] 5071:  	at com.sun.enterprise.web.WebApplication.start(WebApplication.java:83)
   [runcts] OUT => [javatest.batch] 5072:  	at org.glassfish.internal.data.EngineRef.start(EngineRef.java:98)
   [runcts] OUT => [javatest.batch] 5073:  	at org.glassfish.internal.data.ModuleInfo.start(ModuleInfo.java:267)
   [runcts] OUT => [javatest.batch] 5074:  	at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:328)
   [runcts] OUT => [javatest.batch] 5075:  	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:476)
   [runcts] OUT => [javatest.batch] 5076:  	at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:195)
   [runcts] OUT => [javatest.batch] 5077:  	at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:467)
   [runcts] OUT => [javatest.batch] 5078:  	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:516)
   [runcts] OUT => [javatest.batch] 5079:  	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2$1.run(CommandRunnerImpl.java:512)
   [runcts] OUT => [javatest.batch] 5080:  	at java.security.AccessController.doPrivileged(Native Method)
   [runcts] OUT => [javatest.batch] 5081:  	at javax.security.auth.Subject.doAs(Subject.java:360)
   [runcts] OUT => [javatest.batch] 5082:  	at com.sun.enterprise.v3.admin.CommandRunnerImpl$2.execute(CommandRunnerImpl.java:511)
   [runcts] OUT => [javatest.batch] 5083:  	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:542)
   [runcts] OUT => [javatest.batch] 5084:  	at com.sun.enterprise.v3.admin.CommandRunnerImpl$3.run(CommandRunnerImpl.java:534)
   [runcts] OUT => [javatest.batch] 5085:  	at java.security.AccessController.doPrivileged(Native Method)
   [runcts] OUT => [javatest.batch] 5086:  	at javax.security.auth.Subject.doAs(Subject.java:360)
   [runcts] OUT => [javatest.batch] 5087:  	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:533)
   [runcts] OUT => [javatest.batch] 5088:  	at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1441)
   [runcts] OUT => [javatest.batch] 5089:  	at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1300(CommandRunnerImpl.java:86)
   [runcts] OUT => [javatest.batch] 5090:  	at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1823)
   [runcts] OUT => [javatest.batch] 5091:  	at org.glassfish.deployment.autodeploy.AutoOperation.run(AutoOperation.java:140)
   [runcts] OUT => [javatest.batch] 5092:  	at org.glassfish.deployment.autodeploy.AutoDeployer.deploy(AutoDeployer.java:573)
   [runcts] OUT => [javatest.batch] 5093:  	at org.glassfish.deployment.autodeploy.AutoDeployer.deployAll(AutoDeployer.java:460)
   [runcts] OUT => [javatest.batch] 5094:  	at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:388)
   [runcts] ERR => 
   [runcts] OUT => [javatest.batch] 5095:  	at org.glassfish.deployment.autodeploy.AutoDeployer.run(AutoDeployer.java:379)
------------------------------------------------------------------------

**Comment by smillidge** [comment]
Does web profile have Connectors?

**Comment by gurunrao** [comment]
connectors tests were run with jakarta ee web profile 8 here  - https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-run-web-800/lastCompletedBuild/testReport/
I will check the we profile documentation for more information.

**Comment by gurunrao** [comment]
documentation( https://jakarta.ee/specifications/webprofile/8/webprofile-spec-8.pdf ) doesn't indicate that web-profile supports connector.
