### ISSUE TITLE
TypeError: table.getAllSelectedRowsCount is not a function

### ISSUE THREAD

**Issue by ghost** [eclipse-ee4j/glassfish#23200]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* GlassFish Version: GlassFish Server Open Source Edition 5.0.1 (build 5)
* JDK version: 1.8.0_241
* OS: Windows 10
* Database: Server version: 8.0.19 MySQL Community Server - GPL

----------

## Problem Description
In GlassFish 5.0.1, the error message "TypeError: table.getAllSelectedRowsCount is not a function" appears.

[https://drive.google.com/file/d/1IoqOERCBdmi6MnV1q_-GCwoCFBQtbW_S/view?usp=sharing](https://drive.google.com/file/d/1IoqOERCBdmi6MnV1q_-GCwoCFBQtbW_S/view?usp=sharing)

This error appears if I open the "JDBC Connection Pools" page.

This error appears once. To repeat it, you need to refresh the browser page.

This error did not occur in the previous version of GlassFish 5.0.

This error occurs in all popular web browsers.

Question: what is it and how to fix it?

[https://youtu.be/2FWUAchgoyY](https://youtu.be/2FWUAchgoyY)

**Comment by smillidge** [comment]
Please check on later versions. The earliest release of Eclipse GlassFish is 5.1

**Comment by pablorodrigo** [comment]
I've tested on GlassFish is 5.1 as requested and de error still occur especially when I click in some item of "Additional Properties" list. 

![Screen Shot 2021-03-24 at 10 22 36](https://user-images.githubusercontent.com/6105149/112326492-f3e24580-8c8a-11eb-8fdc-09b0dd667e2f.png)

JS ERROR:

![Screen Shot 2021-03-24 at 10 25 34](https://user-images.githubusercontent.com/6105149/112326922-589da000-8c8b-11eb-9edf-ed7882d35fc6.png)

**Comment by ptorresi** [comment]
I use version 6.0.0 and the error keeps showing when entering the list of connection pools.
my server is ubuntu 20.04

![image](https://user-images.githubusercontent.com/39754128/113877540-2f9f0400-978f-11eb-83eb-9951877da7cb.png)

**Comment by dmatej** [comment]
Already fixed by https://github.com/eclipse-ee4j/glassfish/pull/23675
