### ISSUE TITLE
Update GlassFish Admin Console Help Pages

### ISSUE THREAD

**Issue by gerdogdu** [eclipse-ee4j/glassfish#23239]
We need to update help pages (when click Help in right side) in admin console such as 

- Updating GlassFish Server Open Source Edition 5.1 to Eclipse GlassFish Server Edition 6.0

- Copyright &#169; 2005, 2017 to 2020

These files are located in console-common/src/main/help/en/help

My question : Are these files static files or being generated from some sort of XML files?

Regards.
Gurkan

**Comment by hs536** [comment]
AFAIK, all html files are static.
These html files are located under each directory in `appserver/admingui`.

**Comment by gerdogdu** [comment]
At the end of each page, it says Copyright © 2005, 2020, Oracle and/or its affiliates. All rights reserved. Legal Notices
Do we need to maintain Oracle in UI like this? Or we can change them to Eclipse Foundation?

**Comment by hs536** [comment]
Oracle descriptions should not be changed or deleted from copyright.
IMO, updating the copyright year is not necessary if we don't change the content.

**Comment by gerdogdu** [comment]
I have started to work on this and created a PR as starting point, https://github.com/eclipse-ee4j/glassfish/pull/23251

In the meantime, how these documents, https://eclipse-ee4j.github.io/glassfish/docs/, are generated?

In every page, for example, https://eclipse-ee4j.github.io/glassfish/docs/latest/reference-manual/stop-instance.html#GSRFM00241 , there are \{product---name} variables in the page but these variables are not updated. We need to update them while generating these pages. Any idea?
