### ISSUE TITLE
The resource method is called despite an IllegalArgumentException in ParamConverter::fromString

### ISSUE THREAD

**Issue by mwirth** [eclipse-ee4j/glassfish#23266]
## Environment Details
* GlassFish Version (and build number):
* JDK version: 1.8.0_252
* OS: MacOS

----------

## Problem Description
As per contract a [ParamConverter](https://docs.oracle.com/javaee/7/api/javax/ws/rs/ext/ParamConverter.html#fromString-java.lang.String-) has to throw an IllegalArgumentException if the supplied string cannot be parsed or is null.

If an implementation of ParamConverter throws an IllegalArgumentException in `ParamConverter::fromString` the resource method is called anyway (with the default value) but the process chain should be stopped.

**Comment by smillidge** [comment]
Can you provide more detail on the issue. Like version of Eclipse GlassFish, error messages, how to reproduce the issue etc.

**Comment by mwirth** [comment]
GlassFish Version `2.33`

How to reproduce:
Write a REST Service e.g.:

```java
import java.util.regex.Pattern;
...
@RequestScoped
public class Service{
...
    @Path("pattern/{pattern}")
    @GET
    public String find(@PathParam("pattern") Pattern pattern){
        ...
        return ... 
    }

}
```
and use a `ParamConverterProvider` e.g. this one:
```java
@Provider
public class PatternParamConverterProvider implements ParamConverterProvider {

    @Override
    public <T> ParamConverter<T> getConverter(final Class<T> rawType, final Type genericType, final Annotation[] annotations) {
        if (rawType.isAssignableFrom(Pattern.class))
            return (ParamConverter<T>) new ParamConverter<Pattern>() {

                @Override
                public final Pattern fromString(final String regex) {
                    throw new IllegalArgumentException(...);
                }

                @Override
                public final String toString(final Pattern pattern) {
                    return Optional.ofNullable(pattern).map(Pattern::pattern).orElse(null);
                }
            };
        return null;
    }

```
Do a REST-call to `http://..../pattern/myPattern` which calls the method `find`

--> `fromString` throws an exception, the resrouce method is called anyway.

**Comment by mkarg** [comment]
@smillidge You asked for more details, they had been provided by @mwirth, but then nothing happened and the issue was auto-closed. So is this issue not reproducible or is it fixed?

**Comment by smillidge** [comment]
@mkarg no idea it was 3 years ago and the version number wasn't an Eclipse GlassFish version.

**Comment by mkarg** [comment]
So why not simply running the provided reproducer in latest GlassFish to see the bug in action?

**Comment by smillidge** [comment]
time - if it still an issue for you reopen or create another issue?

**Comment by dmatej** [comment]
> So why not simply running the provided reproducer in latest GlassFish to see the bug in action?

If it is so important for you, you could simply create a PR with the reproducer. I don't even know on which GlassFish version it did not work (2.33 does not exist), but on GlassFish 7.0.16-SNAPSHOT it works as expected.
