### ISSUE TITLE
GlassFish 6.0.0 RC3 start-domain command produces an error

### ISSUE THREAD

**Issue by daliasheasha** [eclipse-ee4j/glassfish#23303]
## Environment Details
* GlassFish Version (and build number): GlassFish 6.0.0 RC3
* JDK version: AdoptOpenJDK 8 and 11
* OS: Windows
* Database: N/A

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
I [downloaded](https://projects.eclipse.org/projects/ee4j.glassfish/downloads) the latest RC version of Glassfish (Eclipse GlassFish 6.0.0 RC3 Full Profile). After extracting the zip, I ran the `asadmin start-domain domain1` command which resulted in the following error:
```
Remote server does not listen for requests on [localhost:4848]. Is the server up?
Unable to get remote commands.
Closest matching local command(s):
    restart-domain
    start-domain

Command start-domain failed.
```
The same exact steps worked on Eclipse GlassFish 6.0.0 RC2 Full Profile. See the image below:
![image](https://user-images.githubusercontent.com/16565819/102406700-987c2980-3fb0-11eb-98f3-cf3b406ac780.png)

The problem always happens. The output is listed below:
```
C:\Users\dalia\Downloads\glassfish-6.0.0-RC3\glassfish6\bin>asadmin start-domain domain1
Remote server does not listen for requests on [localhost:4848]. Is the server up?
Unable to get remote commands.
Closest matching local command(s):
    restart-domain
    start-domain

Command start-domain failed.
```

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
1. Download Eclipse GlassFish 6.0.0 RC3 Full Profile from https://projects.eclipse.org/projects/ee4j.glassfish/downloads
2. Unzip the folder and cd into the bin folder
3. Run `asadmin start-domain domain1`

## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"
I wanted to run my Jakarta EE application on Glassfish but wasn't able to start the server.

**Comment by hantsy** [comment]
@daliasheasha  Same here.

```bash
D:\appsvr\glassfish6\bin>asadmin start-domain domain1
Remote server does not listen for requests on [localhost:4848]. Is the server up?
Unable to get remote commands.
Closest matching local command(s):
    restart-domain
    start-domain

Command start-domain failed.


```

**Comment by hantsy** [comment]
This is a **blocking** issue.

**Comment by hantsy** [comment]
Not sure if it is a Windows specific issue, in my sample project, it had been updated to RC3 for days, but no breaking report from Github Actions.

https://github.com/hantsy/jakartaee9-starter-boilerplate/blob/master/pom.xml#L60

**Comment by hussainnm** [comment]
Yes, it seems to be a Windows specific issue. Even the nightly build is not working. However I am able to launch the same glassfish from Eclipse IDE with Payara Tools and also via WSL.

**Comment by hussainnm** [comment]
I have created an issue in https://github.com/eclipse-ee4j/glassfish-hk2/issues/535 and provided a fix https://github.com/eclipse-ee4j/glassfish-hk2/pull/536

**Comment by arjantijms** [comment]
Thanks a lot @daliasheasha for reporting this and @hussainnm for the fix. Closing this now since GF 6.0.0 is released with the fix.
