### ISSUE TITLE
glassfish-6.0.0 Issue with IntelliJ Idea (Application server libraries not found)

### ISSUE THREAD

**Issue by CodezillaTeam** [eclipse-ee4j/glassfish#23318]
## Environment Details
* GlassFish Version (and build number): 6.0.0
* JDK version: 1.8_131
* OS: windows
* Database: ?

----------

## Problem Description
I downloaded glassfish-6.0.0 and wanted to configure the application server on intellij idea (2019.1.3), but when I specify the glassfish server directory `[<C:/glassfish6> not <C:/glassfish6/glassfish>.]` I get the error that some libraries are missing with the error message `Application server libraries not found`
I tried re-downloading the server and restarting/clearing intelliJ idea multiple times, I always end up with same issue

**Comment by gerdogdu** [comment]
This is not a GlassFish server specific issue. 
Did you ask this question to IntelliJ Team? Are you sure that IntelliJ supports to use GlassFish 6?

**Comment by CodezillaTeam** [comment]
Ok so I double checked intelliJ's configuration and glassfish 6's requirements. Turns out the reason was that I was using JDK 15. And glassfish supports only 1.8. After changing intellij's configuration to use java 8 it worked fine. Thanks for pointing out that intelliJ is the reason.
