### ISSUE TITLE
glassfish6 support primefaces or richfaces or some other faces language other than jsf 3

### ISSUE THREAD

**Issue by giorgioUnimi** [eclipse-ee4j/glassfish#23327]
How to migrate from glassfish 4 to glassfish6

## Environment Details
* GlassFish Version (and build number):6
* JDK version:1.8
* OS:linux ubuntu
* Database:postgresql 9

----------

## Problem Description
I have to migrate a old project made with jsf2 and richfaces 3 from glassfish4 to glassfish6.
From glassfish6 I don't have more javax.faces but jakarta.faces and I don't know how to integrate richfaces.
I'am able with maven to use jsf3 and deploy my simple hello world to glassfish 6 but when I add in my pom
richfaces   and retry to deploy on glassfish 6 I have
java.lang.NoClassDefFoundError: javax/faces/FacesWrapper.
So I have to think that richfaces are not supported in glassfish 6 and If yes primefaces are supported ?

## Steps to reproduce
this is my pom.xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>disaa.unimi.it</groupId>
    <artifactId>hello</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>war</packaging>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <failOnMissingWebXml>false</failOnMissingWebXml>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <jakarta.jakartaee-api.version>9.0.0-RC2</jakarta.jakartaee-api.version>
        <microprofile.version>3.0</microprofile.version>
        <mockito-core.version>3.1.0</mockito-core.version>
        <junit-jupiter.version>5.5.0</junit-jupiter.version>
        <maven.compiler.plugin.version>3.1</maven.compiler.plugin.version>
        <maven.source.plugin.version>2.2.1</maven.source.plugin.version>
        <maven.clean.plugin.version>2.5</maven.clean.plugin.version>
        <maven.war.plugin.version>2.3</maven.war.plugin.version>
        <maven.acr.plugin.version>1.0</maven.acr.plugin.version>
        <maven.ear.plugin.version>2.8</maven.ear.plugin.version>
        <maven.ejb.plugin.version>2.3</maven.ejb.plugin.version>
        <maven.jar.plugin.version>2.4</maven.jar.plugin.version>
        <maven.rar.plugin.version>2.3</maven.rar.plugin.version>
        <maven.license.plugin.version>1.10.b1</maven.license.plugin.version>
        <maven.release.plugin.version>2.5.2</maven.release.plugin.version>
        <maven.exec.plugin.version>1.2.1</maven.exec.plugin.version>
        <org.richfaces.bom.version>4.1.0.Final</org.richfaces.bom.version>
    </properties>
        
        <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.richfaces</groupId>
                <artifactId>richfaces-bom</artifactId>
                <version>${org.richfaces.bom.version}</version>
                <scope>import</scope>
                <type>pom</type>
            </dependency>           
        </dependencies>
    </dependencyManagement>      
        
    <dependencies>
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-api</artifactId>
            <version>9.0.0-RC3</version>
        </dependency>
        <dependency>
            <groupId>jakarta.platform</groupId>
            <artifactId>jakarta.jakartaee-web-api</artifactId>
            <scope>provided</scope>
            <version>9.0.0-RC3</version>
            
        </dependency>  
        <dependency>
            <groupId>org.eclipse.microprofile</groupId>
            <artifactId>microprofile</artifactId>
            <version>${microprofile.version}</version>
            <type>pom</type>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit-jupiter.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>${mockito-core.version}</version>
            <scope>test</scope>
        </dependency>
                <dependency>
            <groupId>org.richfaces.ui</groupId>
            <artifactId>richfaces-components-ui</artifactId>
        </dependency>
        <dependency>
            <groupId>org.richfaces.core</groupId>
            <artifactId>richfaces-core-impl</artifactId>
        </dependency>   
    </dependencies>
    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven.compiler.plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>${maven.source.plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-clean-plugin</artifactId>
                    <version>${maven.clean.plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-war-plugin</artifactId>
                    <version>${maven.war.plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.codehaus.cargo</groupId>
                    <artifactId>cargo-maven2-plugin</artifactId>
                    <version>${cargo.plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
        
        
        <finalName>hello</finalName>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
            </plugin>
        </plugins>
    </build>
</project>

and this is my outputtextbean
@Named
@RequestScoped
public class OutputTextBean {
    
    /**
     * Stores the output text.
     */
    private String outputText = "Hello World";

    /**
     * Get the outputText.
     * 
     * @return the outputText.
     */
    public String getOutputText() {
        return outputText;
    }
    
    /**
     * Set the outputText.
     * 
     * @param outputText the outputText.
     */
    public void setOutputText(String outputText) {
        this.outputText = outputText;
    }
}
## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"

[//]: # "Please choose one each Type, Component, and Priority label"

**Comment by gerdogdu** [comment]
You can not run javax. apps in GF6 directly. You need to convert your project and dependencies from javax. to jaakrta.
Look at [Eclipse transformer project](https://github.com/eclipse/transformer)

**Comment by giorgioUnimi** [comment]
Thank you for your response.So with this transformer I am able to use again richfaces ? I ask you this because richfaces are central in my project and I don’t know what with substitute that is compatible with jakarta ee 9.

 

Giorgio G.  

 

Da: Gurkan Erdogdu <notifications@github.com> 
Inviato: venerdì 29 gennaio 2021 06:27
A: eclipse-ee4j/glassfish <glassfish@noreply.github.com>
Cc: giorgioUnimi <giorgio.galassi@unimi.it>; Author <author@noreply.github.com>
Oggetto: Re: [eclipse-ee4j/glassfish] glassfish6 support primefaces or richfaces or some other faces language other than jsf 3 (#23327)

 

You can not run javax. apps in GF6 directly. You need to convert your project and dependencies from javax. to jaakrta.
Look at Eclipse transformer project <https://github.com/eclipse/transformer>

**Comment by smillidge** [comment]
I would suggest you go to GlassFish 5 if you are not ready for the javax->jakarta namespace change. GlassFIsh 6 won't support deploying applications in the javax namespace.
