### ISSUE TITLE
Fix missing requirement org.objectweb.asm) (version>=8.0.0)(!(version>=9.0.0))

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/glassfish#23354]
When starting up GlassFish, the following error is logged:

```
osgi.wiring.package; (&(osgi.wiring.package=org.glassfish.gmbal)(version>=4.0.0)(!(version>=5.0.0))) [caused by: U

    Unable to resolve org.glassfish.gmbal.gmbal [170](R 170.0): missing requirement 
            [org.glassfish.gmbal.gmbal [170](R 170.0)] osgi.wiring.package; 
                   (&(osgi.wiring.package=org.glassfish.pfl.tf.timer.impl)(version>=4.1.0)(!(version>=5.0.0))) 
                         [caused by: 
                          Unable to resolve org.glassfish.pfl.pfl-tf [16](R 16.0): 
                          missing requirement 
                              [org.glassfish.pfl.pfl-tf [16](R 16.0)] osgi.wiring.package; 
                                  (&(osgi.wiring.package=org.glassfish.pfl.dynamic.codegen.spi)(version>=4.1.0)(!(version>=5.0.0))) 
                                  [caused by: 
                                   Unable to resolve org.glassfish.pfl.pfl-dynamic [8](R 8.0): 
                                   missing requirement [
                                        org.glassfish.pfl.pfl-dynamic [8](R 8.0)] osgi.wiring.package; 
                                            (&(osgi.wiring.package=org.objectweb.asm)(version>=8.0.0)(!(version>=9.0.0)))]]]] 


Unresolved requirements: [[org.glassfish.main.security.services [157](R 157.0)] 
         osgi.wiring.package; (&(osgi.wiring.package=com.sun.enterprise.security.auth.login.common)(version>=6.0.0)(!(version>=7.0.0)))]
```

This is seemingly because `pfl-dynamic` depends on `asm` 8, but GF currently uses a 7 version.

**Comment by arjantijms** [comment]
Bummer, HK2 at the moment needs a version lower than 8:

```
Unable to resolve org.glassfish.hk2.class-model [203](R 203.0): missing requirement [org.glassfish.hk2.class-model [203](R 203.0)] osgi.wiring.package; (&(osgi.wiring.package=org.objectweb.asm)(version>=7.3.0)(!(version>=8.0.0))) Unresolved requirements: [[org.glassfish.hk2.class-model [203](R 203.0)] osgi.wiring.package; (&(osgi.wiring.package=org.objectweb.asm)(version>=7.3.0)(!(version>=8.0.0)))]
```

**Comment by hussainnm** [comment]
I have created a series of pull request that needs to be merged and a new version needs to staged for each of the following projects:

- orb-gmbal-pfl
  - https://github.com/eclipse-ee4j/orb-gmbal-pfl/pull/40
  - https://github.com/eclipse-ee4j/orb-gmbal-pfl/pull/41

orb-gmbal-pfl needs to staged first for 4.1.3

- orb
  - https://github.com/eclipse-ee4j/orb/pull/116
  - https://github.com/eclipse-ee4j/orb/pull/121

orb depends on orb-gmbal-pfl-4.13. orb needs to be staged for 4.2.4

- glassfish-hk2
  - https://github.com/eclipse-ee4j/glassfish-hk2/pull/546
  - https://github.com/eclipse-ee4j/glassfish-hk2/pull/547

hk2 needs to be staged for 3.0.2

- glassfish
  - https://github.com/eclipse-ee4j/glassfish/pull/23360

Once the above projects are staged the above pull request will be ready.

**Comment by hussainnm** [comment]
For orb-gmbal-pfl, 4.1.2 needs to be re-staged.

**Comment by smillidge** [comment]
@hussainnm I have the power to do what's needed. Can you let me know in what order you need things doing?

**Comment by hussainnm** [comment]
1. Merge eclipse-ee4j/orb-gmbal-pfl#41
2. Stage orb-gmbal-pfl 4.1.2
3. Merge eclipse-ee4j/orb#121
4. Stage glassfish-corba 4.2.4
5. Stage glassfish-hk2 3.0.2
6. Merge eclipse-ee4j/glassfish#23360

**Comment by smillidge** [comment]
OK  eclipse-ee4j/orb#121 needs draft removed then I can do.

**Comment by hussainnm** [comment]
> OK [eclipse-ee4j/orb#121](https://github.com/eclipse-ee4j/orb/pull/121) needs draft removed then I can do.

Ready for review.

**Comment by smillidge** [comment]
4.2.4 staged

**Comment by smillidge** [comment]
HK2 3.0.2 staged

**Comment by hussainnm** [comment]
I downloaded glassfish from https://ci.eclipse.org/glassfish/job/glassfish_build-and-test-using-jenkinsfile/job/master/348/ to verify if this issue is resolved. The server fails to start with the below error:
```
Unable to resolve
    org.glassfish.main.security.services [246]
    missing requirement
        &(package = com.sun.enterprise.security.auth.login.common) (version >= 6.0.0) (!(version >= 7.0.0))
        caused by:
            Unable to resolve
                org.glassfish.main.security [247]
                missing requirement
                    &(package = org.glassfish.gmbal) (version >= 4.0.0) (!(version >= 5.0.0))
                    caused by:
                        Unable to resolve
                            org.glassfish.gmbal.gmbal [103]
                            missing requirement
                                &(package = org.glassfish.pfl.tf.timer.impl) (version >= 4.1.0) (!(version >= 5.0.0))
                                caused by:
                                    Unable to resolve
                                        org.glassfish.pfl.pfl-tf [237]
                                        missing requirement
                                            &(package = org.glassfish.pfl.dynamic.codegen.spi) (version >= 4.1.0) (!(version >= 5.0.0))
                                            caused by:
                                                Unable to resolve
                                                    org.glassfish.pfl.pfl-dynamic [235]
                                                    missing requirement
                                                        &(package = org.objectweb.asm) (version >= 7.3.0) (!(version >= 8.0.0)))]]]]
```

The build seems to have a cached copy of pfl-dynamic-4.1.2 and pfl-tf-4.1.2. 

By replacing pfl-dynamic and pfl-tf from staging I am able to start the server. Jenkins needs to do a force update to replace the cached copy of pfl.

**Comment by arjantijms** [comment]
The cached copy is now replaced, and the Jenkins build succeeds. Closing this one. Many thanks to @hussainnm
