### ISSUE TITLE
Deployment fails during CTS runs with "Jar file requires the extension" message

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/glassfish#23374]
The deployment fails during tck runs with below exception : 

   [runcts] OUT => [javatest.batch] 14230:    Exception while loading the app : java.io.IOException: Jar file requires the extension Name=cts, spec version = 1.4 but it is not in the known extensions {}
   [runcts] OUT => [javatest.batch] 14231:  java.io.IOException: Jar file requires the extension Name=cts, spec version = 1.4 but it is not in the known extensions {}
   [runcts] OUT => [javatest.batch] 14232:  	at org.glassfish.appclient.server.core.jws.ExtensionFileManager.getReferencedExtensions(ExtensionFileManager.java:317)

More logs at
- https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck/branches/master/runs/1229/nodes/68/steps/230/log/?start=0
- https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck/branches/master/runs/1229/nodes/67/steps/251/log/?start=0

**Comment by scottmarlow** [comment]
@smillidge any idea who can help with this failure?  

[deployfail.txt](https://github.com/eclipse-ee4j/glassfish/files/6005948/deployfail.txt) contains the deployment failure that we are seeing mentioned above.

**Comment by smillidge** [comment]
Looks like a Java WebStart Exception. I can take a look at over the next day or so. Does any of the TCK use Java Web Start?

**Comment by smillidge** [comment]
Looks like I need to backport some work done in Payara a few years back.
