### ISSUE TITLE
ClassNotFoundException: org.glassfish.appclient.client.acc.agent.ACCAgentClassLoader

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/glassfish#23396]
## Environment Details
* GlassFish Version (6.1): 
* git log '--max-count=64'
commit f24428081141815cf46258aec5020d63b90658aa
* JDK version: JDK11

----------

## Problem Description

Below exception while running the platform TCK tests in JDK11: 
platform TCK : https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/jakarta-jakartaeetck-9.1.0.zip 

   [runcts] OUT => [javatest.batch] Error occurred during initialization of VM
   [runcts] OUT => [javatest.batch] java.lang.Error: org.glassfish.appclient.client.acc.agent.ACCAgentClassLoader
   [runcts] OUT => [javatest.batch] 	at java.lang.ClassLoader.initSystemClassLoader(java.base@11.0.7/ClassLoader.java:1989)
   [runcts] OUT => [javatest.batch] 	at java.lang.System.initPhase3(java.base@11.0.7/System.java:2070)
   [runcts] OUT => [javatest.batch] Caused by: java.lang.ClassNotFoundException: org.glassfish.appclient.client.acc.agent.ACCAgentClassLoader
   [runcts] OUT => [javatest.batch] 	at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@11.0.7/BuiltinClassLoader.java:581)
   [runcts] OUT => [javatest.batch] 	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@11.0.7/ClassLoaders.java:178)
   [runcts] OUT => [javatest.batch] 	at java.lang.ClassLoader.loadClass(java.base@11.0.7/ClassLoader.java:521)
   [runcts] OUT => [javatest.batch] 	at java.lang.Class.forName0(java.base@11.0.7/Native Method)
   [runcts] OUT => [javatest.batch] 	at java.lang.Class.forName(java.base@11.0.7/Class.java:398)
   [runcts] OUT => [javatest.batch] 	at java.lang.ClassLoader.initSystemClassLoader(java.base@11.0.7/ClassLoader.java:1975)
   [runcts] OUT => [javatest.batch] 	at java.lang.System.initPhase3(java.base@11.0.7/System.java:2070)

tck run logs : 
samples : https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck/branches/master/runs/1248/nodes/151/steps/732/log/?start=0 
appclient : https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck/branches/master/runs/1248/nodes/98/steps/840/log/?start=0

(same issue is discussed in email alias , sub : "Any idea why on Java 11 the GlassFish Client Container might be failing to see the Client Container classloader? )

**Comment by arjantijms** [comment]
@alwin-joseph The dev-tests in GF also test the ACC, and there is does work. The command it generates there is (formatted):

```
/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home//bin/java 
    -Dcom.sun.aas.installRoot=/workspace/glassfish/glassfish6/glassfish/bin/
    -Djava.security.policy=/workspace/glassfish/glassfish6/glassfish/lib/appclient/client.policy
    -Djava.security.auth.login.config=/workspace/glassfish/glassfish6/glassfish/lib/appclient/appclientlogin.conf
    -Djava.system.class.loader=org.glassfish.appclient.client.acc.agent.ACCAgentClassLoader 

    -javaagent:"/workspace/glassfish/glassfish6/glassfish/lib/gf-client.jar"=argsfile="/var/folders/47/ntsw6chs7jg874_8nk_w37_00000gn/T/acc13024400471617066333.dat"  

    -classpath /workspace/glassfish/glassfish6/glassfish/lib/gf-client.jar:/workspace/glassfish/appserver/tests/appserv-tests/build/module/archive/simple-ejb-implicit-cdiAppClient.jar  

    org.glassfish.appclient.client.AppClientGroupFacade 
```

The TCK uses this command:

```
/opt/jdk-11.0.7/bin/java 
    -Dcom.sun.aas.installRoot=/root/vi/glassfish6/glassfish
    -Djava.security.policy=/root/vi/glassfish6/glassfish/lib/appclient/client.policy 
    -Djava.security.auth.login.config=/root/vi/glassfish6/glassfish/lib/appclient/appclientlogin.conf 
    -Djava.system.class.loader=org.glassfish.appclient.client.acc.agent.ACCAgentClassLoader
   
   
    -Dcts.tmp=/root/jakartaeetck/bin/xml/../../tmp 
    -Djava.protocol.handler.pkgs=javax.net.ssl 
    -Dcom.sun.enterprise.home=/root/vi/glassfish6/glassfish 
    -Djavax.net.ssl.keyStore=/root/jakartaeetck/bin/xml/../../bin/certificates/clientcert.jks 
    -Djavax.net.ssl.keyStorePassword=changeit 

    -Dcom.sun.aas.imqLib=/root/vi/glassfish6/glassfish/../mq/lib 
    -Djavax.net.ssl.trustStore=/root/vi/glassfish6/glassfish/domains/domain1/config/cacerts.jks 
    -Djavax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl 
    -Djavax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl 
    -Djavax.xml.transform.TransformerFactory=com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl 
    -Dorg.xml.sax.driver=com.sun.org.apache.xerces.internal.parsers.SAXParser 
    -Dorg.xml.sax.parser=org.xml.sax.helpers.XMLReaderAdapter 
    -Doracle.jdbc.J2EE13Compliant=true 
    -Doracle.jdbc.mapDateToTimestamp 
    -Djava.security.manager 
    -Dstartup.login=false 
    -Dauth.gui=false 
    -Dlog.file.location=/root/vi/glassfish6/glassfish/domains/domain1/logs 
    -Dri.log.file.location=/root/ri/glassfish6/glassfish/domains/domain1/logs 
    -DwebServerHost.2=localhost  
    -DwebServerPort.2=8002 
    -Dprovider.configuration.file=/root/vi/glassfish6/glassfish/domains/domain1/config/ProviderConfiguration.xml 
    -Djava.security.properties=/root/vi/glassfish6/glassfish/domains/domain1/config/ts.java.security 
    -Dcom.sun.aas.configRoot=/root/vi/glassfish6/glassfish/config 
    -Ddeliverable.class=com.sun.ts.lib.deliverable.cts.CTSDeliverable 
    
    -javaagent:/root/vi/glassfish6/glassfish/lib/gf-client.jar=arg=-configxml,arg=/root/jakartaeetck/tmp/appclient/s1as.sun-acc.xml,client=jar=/root/jakartaeetck/dist/com/sun/ts/tests/ejb30/assembly/librarydirectory/custom/ts_dep/ejb3_assembly_librarydirectory_customClient.jar,arg=-name,arg=ejb3_assembly_librarydirectory_custom_client 
    
     -jar /root/jakartaeetck/dist/com/sun/ts/tests/ejb30/assembly/librarydirectory/custom/ts_dep/ejb3_assembly_librarydirectory_customClient.jar 
     -p /root/jakartaeetck/tmp/tstest.jte 
     -t libDirNotUsed
```

**Comment by arjantijms** [comment]
The dev test version uses a file with the agent options. Putting those direction on the command line:

```
"/Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home//bin/java" \
     -Dcom.sun.aas.installRoot="/workspace/glassfish/glassfish6/glassfish/bin/.." \
     -Djava.security.policy="/workspace/glassfish/glassfish6/glassfish/bin/../lib/appclient/client.policy" \
     -Djava.system.class.loader=org.glassfish.appclient.client.acc.agent.ACCAgentClassLoader \
     -Djava.security.auth.login.config="/workspace/glassfish/glassfish6/glassfish/bin/../lib/appclient/appclientlogin.conf" \
      \
     -javaagent:"/workspace/glassfish/glassfish6/glassfish/bin/../lib/gf-client.jar"=arg=-configxml,arg="/workspace/glassfish/glassfish6/glassfish/bin/../domains/domain1/config/glassfish-acc.xml",client=jar="/workspace/glassfish/appserver/tests/appserv-tests/build/module/archive/simple-ejb-implicit-cdiAppClient.jar",arg=-name,arg="simple-ejb-implicit-cdiClient",arg=-textauth,arg=-user,arg="jee",arg=-password,arg="j2ee",arg=-xml,arg="/workspace/glassfish/glassfish6/glassfish/domains/domain1/config/glassfish-acc.xml" \
           \
     -classpath /workspace/glassfish/glassfish6/glassfish/bin/../lib/gf-client.jar:/workspace/glassfish/appserver/tests/appserv-tests/build/module/archive/simple-ejb-implicit-cdiAppClient.jar \
           \
     org.glassfish.appclient.client.AppClientGroupFacade 
```

**Comment by arjantijms** [comment]
@alwin-joseph I think the fix is that for the TCK string, `-classpath` should be added and `-jar` removed. `-classpath` should contain both the jar entry that's now in `-jar` as well as the full path to `gf-client.jar`. (`/root/vi/glassfish6/glassfish/lib/gf-client.jar` in this example).

**Comment by scottmarlow** [comment]
We can try any change.  Perhaps we could start with just adding the `-classpath`? 

I looked on https://docs.oracle.com/en/java/javase/11/docs/api/java.instrument/java/lang/instrument/package-summary.html but do not see classpath mentioned but do see `Boot-Class-Path` which I think is supposed to be add to the gf-client.jar but I'm not a javaagent expert, so cannot say for sure.

**Comment by scottmarlow** [comment]
In case it helps, the [current gf-client.jar MANIFEST.MF](https://github.com/eclipse-ee4j/glassfish/files/6062922/MANIFEST.MF.txt) seems to have `Class-Path` but not `Boot-Class-Path`

**Comment by alwin-joseph** [comment]
> @alwin-joseph I think the fix is that for the TCK string, `-classpath` should be added and `-jar` removed. `-classpath` should contain both the jar entry that's now in `-jar` as well as the full path to `gf-client.jar`. (`/root/vi/glassfish6/glassfish/lib/gf-client.jar` in this example).

Thanks Arjan & Scott. I am looking for an easy way to try this in the tck code. Will let you know when I am able to run a sample CI job with this.

**Comment by arjantijms** [comment]
Adding the correct location of `gf-client.jar` to the MANIFEST of the jar that's being executed (the one after -jar) would be an alternative option, but this is often more difficult to accomplish and makes the jar more dependent and less easier to test standalone.

**Comment by alwin-joseph** [comment]
> > @alwin-joseph I think the fix is that for the TCK string, `-classpath` should be added and `-jar` removed. `-classpath` should contain both the jar entry that's now in `-jar` as well as the full path to `gf-client.jar`. (`/root/vi/glassfish6/glassfish/lib/gf-client.jar` in this example).
> 
> Thanks Arjan & Scott. I am looking for an easy way to try this in the tck code. Will let you know when I am able to run a sample CI job with this.

I tried the same and ran samples tests ,
job url : https://ci.eclipse.org/jakartaee-tck/blue/organizations/jenkins/jakartaee-tck-alw/detail/gfclientjar_issue/2/
complete logs at https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck-alw/branches/gfclientjar_issue/runs/2/nodes/36/steps/51/log/?start=0 

New command is now : 
   [runcts] OUT => [javatest.batch] command: com.sun.ts.lib.harness.ExecTSTestCmd DISPLAY=:0.0 HOME=? LD_LIBRARY_PATH=/root/vi/glassfish6/glassfish/lib TMP= windir= SYSTEMROOT= PATH=/root/vi/glassfish6/glassfish/nativelib APPCPATH=/root/jakartaeetck/bin/xml/../../lib/tsharness.jar:/root/jakartaeetck/bin/xml/../../lib/cts.jar:/root/jakartaeetck/bin/xml/../../lib/glassfishporting.jar:/root/vi/glassfish6/glassfish/lib/jpa_alternate_provider.jar:/root/jakartaeetck/bin/xml/../../lib/tssv.jar:/root/vi/glassfish6/glassfish/modules/weld-osgi-bundle.jar:/root/vi/glassfish6/glassfish/modules/jakarta.enterprise.cdi-api.jar TZ=US/Eastern /opt/jdk-11.0.7/bin/java -Djava.system.class.loader=org.glassfish.appclient.client.acc.agent.ACCAgentClassLoader -Djava.security.policy=/root/vi/glassfish6/glassfish/lib/appclient/client.policy -Dcts.tmp=/root/jakartaeetck/bin/xml/../../tmp -Djava.security.auth.login.config=/root/vi/glassfish6/glassfish/lib/appclient/appclientlogin.conf -Djava.protocol.handler.pkgs=javax.net.ssl -Dcom.sun.enterprise.home=/root/vi/glassfish6/glassfish -Djavax.net.ssl.keyStore=/root/jakartaeetck/bin/xml/../../bin/certificates/clientcert.jks -Djavax.net.ssl.keyStorePassword=changeit -Dcom.sun.aas.installRoot=/root/vi/glassfish6/glassfish -Dcom.sun.aas.imqLib=/root/vi/glassfish6/glassfish/../mq/lib -Djavax.net.ssl.trustStore=/root/vi/glassfish6/glassfish/domains/domain1/config/cacerts.jks -Djavax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl -Djavax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl -Djavax.xml.transform.TransformerFactory=com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl -Dorg.xml.sax.driver=com.sun.org.apache.xerces.internal.parsers.SAXParser -Dorg.xml.sax.parser=org.xml.sax.helpers.XMLReaderAdapter -Doracle.jdbc.J2EE13Compliant=true -Doracle.jdbc.mapDateToTimestamp -Djava.security.manager -Dstartup.login=false -Dauth.gui=false -Dlog.file.location=/root/vi/glassfish6/glassfish/domains/domain1/logs -Dri.log.file.location=/root/ri/glassfish6/glassfish/domains/domain1/logs -DwebServerHost.2=localhost -DwebServerPort.2=8002 -Dprovider.configuration.file=/root/vi/glassfish6/glassfish/domains/domain1/config/ProviderConfiguration.xml -Djava.security.properties=/root/vi/glassfish6/glassfish/domains/domain1/config/ts.java.security -Dcom.sun.aas.configRoot=/root/vi/glassfish6/glassfish/config -Ddeliverable.class=com.sun.ts.lib.deliverable.cts.CTSDeliverable -javaagent:/root/vi/glassfish6/glassfish/lib/gf-client.jar=arg=-configxml,arg=/root/jakartaeetck/bin/xml/../../tmp/appclient/s1as.sun-acc.xml,client=jar=/root/jakartaeetck/bin/xml/../../dist/com/sun/ts/tests/samples/ejb/ee/twobean/ts_dep/ejb_sam_twobeanClient.jar,arg=-name,arg=ejb_sam_twobean_client -classpath /root/vi/glassfish6/glassfish/lib/gf-client.jar:/root/jakartaeetck/bin/xml/../../dist/com/sun/ts/tests/samples/ejb/ee/twobean/ts_dep/ejb_sam_twobeanClient.jar::: -p /root/jakartaeetck/bin/xml/../../tmp/tstest.jte -t twobeanTest2

For some reason I get : 
   [runcts] OUT => [javatest.batch] Unrecognized option: -Xt
   [runcts] OUT => [javatest.batch] Error: Could not create the Java Virtual Machine.
   [runcts] OUT => [javatest.batch] Error: A fatal exception has occurred. Program will exit.

Any idea why this error ?

**Comment by scottmarlow** [comment]
Do we know which software/class was handling the previous used `-jar` argument and which software/class is handling the now used `-classpath` argument?  Perhaps it is gf-client.jar handling these options?

Perhaps the handling for what `-jar` expected versus what `-classpath` expects.

**Comment by scottmarlow** [comment]
Just to show that this is still failing in [today's Full Platform run](https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1264/testReport/com.sun.ts.tests.ejb30.assembly.appres.appclientejb/Client/jakartaeetck_run___ejb30_assembly___clientPostConstruct/) with JDK11 + latest GlassFish master changes:
```
command: com.sun.ts.lib.harness.ExecTSTestCmd DISPLAY=:0.0 HOME=? LD_LIBRARY_PATH=/root/vi/glassfish6/glassfish/lib TMP= windir= SYSTEMROOT= PATH=/root/vi/glassfish6/glassfish/nativelib APPCPATH=/root/jakartaeetck/bin/xml/../../lib/tsharness.jar:/root/jakartaeetck/bin/xml/../../lib/cts.jar:/root/jakartaeetck/bin/xml/../../lib/glassfishporting.jar:/root/vi/glassfish6/glassfish/lib/jpa_alternate_provider.jar:/root/jakartaeetck/bin/xml/../../lib/tssv.jar:/root/vi/glassfish6/glassfish/modules/weld-osgi-bundle.jar:/root/vi/glassfish6/glassfish/modules/jakarta.enterprise.cdi-api.jar TZ=US/Eastern /opt/jdk-11.0.7/bin/java -Djava.system.class.loader=org.glassfish.appclient.client.acc.agent.ACCAgentClassLoader -Djava.security.policy=/root/vi/glassfish6/glassfish/lib/appclient/client.policy -Dcts.tmp=/root/jakartaeetck/bin/xml/../../tmp -Djava.security.auth.login.config=/root/vi/glassfish6/glassfish/lib/appclient/appclientlogin.conf -Djava.protocol.handler.pkgs=javax.net.ssl -Dcom.sun.enterprise.home=/root/vi/glassfish6/glassfish -Djavax.net.ssl.keyStore=/root/jakartaeetck/bin/xml/../../bin/certificates/clientcert.jks -Djavax.net.ssl.keyStorePassword=changeit -Dcom.sun.aas.installRoot=/root/vi/glassfish6/glassfish -Dcom.sun.aas.imqLib=/root/vi/glassfish6/glassfish/../mq/lib -Djavax.net.ssl.trustStore=/root/vi/glassfish6/glassfish/domains/domain1/config/cacerts.jks -Djavax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl -Djavax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl -Djavax.xml.transform.TransformerFactory=com.sun.org.apache.xalan.internal.xsltc.trax.TransformerFactoryImpl -Dorg.xml.sax.driver=com.sun.org.apache.xerces.internal.parsers.SAXParser -Dorg.xml.sax.parser=org.xml.sax.helpers.XMLReaderAdapter -Doracle.jdbc.J2EE13Compliant=true -Doracle.jdbc.mapDateToTimestamp -Djava.security.manager -Dstartup.login=false -Dauth.gui=false -Dlog.file.location=/root/vi/glassfish6/glassfish/domains/domain1/logs -Dri.log.file.location=/root/ri/glassfish6/glassfish/domains/domain1/logs -DwebServerHost.2=localhost -DwebServerPort.2=8002 -Dprovider.configuration.file=/root/vi/glassfish6/glassfish/domains/domain1/config/ProviderConfiguration.xml -Djava.security.properties=/root/vi/glassfish6/glassfish/domains/domain1/config/ts.java.security -Dcom.sun.aas.configRoot=/root/vi/glassfish6/glassfish/config -Ddeliverable.class=com.sun.ts.lib.deliverable.cts.CTSDeliverable -javaagent:/root/vi/glassfish6/glassfish/lib/gf-client.jar=arg=-configxml,arg=/root/jakartaeetck/bin/xml/../../tmp/appclient/s1as.sun-acc.xml,client=jar=/root/jakartaeetck/bin/xml/../../dist/com/sun/ts/tests/ejb30/assembly/appres/appclientejb/ts_dep/ejb3_assembly_appres_appclientejbClient.jar,arg=-name,arg=ejb3_assembly_appres_appclientejb_client -jar /root/jakartaeetck/bin/xml/../../dist/com/sun/ts/tests/ejb30/assembly/appres/appclientejb/ts_dep/ejb3_assembly_appres_appclientejbClient.jar -p /root/jakartaeetck/bin/xml/../../tmp/tstest.jte -t clientPostConstruct
----------log:(13/936)----------
Error occurred during initialization of VM
java.lang.Error: org.glassfish.appclient.client.acc.agent.ACCAgentClassLoader
	at java.lang.ClassLoader.initSystemClassLoader(java.base@11.0.7/ClassLoader.java:1989)
	at java.lang.System.initPhase3(java.base@11.0.7/System.java:2070)
Caused by: java.lang.ClassNotFoundException: org.glassfish.appclient.client.acc.agent.ACCAgentClassLoader
	at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@11.0.7/BuiltinClassLoader.java:581)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@11.0.7/ClassLoaders.java:178)
	at java.lang.ClassLoader.loadClass(java.base@11.0.7/ClassLoader.java:521)
	at java.lang.Class.forName0(java.base@11.0.7/Native Method)
	at java.lang.Class.forName(java.base@11.0.7/Class.java:398)
	at java.lang.ClassLoader.initSystemClassLoader(java.base@11.0.7/ClassLoader.java:1975)
	at java.lang.System.initPhase3(java.base@11.0.7/System.java:2070)

result: Failed. unexpected exit code: exit code 1


test result: Failed. unexpected exit code: exit code 1
```
More details:
[TCK job link](https://ci.eclipse.org/jakartaee-tck/job/9.1/job/eftl-jakartaeetck-run-910/21/)
[GlassFish build](https://ci.eclipse.org/jakartaee-tck/job/build-glassfish/lastSuccessfulBuild/artifact/appserver/distributions/glassfish/target/glassfish.zip) which was built from commits:
```
#109 (Mar 4, 2021, 1:05:57 PM)

    Add an entry to enable TLS1.3 for HTTPS — sawamura.hiroki / githubweb

#108 (Mar 4, 2021, 1:47:05 AM)

    Small cleanup of ACC code for easier comprehension. — arjan.tijms / githubweb
    Update Jackson to 2.12.1 — arjan.tijms / githubweb
    Make test more robust — arjan.tijms / githubweb
    Integrate xml binding API 3.0.1, impl 3.0.1-b01 — Lukas Jungmann / githubweb
```

**Comment by scottmarlow** [comment]
(Work in progress) Instructions to reproduce:
```
#!/bin/bash -x

# podman run -it centos /bin/bash
# yum install -y zip java-11-openjdk-devel wget vim git unzip

export JDK_HOME=$JAVA_HOME
export JDK=JDK11
export PATH=$JDK_HOME/bin:$PATH

mkdir -p /tmp/ee9
cd /tmp/ee9

export WORKSPACE=$PWD

#ensure ant is setup
[ -z "$ANT_HOME" ] && wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.10.6-bin.zip && unzip -o apache-ant-1.10.6-bin.zip &&  rm -f apache-ant-1.10.6-bin.zip && export ANT_HOME=$PWD/apache-ant-1.10.6 && export PATH=$ANT_HOME/bin

#verify that jdk11 is configured
echo "Please ensure that JDK11 is in use"

export GF_BUNDLE_URL=https://download.eclipse.org/ee4j/glassfish/glassfish-6.1.0-SNAPSHOT-nightly.zip

#[ ! -d "glassfish6" ] && wget $GF_BUNDLE_URL &&  unzip glassfish-6.1.0-SNAPSHOT-nightly.zip
#cd glassfish6/glassfish
#export JAVAEE_HOME_RI=$PWD
#cd ../javadb
#export DERBY_HOME=$PWD

[ ! -d "jakartaeetck" ] && wget https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/jakarta-jakartaeetck-9.1.0.zip && unzip jakarta-jakartaeetck-9.1.0.zip && wget https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/jakarta-jakartaeetckinfo.txt
chmod +x jakartaeetck/docker/run_jakartaeetck.sh

echo "copy the jdk11 ts.jte.jdk11 over the ts.jte"
cp jakartaeetck/bin/ts.jte.jdk11 jakartaeetck/bin/ts.jte

bash -x ./jakartaeetck/docker/run_jakartaeetck.sh ejb30/assembly/appres/appclientejb 2>&1 | tee tck.log
```

**Comment by smillidge** [comment]
Tried to follow the instructions but the change to AutoDeployment.java didn't seem to take.

Anyway I think the line should change to;
```java
executeArgs = sApp + ",arg=-name,arg=" + sClientname + " --classpath "+ propMgr.getProperty("javaee.home", "/") + "/lib/gf-client.jar" + ":" + sApp + " org.glassfish.appclient.client.AppClientGroupFacade " ; // +
```

I think change Alwin did when adding classpath didn't add to the command line the class to execute `org.glassfish.appclient.client.AppClientGroupFacade`

**Comment by scottmarlow** [comment]
Created https://github.com/eclipse-ee4j/jakartaee-tck/pull/644 with a copy/paste of ^ change.

**Comment by smillidge** [comment]
Worked out why my changes weren't being applied. The change worked and the tests passed

**Comment by scottmarlow** [comment]
Thanks, I'll build this change now via https://ci.eclipse.org/jakartaee-tck/job/9.1/job/eftl-jakartaeetck-build-910 + start a new Full Platform TCK run via https://ci.eclipse.org/jakartaee-tck/job/9.1/job/eftl-jakartaeetck-run-910 on JDK11.

**Comment by scottmarlow** [comment]
I can confirm that this issue can be closed now.  Thanks!

**Comment by scottmarlow** [comment]
For future reference, I copied the above instructions for reproducing the test failure to https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Run-a-Platform-TCK-test-with-GlassFish-6.1
