### ISSUE TITLE
Improve build.id information

### ISSUE THREAD

**Issue by hussainnm** [eclipse-ee4j/glassfish#23401]
Currently the build produced from Jenkins has the build.id as `?-private` which is written into `glassfish-version.properties`. Can we add proper information like commit-id, timestamp, buildnumber, branchname.

The `nuclues/parent/pom.xml` has the `build.id` property which can be overridden via the command line. This `-Dbuild.id=` argument can be added to `MVN_EXTRA` in the Jenkinsfile or directly in the `gfbuild.sh`. This can also be configured as a Jenkins Parameter with some default value and overridden for milestone builds (alpha,beta,m,rc,final).

Thoughts and suggestions?

**Comment by arjantijms** [comment]
I had the exact same issue. What about adopting this one?

https://github.com/git-commit-id/git-commit-id-maven-plugin

**Comment by hussainnm** [comment]
I was thinking of a simpler solution using `git describe`

```
$ git describe
6.0.0-201-g8a330360a
$ buildid=`git describe | cut -b 7-`
$ echo $buildid
201-g8a330360a
$ mvn -Pstaging install -Dbuild.id=$buildid
```

**Comment by arjantijms** [comment]
Sure, why not? The mvn plug-in would have as advantage that anyone building locally and reporting errors or doing debugging has the exact revision, but for our build that would work.
