### ISSUE TITLE
JavaScript charts are not re-rendered with AJAX-Request in JSF

### ISSUE THREAD

**Issue by helper14** [eclipse-ee4j/glassfish#23465]
If an AJAX request is used to update the JavaScript chart data by an backing bean, the request "hangs" and the JSF-page is not re-rendered. 

## Environment Details
* GlassFish glassfish-6.1.0-RC1:
* JDK version: jdk-11.0.11+9
* OS: Win10
* Database:

----------

## Problem Description
I have some JavaScript charts on my JSF pages. It used to work in Glassfish 4 (Mojarra 2.2.7) - now with glassfish-6.1.0-RC1 and jakarta.faces 2.3.9 it doesn't. If an AJAX request is used to update the chart data by an backing bean, the request "hangs" and the chart is not re-rendered. Other JSF-elements of the page aren't updated too. I reproduced the bug with two different chart framworks: EChart and Flot (https://echarts.apache.org/, https://www.flotcharts.org/).

## Steps to reproduce
I add an Maven-Netbeans-project with a simple proof of the bug.
[mavenwebEE9project1.zip](https://github.com/eclipse-ee4j/glassfish/files/6591873/mavenwebEE9project1.zip)

## Impact of Issue
I can't move to Glassfish 6.1/EE9.

[//]: # "Please choose one each Type, Component, and Priority label"

**Comment by krishnakittu** [comment]
Can you disable HTTP2 and try it.
Command to disable HTTP2 support
**asadmin set configs.config.server-config.network-config.protocols.protocol.http-listener-2.http.http2-enabled=false**

**Comment by helper14** [comment]
Hello,

I tried it: Does not make any difference.

By S.M.
