### ISSUE TITLE
GlassFish Console - About info incorrect version qualifier

### ISSUE THREAD

**Issue by rfelcman** [eclipse-ee4j/glassfish#23489]
## Environment Details
* GlassFish Version (and build number): 6.2.0
* JDK version: Oracle JDK "11.0.11" 2021-04-20 LTS
* OS: Linux Debian 10
* Database: MySQL 5.7
* WebBrowser: Firefox 89.0

----------

## Problem Description
About window in console doesn't display version qualifier correctly.
Server was downloaded from https://repo1.maven.org/maven2/org/glassfish/main/distributions/glassfish/6.2.0/glassfish-6.2.0.zip

## Steps to reproduce
- Start GlassFish
- Open Console (e.g. http://localhost:4848) in the web browser
- Click to "About..." button in top of the page
- New version info window is displayed
- It prints instead of complete version with qualifier following `Eclipse GlassFish 6.2.0 (build ${git.branch}-b${git.closest.tag.commit.count}-g${git.commit.id.abbrev} ${git.build.time})`
_It seems, that substitution variables are not correctly loaded._

## Impact of Issue
There is minimal impact to me. I want just point You to this GUI error.

**Comment by arjantijms** [comment]
@rfelcman thanks for the report, I'll take a look.
