### ISSUE TITLE
Remove unused modules from the build and make updating the version id easier

### ISSUE THREAD

**Issue by dmatej** [eclipse-ee4j/glassfish#23485]
## Environment Details
* GlassFish Version (and build number): master branch, 6.x.x-SNAPSHOT
* JDK version: 11

----------

## Problem Description
Version id has to be done manually as a text change, because not all modules are in the same reactor, so using versions maven plugin in this configuration is painful and leads to mistakes. I tried to integrate them in a special profile, but there were still modules standing outside the reactor, so I still had to do some changes manually. This can change, even with some compromise.

Following modules are always ignored and it seems they are not required for anything now:

appserver/admingui/jsftemplating
- repackaged jsftemplating from another repository
- unused

appserver/extras/embedded-shell
- this module exists twice, one stands outside the reactor, both have the same id: <artifactId>glassfish-embedded-shell</artifactId>

<artifactId>jta-xa</artifactId> 
- unused, outside the reactor

<artifactId>ha-apt</artifactId> 
- unused, outside the reactor

<artifactId>glassfish-uber</artifactId> 
- unused, outside the reactor
- never distributed, I have found just [this](https://repo1.maven.org/maven2/org/glassfish/extras/glassfish-uber/)

**Comment by arjantijms** [comment]
Sounds good! +1

**Comment by dmatej** [comment]
Done and merged, you should probably add some labels ...? I don't have rights to do that.

**Comment by arjantijms** [comment]
> you should probably add some labels ...? I don't have rights to do that.

I added the 6.2 milestone to the PR. At the moment labels are a little messy in the GF project. We should probably remove all ancient and unused labels and add new ones that are more to the point.
