### ISSUE TITLE
Transactional Annotation does not rollback when using other than JPA as an O/R mapper.

### ISSUE THREAD

**Issue by dsano82** [eclipse-ee4j/glassfish#23528]
## Environment Details
* GlassFish Version: GlassFish 6.2.0
* JDK version :OpenJDK 11.0.2
* OS: rehl 7.7
* Database: SQL server 8.2.2

----------

## Problem Description
The JTA spec "3.7 Transactional Annotation" says; 

>The following example will override behavior for application exceptions, 
>causing the transaction to be marked for rollback for all application exceptions.
>
>@Transactional(rollbackOn={Exception.class})

However any application exception makes no rollback in the annotated method
if we use other than JPA as an O/R mapper.

Payara server seems to have fixed this problem as 
* https://github.com/payara/Payara/issues/505
* https://github.com/payara/Payara/issues/667

## Steps to reproduce
1. Start glassfish
2. Set JDBC connection pool and JDBC resource
3. Run an application, which  meets below requirements 
    * using mybatis as an O/R mapper  
    * containing Transactional annotation    
    * occurring exception process in transaction processing
4. Check database to confirm

**Comment by OndroMih** [comment]
The same expected behavior - link is added to the GF repo but only visible to me (those who see this private repo)
