### ISSUE TITLE
Use of LdapName triggers Javadoc errors

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/glassfish#23567]
Although not a problem for Javac, Javadoc reports errors regarding `'LdapName`:

```
[ERROR] MavenReportException: Error while generating Javadoc: 

Exit code: 1 - /glassfish/appserver/ldapbp/src/main/java/com/sun/jndi/ldap/obj/LdapPrincipal.java:21: error: cannot find symbol

import com.sun.jndi.ldap.LdapName;
```

**Comment by dmatej** [comment]
Eclipse too has an issue with that, because it is a private forbidden JDK package ... it has to be open somehow ...

**Comment by dmatej** [comment]
We probably could switch to javax.naming.LdapName ...?

**Comment by avpinchuk** [comment]
Completed with #25096. Module `ldapbp` was removed.
