### ISSUE TITLE
Cannot enbale Security Manager from the admin console.

### ISSUE THREAD

**Issue by 11rx4f** [eclipse-ee4j/glassfish#23578]
An error occurs when enabling Security Manager from the admin console.

## Environment Details
* GlassFish Version (and build number): Eclipse GlassFish  6.2.1  (build master-b568-g0f9a1e7 2021-08-30T05:04:52+0000)
* JDK version: OpenJDK 11.0.12+7
* OS: Red Hat Enterprise Linux release 8.0
* Database:

----------

## Problem Description
If you enable Security Manager from the admin console, you will get an error:
![image](https://user-images.githubusercontent.com/53206845/131632567-c440a5b7-f547-49ac-9366-d7f161a025dc.png)

## Steps to reproduce
1. Create a new Cluster, eg SecMgrTest1
2. Navigate to new cluster's config, Configurations > SecMgrTest1-config
3. Navigate to cluster's Security page
4. Check the Enabled checkbox for "Security Manager"
5. Click "Save" button.

## Impact of Issue
We cannot enable Security Manager from the admin console.

**Comment by dmatej** [comment]
The SecurityManager will be removed from the JDK soon, currently we are discussing that we will start sooner with removal in GlassFish7, so I expect we will remove the option too from the UI.

See https://openjdk.java.net/jeps/411
