### ISSUE TITLE
Professional Services Section to README.md

### ISSUE THREAD

**Issue by gerdogdu** [eclipse-ee4j/glassfish#23615]
Hello folks,

We would like to add Professional Service and Support section to README.md to add commercial companies which provides enterprise support for GlassFish Server. 

Here is what we can add:

> **Professional Services**
> 
> Expert advice and production support are available through ManageCat, XYZ Company, ABC Company etc....

As an example, you can check [Eclipse Jetty GitHub page](https://github.com/eclipse/jetty.project) page which includes a link to Webtide.

In the meantime, we would also like to add same to the website https://glassfish.org

Currently, the companies think that GF services and enterprise support is not available by any companies but this is not correct anymore. 

WDYT? 

Regards.
Gurkan

**Comment by gerdogdu** [comment]
I have added a PR https://github.com/eclipse-ee4j/glassfish/pull/23617

**Comment by gerdogdu** [comment]
I have added a comment to PR, [https://github.com/eclipse-ee4j/glassfish/pull/23617#issuecomment-926377511](https://github.com/eclipse-ee4j/glassfish/pull/23617#issuecomment-926377511)

Could you please add your comments to the PR?
Regards.

**Comment by smillidge** [comment]
I am not in favour of this as I don't think the project should endorse companies and we would have to check carefully how the GlassFish trademark was being utilised. There is the Jakarta EE compatibility page for implementations derived from GlassFish.

**Comment by gerdogdu** [comment]
@smillidge  Thanks for your comment. But, the GF project will not endorse any company. Just list the companies providing support and services. It will not specific to special company. Any company can be listed here if they provide support, products, services around GF.

Here are some examples:

- Tomcat : https://cwiki.apache.org/confluence/display/tomcat/SupportAndTraining
- TomEE : http://tomee.apache.org/commercial-support.html
- Jetty : https://github.com/eclipse/jetty.project
- Directory : https://directory.apache.org/commercial-support.html
- NetBeans : https://netbeans.apache.org/help/commercial-support.html
- OpenOffice : https://www.openoffice.org/bizdev/consultants.html

Regards.
