### ISSUE TITLE
Unable to run embedded glassfish

### ISSUE THREAD

**Issue by tnagao7** [eclipse-ee4j/glassfish#23632]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* GlassFish Version (and build number): glassfish-embedded-all 6.2.1 (the one available on maven central; build number unknown)
* JDK version: OpenJDK 11.0.12+7
* OS: CentOS 7.6
* Database:

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

The embedded glassfish (glassfish-embedded-all) cannot be run.
Calling `org.glassfish.embeddable.GlassFishRuntime.bootstrap()` always causes the exception `GlassFishException` as follows.

```
$ java -cp .:glassfish-embedded-all-6.2.1.jar Program
Exception in thread "main" org.glassfish.embeddable.GlassFishException: No runtime builder available for this configuration: {}
	at org.glassfish.embeddable.GlassFishRuntime.getRuntimeBuilder(GlassFishRuntime.java:171)
	at org.glassfish.embeddable.GlassFishRuntime._bootstrap(GlassFishRuntime.java:132)
	at org.glassfish.embeddable.GlassFishRuntime.bootstrap(GlassFishRuntime.java:86)
	at org.glassfish.embeddable.GlassFishRuntime.bootstrap(GlassFishRuntime.java:60)
	at com.example.Program.main(Program.java:7)
```

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

Save the following program as Program.java.

```java
import org.glassfish.embeddable.GlassFish;
import org.glassfish.embeddable.GlassFishProperties;
import org.glassfish.embeddable.GlassFishRuntime;

public class Program {
    public static void main(String[] args) throws Exception {
        GlassFishRuntime runtime = GlassFishRuntime.bootstrap();
    }
}
```

Then compile and run it as follows.

```
$ javac -cp glassfish-embedded-all-6.2.1.jar Program.java
$ java -cp .:glassfish-embedded-all-6.2.1.jar Program
```

## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"

Unable to run the embedded glassfish.

[//]: # "Please choose one each Type, Component, and Priority label"

**Comment by tnagao7** [comment]
## Detailed description of the cause

The cause of this problem is absence of the hk2 descriptor file `META-INF/hk2-locator/default` in the glassfish-embedded-all jar.

```
$ jar tf glassfish-embedded-all-5.1.0.jar | grep META-INF/hk2-locator
META-INF/hk2-locator/default
META-INF/hk2-locator/

$ jar tf glassfish-embedded-all-6.2.1.jar | grep META-INF/hk2-locator
META-INF/hk2-locator/
```

The absence of the hk2 descriptor file is caused by the version mismatching between Ant (Ant 1.10.10) and maven-antrun-extended-plugin (requiring Ant 1.6.5), which is introduced by PR #23473.
I confirmed that reverting #23473 solves the problem.

The reason the problem occurs with newer versions of Ant is that Ant 1.8+ almost omits the first of two jar-scanning phases.
The `rejar` task (used in [build.xml](https://github.com/eclipse-ee4j/glassfish/blob/6.2.1/appserver/extras/embedded/build.xml), defined in [RejarTask](https://github.com/javaee/maven-antrun-extended-plugin/blob/maven-antrun-extended-plugin-1.43/src/main/java/org/jvnet/maven/plugin/antrun/RejarTask.java)) expects that jar files are scanned twice as follows, but Ant 1.8+ omits the first scan except for `META-INF/MANIFEST.MF` file.

* 1st scan (`skipWriting` is true) to scan input files
* 2nd scan (`skipWriting` is false) to write files out to destination jar

These two scanning phases are necessary, and thus it takes a long time to build the embedded glassfish.
Build speed increase by #23473 is due to the lack of the first jar-scanning phase.

This change in Ant 1.8+ was introduced by the modification of `org.apache.tools.ant.taskdefs.Jar#getResourcesToAdd` method in the commit https://github.com/apache/ant/commit/8df1ef0ecfcd30c0445cb3f7300cdf8e16e32df1#diff-f24349915dd67fba9286d03c4c26dd424a07ac3fb747b2a21b62852b3c94a280R782-R789

**Comment by tnagao7** [comment]
To fix this problem, approaches such as below can be considered:

- Changing the version of Ant to the original one, or
- Adding a task to generate hk2 descriptor files after the current `rejar` task

**Comment by dmatej** [comment]
Wow, thank you for the investigation! And sorry I caused this issue, I'm working on test improvements to avoid these things. I would like to avoid Ant at all in some near future, but again, without tests it is hard to guarantee anything.
