### ISSUE TITLE
Remove usages of maven-antrun-extended-plugin

### ISSUE THREAD

**Issue by dmatej** [eclipse-ee4j/glassfish#23641]
- the plugin is not maintained and has obsoleted (Java 1.5, Maven 2.0.7, Ant 1.6.5, last version 2012)
- in #23640 we found a way how to replace Ant with Maven
- so let's continue on remaining usages.

**Comment by OndroMih** [comment]
The commit https://github.com/dmatej/glassfish/commit/a53e2d0a0f9b4e96526c706dbd9132bc08b4eeb1 breaks copying the templates resources into the final distribution. In the distribution projects (e.g. appserver/distributions/glassfish), JAR dependencies are copied to target/dependency while ZIP dependencies are extracted. If templates artifact is packaged as JAR, it's not extracted and the Assembly plugin won't copy its contents to the distribution.
