### ISSUE TITLE
Investigate making standalone Jakarta Transactions project

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/glassfish#23669]
Many components of GlassFish, like Faces (Mojarra) and Pages (WaSP) have standalone implementations.

Jakarta Transactions however is integrated in the GlassFish code, though it does have its own package.

Just like the recently created Exousia, investigate whether it's possible to create a standalone project from the GF Transactions implementation, which can be used with e.g. Weld on Tomcat, or can be used entirely standalone in Java SE.

**Comment by gerdogdu** [comment]
Yes, I think this is possible because I integrated GlassFish Transaction Manager implementation to extend Apache Tomcat JDBC pooling via supporting of XA Connections. But, the project may depend to several GF related internal projects.
