### ISSUE TITLE
Improve build time (fix regression)

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/glassfish#23692]
running `mvn -U -C clean install -Pstaging -Dcheckstyle.skip=true` on my box used to take <30mins some time ago. The build of current master (204d3af):

```
...
[INFO] GlassFish OSGi Console Plugin ...................... SUCCESS [ 14.059 s]
[INFO] GlassFish Flashlight Client ........................ SUCCESS [ 12.284 s]
[INFO] Flashlight ......................................... SUCCESS [  0.049 s]
[INFO] Ant tasks .......................................... SUCCESS [ 12.109 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:28 h
[INFO] Finished at: 2021-11-01T13:08:55+01:00
[INFO] ------------------------------------------------------------------------
```

re-running the build after few changes:

```
[INFO] Glassfish Distribution ............................. SUCCESS [ 41.555 s]
[INFO] Security Related Implementation for GlassFish ...... SUCCESS [  0.347 s]
[INFO] GlassFish Tests .................................... SUCCESS [  0.149 s]
[INFO] GlassFish Tests - TCK .............................. SUCCESS [  0.149 s]
[INFO] GlassFish Tests - TCK - Authorization .............. FAILURE [01:45 min]
[INFO] GlassFish Tests - TCK - Embedded EJB - Smoke ....... SKIPPED
[INFO] GlassFish JavaTest install ......................... SKIPPED
[INFO] EJB Lite Basic ..................................... SKIPPED
[INFO] GlassFish Tests - TCK - Run embedded EJB smoke ..... SKIPPED
[INFO] Console extensions for OSGi platforms .............. SKIPPED
[INFO] Felix Web Console Extension for GlassFish .......... SKIPPED
[INFO] GlassFish OSGi Console Plugin ...................... SKIPPED
[INFO] GlassFish Flashlight Client ........................ SKIPPED
[INFO] Flashlight ......................................... SKIPPED
[INFO] Ant tasks .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:13 h
[INFO] Finished at: 2021-11-01T17:14:03+01:00
[INFO] ------------------------------------------------------------------------
```

Seriously? Does one have to wait for hours to find out he has done something wrong somewhere?

https://ci.eclipse.org/glassfish/view/GlassFish/job/glassfish_weekly_build/buildTimeTrend shows that I'm not alone who sees the significant slowdown of the build - it went from 10mins to 20mins

**Comment by dmatej** [comment]
If you need it just for manual testing, you can run mvn clean install -Pfastest -T4C
On my machine it is under 3 minutes. 
Currently I am trying to refactor some things to make it more aligned to maven lifecycle, but until we get rid of "distribution-fragments" it will be still limited a bit ...

But especially that downloading in tck-authorization will be better after I will push this week (I hate it too) :-)

**Comment by arjantijms** [comment]
Indeed, with `-Pfastest -T8` it's some 5 minutes even an older machines (5 to 6 year old).

**Comment by lukasj** [comment]
I need to update some dependencies - that means to repeat change poms, full rebuild and run QL tests until all tests pass - which is quite common dev cycle. Given one build takes 1-2hours, there is not much room for mistakes and `-Pfastest` skips tests which I need to run

> Currently I am trying to refactor some things to make it more aligned to maven lifecycle, but until we get rid of "distribution-fragments" it will be still limited a bit ...

how is that going to help avoiding doing unnecessary resource filtering? As I see it, most time is being spent on that. Having said that - #23694 saves ~1 hour on my end

Additional improvements which can be done - move non-java files from the java source root to resources root - ie following should find nothing:

```
$ find . -name java -type d -exec find {} -iname *.prop* \;
./appserver/connectors/work-management/src/main/java/com/sun/enterprise/connectors/work/LocalStrings.properties
./appserver/connectors/admin/src/main/java/org/glassfish/connectors/admin/cli/LocalStrings.properties
./appserver/connectors/connectors-internal-api/src/main/java/org/glassfish/connectors/config/validators/LocalStrings.properties
./appserver/transaction/jts/src/main/java/com/sun/jts/utils/RecoveryHooks/Messages_en_US.properties
./appserver/transaction/jts/src/main/java/com/sun/jts/utils/RecoveryHooks/Messages.properties
./appserver/security/core-ee/src/main/java/com/sun/enterprise/security/auth/digest/impl/LocalStrings.properties
./appserver/security/core-ee/src/main/java/com/sun/enterprise/security/ee/audit/LocalStrings.properties
./appserver/security/core-ee/src/main/java/com/sun/enterprise/security/acl/LocalStrings.properties
```
or remove obsolete global exclusion filters on resources

**Comment by gerdogdu** [comment]
In my machine, it takes 53 mins to run mvn clean install -DskipTests -Pstaging, before it took 20 mins something like that.

@dmatej You have been working on the tests etc. Did you update anything regarding more checks on the source files, checkstyle etc?

**Comment by gerdogdu** [comment]
Maybe you can try to disable -Dcheckstyle.skip=true

**Comment by lukasj** [comment]
> running mvn -U -C clean install -Pstaging -Dcheckstyle.skip=true on my box ...

**Comment by gerdogdu** [comment]
mvn clean install -Dcheckstyle.skip=true  -Pstaging

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  28:09 min
[INFO] Finished at: 2021-11-02T12:17:21+03:00
[INFO] ------------------------------------------------------------------------

**Comment by lukasj** [comment]
so with my changes from #23694 running `mvn -U -C clean install -Pstaging -Dcheckstyle.skip=true -T8` took ~20mins - well, not ideal, ie I do not understand why TCKs should be part of every build when QL takes similar amount of time and cover more functionality, but acceptable, definitely better than >1h

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21:52 min (Wall Clock)
[INFO] Finished at: 2021-11-02T10:14:54+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by gerdogdu** [comment]
I think you may also disable to run TCK Authorization? Why do we run TCK test in default build?
[INFO] GlassFish Tests - TCK - Authorization .............. SUCCESS [02:39 min]

**Comment by dmatej** [comment]
After we merge both PRs it should be much better. There are two profiles:
`-Pfastest `just to get artifacts; it skips all tests and QA plugins, also tck.
`-Pfast` skips just QA plugins and tck, but still executes unit tests (however their coverage is poor)
Some time ago I fixed many ignored tests, but they don't take so much time. The worst thing here was the authorization, which always downloaded two zip files. In that PR I do that just once, maven plugin caches them and even two included jar files are installed as standard maven dependency (not deployed) and then reused.

Proper solution would be if **tsharness**, **javatest** and others would be available in some maven repository, then we can simply drop part of this. But even now it should be much faster. And if TCK would not use Ant ... ok, dreams of a future :D

**Comment by dmatej** [comment]
There is yet one PR blocked by one other, waiting for @lukasj  attention :-)

**Comment by lukasj** [comment]
```
$ git rev-parse --short HEAD
3218a2687

$ git status
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean

$ mvn -U -C clean install -Pstaging -Dcheckstyle.skip=true
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:23 h
[INFO] Finished at: 2021-11-03T19:40:26+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by dmatej** [comment]
Btw, why are you running -U? Is your build depending on some snapshot dependency outside the project?

**Comment by lukasj** [comment]
I'm used to use `-U` as I do use snapshots in my _local_ builds quite often. The overhead it brings is not that big.

**Comment by dmatej** [comment]
Hmm, on my slow wifi it is significant, it can double build time. Unless I use some special settings in settings.xml (mirrors, and updatePolicy set to daily ie.)
