### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by dmatej** [eclipse-ee4j/glassfish#23705]
- Especially building should be much better - where can I find built artifacts, how to get them faster
- Compatibility
- Basic commands

**Comment by dmatej** [comment]
See also discussion in https://github.com/eclipse-ee4j/glassfish/issues/23692

**Comment by gerdogdu** [comment]
@dmatej  Do you mean the README.md in the root?

**Comment by ttelang** [comment]
README.md at the root says "Eclipse GlassFish 5.1 is also Java EE 8 Compatible."
It should be updated to "Eclipse GlassFish 6.2.2 is Jakarta EE 9.1 Compatible."
