### ISSUE TITLE
Can't create new JavaMail Session using GlassFish Console

### ISSUE THREAD

**Issue by neo2238** [eclipse-ee4j/glassfish#23717]
## Environment Details
* GlassFish Version (and build number): GlassFish 6.2.3 (build master-b122-g6dcda93 2021-11-18T16:34:28+0000)
* JDK version: openjdk version "**17.0.1**" 2021-10-19
* OS:Rocky Linux 8.4 (Green Obsidian)
* Database:

----------

## Problem Description
Can't create new JavaMail Session using GlassFish Console
![image](https://user-images.githubusercontent.com/94802335/142775655-7c0a7a4c-288d-48aa-8564-78975bc1a3df.png)

## Steps to reproduce
Download latest glassfish 6.2.3
Configure admin password and enable secure admin
Go to JavaMail Sessions under Resources in GlassFish Console
Try add new JavaMail Session

**Comment by hendrik-weiler** [comment]
You can alternatively create a mail session with bin/asadmin. After creating the session you can update the session through the admin console.

```
Command create-javamail-resource not found. 
Check the entry of command name. This command may be provided by a package that is not installed.
Closest matching local and remote command(s): 
    create-mail-resource

Command create-javamail-resource failed.
$ ./asadmin create-mail-resource --help
NAME
     create-mail-resource

SYNOPSIS
     Usage: create-mail-resource --mailhost=mailhost --mailuser=m
     ailuser --fromaddress=fromaddress [--storeprotocol=imap] [--
     storeprotocolclass=com.sun.mail.imap.IMAPStore] [--transprot
     ocol=smtp] [--transprotocolclass=com.sun.mail.smtp.SMTPTrans
     port] [--enabled=true] [--debug=false] [--property=property]
      [--target=server] [--description=description] jndi_name 

OPTIONS
     --mailhost

     --mailuser

     --fromaddress

     --storeprotocol

     --storeprotocolclass

     --transprotocol

     --transprotocolclass

     --enabled

     --debug

     --property

     --target

     --description

OPERANDS
     jndi_name
Command create-mail-resource executed successfully.
```

**Comment by jaceabreu** [comment]
I second this bug and have worked around it by using the CLI asadmin utility.
The Admin Web UI complains about a "create-javamail-resource" subcommand while the actual subcommand is "create-mail-resource."
