### ISSUE TITLE
jakarta.enterprise.cdi-api not reachable through javaee.jar

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/glassfish#23745]
javaee.jar (which should be renamed to jakartaee.jar) still references cdi api artifact as `cdi-api.jar` which no longer exists. In the end, one is not able to use `javaee.jar` as a single entry point to EE APIs (see [the source](https://github.com/eclipse-ee4j/glassfish/blob/6.2.3/appserver/extras/javaee/manifest-jar/pom.xml#L40))

**Comment by dmatej** [comment]
Relates to https://github.com/eclipse-ee4j/glassfish/issues/23455
