### ISSUE TITLE
Build for snapshots is not executed in weekly build

### ISSUE THREAD

**Issue by pzygielo** [eclipse-ee4j/glassfish#23835]
```diff
--- https://ci.eclipse.org/glassfish/view/GlassFish/job/glassfish_weekly_build/103/consoleFull
+++ https://ci.eclipse.org/glassfish/view/GlassFish/job/glassfish_build-and-publish-to-eclipse-download/657/consoleFull
@@ -1,7 +1,6 @@
 + bash -xe ./gfbuild.sh build_re_dev
-+ '[' -z /home/jenkins/agent/workspace/glassfish_weekly_build ']'
++ '[' -z /home/jenkins/agent/workspace/glassfish_build-and-publish-to-eclipse-download/glassfish-build ']'
 + build_re_dev
-+ '[' -f /home/jenkins/agent/workspace/glassfish_weekly_build/snapshots/pom.xml ']'
-+ dev_build
-+ mvn -U clean install -Pstaging,fastest -T2C
++ '[' -f /home/jenkins/agent/workspace/glassfish_build-and-publish-to-eclipse-download/glassfish-build/snapshots/pom.xml ']'
++ mvn clean install -T2C -s /home/jenkins/agent/workspace/glassfish_build-and-publish-to-eclipse-download/glassfish-build/snapshots/settings.xml -f /home/jenkins/agent/workspace/glassfish_build-and-publish-to-eclipse-download/glassfish-build/snapshots/pom.xml
```

Note: the extra `glassfish-build` in `WORKSPACE` envvar in nightly build. As weekly build has only top-level directory in WORKSPACE - `snapshots/pom.xml` is not discovered, build for snapshots is not executed, build continues with main GF project.

Related:
- https://github.com/eclipse-ee4j/glassfish/pull/23832
- https://github.com/eclipse-ee4j/glassfish/pull/23824

This is above my privileges to inspect Jenkins jobs, so I leave the next steps to project's Committers.

**Comment by pzygielo** [comment]
Hi @hs536 - maybe https://github.com/eclipse-ee4j/glassfish/pull/23824#discussion_r813480026 /[*1] should also be applied to weekly build?

**Comment by hs536** [comment]
> maybe https://github.com/eclipse-ee4j/glassfish/pull/23824#discussion_r813480026 /[*1] should also be applied to weekly build?

Yes, indeed. I've applied.

**Comment by pzygielo** [comment]
> > maybe [#23824 (comment)](https://github.com/eclipse-ee4j/glassfish/pull/23824#discussion_r813480026) /[*1] should also be applied to weekly build?
> 
> Yes, indeed. I've applied.

Thanks - I checked and [current failure](https://ci.eclipse.org/glassfish/view/GlassFish/job/glassfish_weekly_build/105) (at later) stage has snapshots built successfully.
