### ISSUE TITLE
Message catalog key not transformed: using.default.ds

### ISSUE THREAD

**Issue by mheydem** [eclipse-ee4j/glassfish#23873]
## Environment Details
* GlassFish Version (and build number): Glassfish 6.0 Release
* JDK version: corretto jdk1.8.0_322
* OS: Windows 10

----------

## Problem Description
This message appears in my server.log:
```
[2022-03-29T13:06:44.563+0000] [glassfish 6.0] [WARNING] [] [javax.enterprise.resource.resourceadapter.org.glassfish.jdbcruntime] [tid: _ThreadID=33 _ThreadName=RunLevelControllerThread-1648559203407] [timeMillis: 1648559204563] [levelValue: 900] [[
  using.default.ds]]
```
A more meaningful  text like this is expected:
`RAR8068: Using default datasource : {0} for pool : {1}`

This issue was fixed for Payara. Glassfish could have this fix, too.
https://github.com/payara/Payara/issues/502

## Steps to reproduce
Not sure. I guess using a jdbc resource adapter can trigger this.

## Impact of Issue
This issue does not to hurt functionality, but animates developers to waste time on useless investigation.

**Comment by pzygielo** [comment]
With unit test for `appserver/jdbc/jdbc-runtime/src/main/java/org/glassfish/jdbc/util/JdbcResourcesUtil.java` and `appserver/jdbc/jdbc-runtime/src/main/java/org/glassfish/jdbcruntime/JdbcRuntimeExtension.java` I'm getting as expected:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] [0.023s][info][gc] Using G1
[INFO] [0.511s][info][gc] GC(0) Pause Young (Normal) (G1 Evacuation Pause) 14M->3M(256M) 7.635ms
[INFO] Running org.glassfish.jdbc.util.JdbcResourcesUtilTest
Mar 29, 2022 7:55:37 PM org.glassfish.jdbc.util.JdbcResourcesUtilTest testlog
WARNING: RAR8068: Using default datasource : ABCD for pool : EFGH
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.234 s - in org.glassfish.jdbc.util.JdbcResourcesUtilTest
[INFO] Running org.glassfish.jdbcruntime.JdbcRuntimeExtensionTest
Mar 29, 2022 7:55:37 PM org.glassfish.jdbcruntime.JdbcRuntimeExtensionTest testlog
WARNING: RAR8068: Using default datasource : ABCD2 for pool : EFGH2
```


> Steps to reproduce
> Not sure.

what about
> animates developers to waste time 

?

**Comment by mheydem** [comment]
I was able to narrow down the problem.
It occurs in connection with a custom AuditModule.
I think the fix or this particular constellation is not of public interest.
That is why I am closing this big report. Thank you for your help.
If I find something interesting, I will share it with you.

**Comment by dmatej** [comment]
Ok, it is in my list in GF too :)

**Comment by mheydem** [comment]
I was able to reproduce this by extending domain.xml of the default domain1:
- adding a `<jdbc-connection-pool res-type="javax.sql.XADataSource" datasource-classname="oracle.jdbc.xa.client.OracleXADataSource" name="OracleConnectionPool">`
- adding a `<jdbc-resource pool-name="OracleConnectionPool" jndi-name="jdbc/oracle">`
- adding an application which accesses the jdbc-resource via jndi (or by a custom audit module)
- make sure the oracle libs are NOT provided to glassfish (for example ojdbc8.jar)
@dmatej Can you create the symptoms in the same way?
