### ISSUE TITLE
Do extra work to integrate Weld 5

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/glassfish#23872]
Weld 5 has changed things so that extra work is needed to integrate it.

See http://weld.cdi-spec.org/news/2022/01/24/weld-500Beta1/ and

https://www.eclipse.org/lists/cdi-dev/msg00573.html

**Comment by gurunrao** [comment]
CDI TCK with GF7 has 102 failures CI run [link](https://ci.eclipse.org/jakartaee-tck/job/cditck-porting/job/master/157/#showFailuresLink) .
BV TCK with GF 7 has 165 failures CI run [link](https://ci.eclipse.org/jakartaee-tck/job/bvtck-porting/job/master/147/#showFailuresLink)

**Comment by arjantijms** [comment]
@gurunrao 

The latest numbers with [updated GF](https://github.com/eclipse-ee4j/glassfish/pull/23944) and [updated CDI API](https://github.com/jakartaee/cdi/pull/616) are:

```
Tests run: 1863, Failures: 54, Errors: 0, Skipped: 32


Additionally, the existing TCK porting kit is very large. It's possible to run the CDI TCK with much less code. See https://github.com/eclipse-ee4j/glassfish/tree/master/appserver/tests/tck/cdi
```

**Comment by dmatej** [comment]
Example:
`mvn clean install -Pstaging,tck -pl :glassfish-external-tck-cdi -Dtest=**/full/extensions/lifecycle/**`

**Comment by dmatej** [comment]
Can this be already closed, or everything is done now?

**Comment by arjantijms** [comment]
I think it’s all done now done ✅
