### ISSUE TITLE
GlassFish 7 needs --add-opens=java.base/java.lang=ALL-UNNAMED

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/glassfish#23915]
https://github.com/eclipse-ee4j/glassfish/issues/23805 seems similar but was closed.  During EE 10 (Full) Platform TCK testing we are seeing [Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @10315254](https://gist.github.com/scottmarlow/cafb1c9b63b4f56b6ddbfb5d6369b41b) failures in TCK test run https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-jakartaeetck-run-100/38

I see some references to "--add-opens" in GlassFish 7 source but none of them seem to solve the `InaccessibleObjectException` failure in https://gist.github.com/scottmarlow/cafb1c9b63b4f56b6ddbfb5d6369b41b.

**Comment by dmatej** [comment]
Server already sets this:
`<jvm-options>--add-opens=java.base/java.lang=ALL-UNNAMED</jvm-options>`

So I would expect it is a client issue, despite I see server classes in the stacktrace. I see some compiler message in the gist before the stacktrace, is it the same process/JVM as the one which produced the stacktrace?

`[ts.javac] Compiling 21 source files to /root/jakartaeetck/classes`

There was also an issue with defining proxy classes in runtime we fixed months ago - each way has it's own limitations. But that related to corba and old RMI.

**Comment by dmatej** [comment]
Oh, it is in the stacktrace, this is the criminal ...
`at com.sun.ts.tests.common.vehicle.VehicleClient.main(VehicleClient.java:37)`

**Comment by dmatej** [comment]
There is yet much more similar issues. Simply the TCK client doesn't set any add-opens.
https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-jakartaeetck-run-100/37/testReport/junit/com.sun.ts.tests.ejb30.lite.packaging.embed.classloader.annotated/Client/additionalModuleDir_from_ejbembed/

**Comment by lukasj** [comment]
to goal should be to avoid the need for add-opens. In this particular case the problem in [ClassGenerator](https://github.com/eclipse-ee4j/glassfish/blob/master/appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/ClassGenerator.java#L58) by using something like I used in [Injector](https://github.com/eclipse-ee4j/metro-jax-ws/blob/master/jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/model/InjectorHelper.java) to get the "hidden" method and bypass exceptions..

**Comment by scottmarlow** [comment]
Good point @dmatej, I just added a few more lines to the start to give more context.

**Comment by dmatej** [comment]
> the goal should be to avoid the need for add-opens. In this particular case the problem in [ClassGenerator](https://github.com/eclipse-ee4j/glassfish/blob/master/appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/ClassGenerator.java#L58) can be fixed by using something like I used in [InjectorHelper](https://github.com/eclipse-ee4j/metro-jax-ws/blob/master/jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/model/InjectorHelper.java#L53) to get the "hidden" method and bypass exceptions..

That would be nice, but it is impossible now.

**Comment by scottmarlow** [comment]
> Can I reproduce it locally somehow without running the whole TCK?

I will try reproducing locally with Java SE 17 + following https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Run-a-Platform-TCK-test-with-GlassFish-7

**Comment by dmatej** [comment]
I think I have all information I needed for now, thanks. 
(I completely forgot I already cloned jakartaee-tck project months ago and created some magic shell script which is running now).

**Comment by dmatej** [comment]
> the goal should be to avoid the need for add-opens. In this particular case the problem in [ClassGenerator](https://github.com/eclipse-ee4j/glassfish/blob/master/appserver/ejb/ejb-container/src/main/java/com/sun/ejb/codegen/ClassGenerator.java#L58) can be fixed by using something like I used in [InjectorHelper](https://github.com/eclipse-ee4j/metro-jax-ws/blob/master/jaxws-ri/runtime/rt/src/main/java/com/sun/xml/ws/model/InjectorHelper.java#L53) to get the "hidden" method and bypass exceptions..

Yet something - that mechanism used by the InjectorHelper is exactly used here and causes the stacktrace. The point is that JDK17+ is more restrictive than JDK11. There is yet one solution (MethodHandle, used also in HK2), but both solutions have consequences and limitations.

Also original implementation ignored many exceptions, but then GF didn't pass it's own tests and was impossible to find out why.

So the solution is to add add-opens for client (while we use reflection to access the defineClass method; we can use MethodHandles, but such proxies are different and don't work as expected). 

See #23628 

There is yet one stacktrace before this - another add-opens required:
```
java.lang.reflect.InaccessibleObjectException: Unable to make field private static javax.naming.spi.InitialContextFactoryBuilder javax.naming.spi.NamingManager.initctx_factory_builder accessible: module java.naming does not "opens javax.naming.spi" to unnamed module @10315254
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at com.sun.enterprise.naming.GlassFishNamingBuilder.resetInitialContextFactoryBuilder(GlassFishNamingBuilder.java:187)
	at com.sun.enterprise.naming.GlassFishNamingBuilder.preDestroy(GlassFishNamingBuilder.java:179)
	at org.jvnet.hk2.internal.ClazzCreator.preDestroyMe(ClazzCreator.java:370)
	at org.jvnet.hk2.internal.ClazzCreator.dispose(ClazzCreator.java:441)
	at org.jvnet.hk2.internal.SystemDescriptor.dispose(SystemDescriptor.java:521)
```

I don't think the evolution will stop here, but first we need more and much better tests, because especially things around proxies, RMI and Corba are pretty nasty. And package names matter (which wasn't true for proxies until JDK11).

These tests use embedded container, so probably there is no other option than add-opens.

**Comment by dmatej** [comment]
Funny, I found that @arjantijms  already added one ejb30.lite test to the GlassFish build and look what he did here:
https://github.com/eclipse-ee4j/glassfish/blob/82054008794f21bb88ece2a5c6fba3d63d0e5c2a/appserver/tests/tck/embedded_ejb_smoke/runner/src/test/java/com/sun/ts/run/EmbeddedRunnerITest.java#L85

(Test is executed from JUnit5 test instead of Ant/Bash)

**Comment by lukasj** [comment]
> Yet something - that mechanism used by the InjectorHelper is exactly used here

no, it is not and MethodHandles may not help unless you get the right Lookup from the caller - which you are unlikely to get without API changes.

**Comment by dmatej** [comment]
When I removed those add-opens, it passed on JDK11, but crashed on JDK17 with nearly same exceptions - one more was from HK2.

**Comment by dmatej** [comment]
> > Yet something - that mechanism used by the InjectorHelper is exactly used here
> 
> no, it is not and MethodHandles may not help unless you get the right Lookup from the caller - which you are unlikely to get without API changes.

Oh, I see, you use the evil `Unsafe` there. That seems to me even worse than add-opens. We plan some larger refactoring later this year, so I hope we will reduce the need for add-opens, but for now I would prefer that.

**Comment by lukasj** [comment]
There are cases where one cannot avoid using Unsafe and this is one of them as there is no public API in Java for the use case of the ClassGenerator and add-* options  are ment just to help projects moving forward (it’s like saying we’re not ready yet to the user). Also note that these options are not transitive, so there’s some impact on usability and maintenance cost as well.

…but your project, your choice ;-)

**Comment by scottmarlow** [comment]
@dmatej do you plan to make a GlassFish change for this issue?

**Comment by scottmarlow** [comment]
I'm not seeing this failure now but I need to confirm with more testing and examination of Platform TCK test results.  I will reopen or simply comment depending on what I find next.

**Comment by dmatej** [comment]
Just for the record and probable readers who will see this too.

The current state is that if you want to use GF components directly (not using the server, but ie. ejb-container.jar), you have to set several add-opens JVM options. That applies also to embedded usages and clients used in the TCK.

Take a look these settings in domain.xml, you will probably need just some of them. We plan to reduce the list later, but first I want to have faster tests with better coverage, so we can be more radical, faster and safe.
https://github.com/eclipse-ee4j/glassfish/blob/a02f20e847340fe8f2889f63a6cb1d696c3d16c8/appserver/admin/template/src/main/resources/config/domain.xml#L211
