### ISSUE TITLE
EE 10:  JSP engine needs update to handle NO-OP <jsp:plugin> actions.

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/glassfish#23914]
As mentioned in https://github.com/eclipse-ee4j/jakartaee-tck/pull/940#issuecomment-1108773460, applet is not supported in Jakarta EE 10 and the Standalone Pages TCK is now updated to require jsp:plugin to be ignored as per change https://github.com/eclipse-ee4j/jakartaee-tck/pull/940

**Comment by arjantijms** [comment]
Thanks for creating this issue, I'm on it.
