### ISSUE TITLE
EE 10: wasp runtime needs to be fixed to not fail with `ClassCastException: class org.glassfish.wasp.runtime.ELContextWrapper cannot be cast to class org.glassfish.wasp.runtime.ELContextImpl `

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/glassfish#23931]
As per https://www.eclipse.org/lists/jsp-dev/msg00303.html +  https://www.eclipse.org/lists/jsp-dev/msg00304.html, GlassFish 7.0 needs an update to resolve the below ClassCastException mentioned as #2 in https://www.eclipse.org/lists/jsp-dev/msg00302.html:
```
2.  ClassCastException: class org.glassfish.wasp.runtime.ELContextWrapper cannot be cast to class org.glassfish.wasp.runtime.ELContextImpl (org.glassfish.wasp.runtime.ELContextWrapper and org.glassfish.wasp.runtime.ELContextImpl are in unnamed module (see full failure in [4]).  

[4] https://gist.github.com/scottmarlow/841b30e370ea8caa75f2ba16aef77f05
```

**Comment by arjantijms** [comment]
The path taken when the security manager is active didn't had the code updated. It is now as per:

https://github.com/eclipse-ee4j/glassfish/pull/23932

Can you try again with the next nightly?

**Comment by arjantijms** [comment]
I ran the nightly against the 10/TCK job, and it seems to pass now:


https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1781/console
