### ISSUE TITLE
Cant start server

### ISSUE THREAD

**Issue by SekaNuos** [eclipse-ee4j/glassfish#23956]
When trying to start server, it's just goes one like nothing happend. 
Any commands after asadmin - ignored?

## Environment Details
GlassFish Version  5.2022.2
JDK 17
OS: Windows 10

----------
![image](https://user-images.githubusercontent.com/96438712/171059460-6b18ea56-08d7-46f0-bc6b-2e55726a9f5b.png)

**Comment by arjantijms** [comment]
Did you try the latest version of GlassFish? See https://github.com/eclipse-ee4j/glassfish/releases/tag/6.2.5

Also to see the logs directly in your console, try `asadmin start-domain --verbose`

**Comment by pzygielo** [comment]
This seems to be a problem with different project.

**Comment by dmatej** [comment]
You are not using GlassFish but Payara. Please report the issue to their team (or first try to find if someone did not report it already).
https://github.com/payara/Payara/issues
