### ISSUE TITLE
provide link to download latest nightly build on the GF downloads page

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/glassfish#23998]
https://glassfish.org/download should provide a link to download the latest greatest nightly build

**Comment by OndroMih** [comment]
There's now information about GlassFish 7 milestone versions, with a download link pointing to the [Eclipse Foundation Download portal](https://download.eclipse.org/ee4j/glassfish/). Under this link, there's also a ZIP with a nightly build, although the download page doesn't mention that.

Is that enough? I think that general public doesn't need a nightly build, a milestone build should be enough. And those that want the nightly build will most probably find out themselves that it's under the link for the milestone versions.

**Comment by lukasj** [comment]
changing

> You can download the latest Eclipse GlassFish 7 milestone version ...

to

> You can download the latest Eclipse GlassFish development milestone or nightly version ...

would make it more obvious. WDYT?
