### ISSUE TITLE
Include org.glassfish.jersey.ext.cdi:jersey-cdi-rs-inject to support @Inject in Jakarta REST

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/glassfish#24049]
## Environment Details
* GlassFish Version (and build number): Glassfish
* JDK version: 17
* OS: Windows
* Database: built-in Derby

----------

## Problem Description
I have tried to use `@Inject` to replace `@Context` in Jaxrs beans, all failed to works.
see: https://github.com/eclipse-ee4j/jersey/issues/5100

```java
@Path("todos")
@RequestScoped
public class TodoResources {

    //@Inject
    @Context
    ResourceContext resourceContext;

    //@Inject
    @Context
    UriInfo uriInfo;

````

And I follow the new features in Rest 3.1 article to taste Jaxrs 3.1. https://dev.to/andymc12/what-s-coming-in-jakarta-rest-3-1-ole

## Steps to reproduce
1. Checkout my sample project,  https://github.com/hantsy/jakartaee10-sandbox/tree/master/rest 
2. build and deploy to Glassfish
3. If changing `@Context` to `@Inject` in the `TodoResources.java`, all failed.

**Comment by OndroMih** [comment]
AFAIK, Jakarta REST 3.1 (EE 10) doesn't specify anything about injecting JAX-RS resources using `@Inject` yet, besides claiming that injection using `@Context` annotation is deprecated and it will be replaced by CDI's `@Inject` in the future. Usage of `@Context` annotation is deprecated without any suggested alternative yet. The [Javadoc just says](https://jakarta.ee/specifications/restful-ws/3.1/apidocs/jakarta.ws.rs/jakarta/ws/rs/core/context): "Note that future versions of this API will stop supporting injection via Context as part of a tighter integration and alignment with [Jakarta CDI](https://jakarta.ee/specifications/cdi/)". 

Therefore I don't think this is a bug, rather an enhancement request. It certainly would be nice to support this in GlassFish 7. Especially, since there is already support for it in Jersey with `org.glassfish.jersey.ext.cdi:jersey-cdi-rs-inject` as mentioned in comment [here](https://github.com/eclipse-ee4j/jersey/issues/5100#issuecomment-1189308215). This module is not included in GlassFish and never was, but it's probably easy to add it to GlassFish (although just dropping it into GlassFish module directory [isn't enough](https://github.com/eclipse-ee4j/jersey/issues/5100#issuecomment-1204866756))

**Comment by hantsy** [comment]
It seems the latest Glassfish 7.0.0-M9 includes `org.glassfish.jersey.ext.cdi:jersey-cdi-rs-inject`, but I still encountered an issue when using `@Inject UriInfo` or `@Inject ResourceContext`. 

According to the exception info, I added an extra `@Any` annotation, still failed.
```java

    @Inject
    @Any
    ResourceContext resourceContext;

    @Inject
    @Any // or  @JaxRsContext
    UriInfo uriInfo;
```
The exception info like this.

```bash 
Oct 01, 2022 10:04:20 AM org.jboss.arquillian.container.glassfish.clientutils.GlassFishClientUtil getResponseMap
SEVERE: exit_code: FAILURE, message: Error occurred during deployment: Exception while loading the app : CDI deployment failure:WELD-001408: Unsatisfied dependencies for type ResourceContext with qualifiers @Any
  at injection point [BackedAnnotatedField] @Inject @Any com.example.TodoResources.resourceContext
  at com.example.TodoResources.resourceContext(TodoResources.java:0)
. Please see server.log for more details. [status: CLIENT_ERROR reason: Bad Request]
Oct 01, 2022 10:04:20 AM org.jboss.arquillian.container.glassfish.clientutils.GlassFishClientUtil getResponseMap
WARNING: exit_code: FAILURE, message: Resource not found. [status: CLIENT_ERROR reason: Not Found]
```

The complete server log file, 
[server.log](https://github.com/eclipse-ee4j/glassfish/files/9689342/server.log)

**Comment by OndroMih** [comment]
Did you try with adding the `jersey-cdi-rs-inject` module into GlassFish? It's not bundled in GlassFish by default, so there's no way injecting works if this module isn't added to GlassFish. Maybe it's enough to add it to the application but I'm not sure if it's enough.

**Comment by hantsy** [comment]
If I copy the `jersey-cdi-rs-inject` to the target Glassfish modules by dependency plugin.

```xml
<execution>
      <id>copy</id>
      <phase>pre-integration-test</phase>
      <goals>
          <goal>copy</goal>
      </goals>
      <configuration>
          <artifactItems>
              <artifactItem>
                  <groupId>org.glassfish.jersey.ext.cdi</groupId>
                  <artifactId>jersey-cdi-rs-inject</artifactId>
                  <version>${jersey.version}</version>
                  <type>jar</type>
                  <overWrite>false</overWrite>
              </artifactItem>
          </artifactItems>
          <outputDirectory>${project.build.directory}/glassfish7/glassfish/modules</outputDirectory>
      </configuration>
  </execution>
```

When running the TodoResourceTests will throw the following exception.

```bash 
Oct 01, 2022 4:14:03 PM org.jboss.arquillian.container.glassfish.clientutils.GlassFishClientUtil getResponseMap
SEVERE: exit_code: FAILURE, message: Error occurred during deployment: Exception while loading the app : CDI definition failure:Exception List with 1 exceptions:
Exception 0 :
org.jboss.weld.exceptions.IllegalArgumentException: WELD-001325: No instance of an extension class org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider registered with the deployment
        at org.jboss.weld.manager.BeanManagerImpl.getExtension(BeanManagerImpl.java:1421)
        at org.jboss.weld.util.ForwardingBeanManager.getExtension(ForwardingBeanManager.java:228)
        at org.glassfish.jersey.ext.cdi1x.inject.internal.InjectExtension.beforeDiscoveryObserver(InjectExtension.java:70)
```

**Comment by OndroMih** [comment]
It looks like further integration is needed in GlassFish. I think the error means that the CDI extension [CdiComponentProvider](https://github.com/eclipse-ee4j/jersey/blob/master/ext/cdi/jersey-cdi1x/src/main/java/org/glassfish/jersey/ext/cdi1x/internal/CdiComponentProvider.java), which connects Jersey to the Bean Manager, isn't loaded. I'm not sure what is needed for that but I would start with the test project for `CdiComponentProvider`: https://github.com/eclipse-ee4j/jersey/blob/c5e71d03a02f0f79a3df451c4d325d90a5953542/tests/integration/cdi-integration/cdi-test-webapp/src/test/java/org/glassfish/jersey/tests/cdi/resources/CdiComponentProviderTest.java

Maybe @jansupol can clarify what's needed to integrate `jersey-cdi-rs-inject` into GlassFish/Weld.

**Comment by jansupol** [comment]
Odd, we have the [test working](https://github.com/eclipse-ee4j/jersey/tree/3.1/tests/integration/cdi-integration/gf-cdi-inject). Will try with M9.

**Comment by jansupol** [comment]
Still working with M9. @hantsy I suspect there is some Jersey mismatch in your local env, I have seen the message in my env when there was no OSGi header in the module (3.1.0-M7)

**Comment by hantsy** [comment]
I am using Glassfish 7.0.0.M9 and built-in Jersey, I am not sure if it is the newest version.

**Comment by hantsy** [comment]
> Odd, we have the [test working](https://github.com/eclipse-ee4j/jersey/tree/3.1/tests/integration/cdi-integration/gf-cdi-inject). Will try with M9.

In your example project, it copies the latest jeyser libs to override the default ones.

**Comment by jansupol** [comment]
> In your example project, it copies the latest jeyser libs to override the default ones.

Yes, but arguably, they are the same as in the Glassfish. Also, I added 
```
<properties>
        <jersey.version>3.1.0-M8</jersey.version>
```
So that Jersey M8 is there (exactly the same as in GF) and still works fine. But it was not clear what version of `jersey-cdi-rs-inject` you are using, the error message seems I got with M7, not with M8.

**Comment by hantsy** [comment]
I used Jersey 3.1.0-M8, https://github.com/hantsy/jakartaee10-sandbox/blob/master/pom.xml#L40

**Comment by hantsy** [comment]
I am sure it does not work till GF7 M9 when using the **original Glassfish** without overriding the built-in Jersey libs.

**Comment by arjantijms** [comment]
> Thinking about it, the HttpServletRequest bean should be provided by the Servlet implementation.

Indeed. All other specs should not provide this, unless they provide a special decorated version or so. Let's make sure we get this into the next revision of the Servlet spec (in an optional Jakarta EE environment section, so Greg and Tomcat don't have to worry about this).

**Comment by hantsy** [comment]
So, how to get it work in the current M9?

**Comment by jansupol** [comment]
Jersey 3.1.0 Final has been released. That should have been working fine.

**Comment by hantsy** [comment]
Yes, hope the next GlassFish release will include it.

**Comment by arjantijms** [comment]
Re-opening this. Unfortunately the dreaded Jersey module does 2 things:

1. Enable @Inject injection of REST artefacts
2. Enable a kind of strange Jersey specific injection of HttpServletRequest (qualified with Jersey annotation)

Item 2 happens via the following code:

class ServletReferenceProducer {
    @Inject
    InjectionManager injectionManager;

```java
    @Inject
    BeanManager beanManager;

    @Produces
    @JerseyContext
    @RequestScoped
    public HttpServletRequest produceHttpServletRequest() {
        return injectionManager().getInstance(HttpServletRequest.class);
    }
}
```

and 

```java
  private void afterDiscoveryObserver(@Observes final AfterBeanDiscovery abd, final BeanManager beanManager) {
        if (WEB_CONFIG_CLASS != null) {
            abd.addBean(new ServletReferenceProducerBean(beanManager));
        }
    }
```

Unfortunately, the TCK has this observer:

```java
    public void observeHttpServletRequestBeanAttributes(@Observes ProcessBeanAttributes<HttpServletRequest> event) {
        observedBeanAttributes.add(event);
    }
```

This is seemingly unstoppable (can't veto it, since that would be another ProcessBeanAttributes, and the order is not guaranteed).

Maybe it's a TCK error, as the TCK is supposed to check for build-in beans, and this here doesn't concern a build-in bean (but the test triggers on it nevertheless).

@jansupol 
@manovotn & @Ladicek

**Comment by manovotn** [comment]
@arjantijms does this mean that the PBA event you are observing comes with some qualifier?
Because technically, the test *could* be made to check for default qualifier only.

**Comment by manovotn** [comment]
I assume the test verifies following parts of the spec([1](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#additional_builtin_beans)):

> A Jakarta EE or embeddable EJB container must provide the following built-in beans, all of which have qualifier `@Default`:
> ...
> a bean with bean type jakarta.servlet.http.HttpServletRequest, allowing injection of a reference to the HttpServletRequest

In combination with([2](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#process_bean_attributes)):

> No [PBA] event is fired for any:
> * beans added programmatically using AfterBeanDiscovery.addBean(), or,
> * for any built-in beans.

So I'd say the TCKs should assert `@Default` qualifier with those PBA events.

**Comment by arjantijms** [comment]
> So I'd say the TCKs should assert @Default qualifier with those PBA events.

I think so too. The `@JerseyContext` qualifier is applied in this case.

**Comment by manovotn** [comment]
> > So I'd say the TCKs should assert @default qualifier with those PBA events.
> 
> I think so too. The `@JerseyContext` qualifier is applied in this case.

I've created https://github.com/jakartaee/cdi-tck/issues/474 for this.


> This is seemingly unstoppable (can't veto it, since that would be another ProcessBeanAttributes, and the order is not guaranteed).

I am thinking Weld maybe allowed you to specify priority on extensions hence enforcing ordering, I need to double check though.

**Comment by arjantijms** [comment]
> EDIT: Actually not just on Weld, TCKs have a [test](https://github.com/jakartaee/cdi-tck/blob/2.0/impl/src/main/java/org/jboss/cdi/tck/tests/extensions/observer/priority/TestExtension01.java#L30-L41) for it as well :)

Interesting! Today I Learned, thanks!

**Comment by jansupol** [comment]
@arjantijms It's the JAX-RS Spec [mandates](https://jakarta.ee/specifications/restful-ws/3.1/jakarta-restful-ws-spec-3.1.html#servlet_container) for the implementation to produce the beans for the Servlet classes (Injected by `@Context`, but in the case of this module that replaces `@Context` with `@Inject` Jersey should be able to inject those as well, so as a compromise we do not qualify using the @Default annotation). In the case Jersey is not in a Glassfish, the Servlet bean may not be provided. 

However, if you suggest any mechanism not to register the producer in Glassfish we can consider the change if not affecting our customers.

**Comment by jansupol** [comment]
> shall we try to get that removed from the REST spec?

I hope this will eventually be a part of the transition towards the CDI in the Spec. The problem was that Servlet did not produce the beans in the past, which it now does.
