### ISSUE TITLE
StructuredLogViewerResource randomly produces corrupted output

### ISSUE THREAD

**Issue by dmatej** [eclipse-ee4j/glassfish#24068]
I am not quite sure about the cause of the error as LoggingRestITest mostly passes, but sometimes fails because log records/filenames in the response are escaped. That is probably caused by these circumstances:

JSON methods of both StructuredLogViewerResource and LogNamesResource provide both JSON and PLAIN response types. Despite client (the test) asked for JSON, sometimes (only on Jenkins and still not always, "makes me maaaad!!!") produces incorrectly escaped JSON. 

The JSON response (and XML too) is produced manually in the Java code - it uses JSONObject to convert the record to a JSON string and then concatenates these strings to create JSON. Same does it with XML, but there's just single XML response type declaration.

So ... it seems to me that when the client asks for JSON, Jersey takes the string produced by the endpoint and escapes it as a JSON response (escapes all "\n\t..." characters by a backslash), because it expects that the string is an entity to be wrapped as json. Then the response cannot be parsed for some reason as a JsonObject. Example from [Jenkins](https://ci.eclipse.org/glassfish/job/glassfish_build-and-test-using-jenkinsfile/job/PR-24067/4/execution/node/365/log/):
```
LoggingRestITest.logFileNames:53 ? JSON A JSONObject text must begin with '{' at character 1 of "{\"InstanceLogFileNames\": [\"server.log\"]}\n"
```
The scary thing is that it is not reproducible. It just sometimes happens.

```
    private String convertQueryResult(List<String> files, String type) {
        StringBuilder sb = new StringBuilder();
        String sep = "";
        if (type.equals("json")) {
            sb.append("{\"InstanceLogFileNames\": [");
        } else {
            sb.append("<InstanceLogFileNames>\n");
        }

        // extract every record
        for (String name : files) {
            if (type.equals("json")) {
                sb.append(sep);
                sb.append(quote(name));
                sep = ",";
            } else {
                sb.append("<" + name + "/>");
            }
        }
        if (type.equals("json")) {
            sb.append("]}\n");
        } else {
            sb.append("\n</InstanceLogFileNames>\n");

        }
        return sb.toString();
    }

    private String quote(String s) {
        return "\"" + s + "\"";
    }
```

How to fix it? What I would do is ...

- split PLAIN and JSON response types - it is not the same.
- maybe the PLAIN text would be useful too, no JSON, no XML, just text.
- return just list of LogRecord instances (in JSONObject under the "records" key to keep API ... or in a Map), let Jersey to format it. Same for XML.

However it seems to me quite suspicious that it changes the behavior and I don't know what exactly causes it. 
Any ideas?

**Comment by pzygielo** [comment]
1. 7.0.1-BRANCH includes #24272
2. Unfortunately https://ci.eclipse.org/glassfish/job/glassfish_build-and-test-using-jenkinsfile/job/7.0.1-BRANCH/2/execution/node/187/log/
```
22:59:08  [ERROR] org.glassfish.main.admin.test.rest.LoggingRestITest.logFileNames  Time elapsed: 0.007 s  <<< ERROR!
22:59:08  org.codehaus.jettison.json.JSONException: A JSONObject text must begin with '{' at character 1 of "{\"InstanceLogFileNames\": [\"server.log_2023-01-29T21-55-44\",\"server.log\"]}\n"
22:59:08  	at org.codehaus.jettison.json.JSONTokener.syntaxError(JSONTokener.java:492)
22:59:08  	at org.codehaus.jettison.json.JSONObject.<init>(JSONObject.java:214)
22:59:08  	at org.codehaus.jettison.json.JSONObject.<init>(JSONObject.java:332)
22:59:08  	at org.glassfish.main.admin.test.rest.LoggingRestITest.readJsonObjectFrom(LoggingRestITest.java:
```
3. Maybe https://github.com/eclipse-ee4j/glassfish/pull/24270#issuecomment-1404809076 should be considered after all.

**Comment by dmatej** [comment]
I believe this cannot be in flushing. With your fix the stream is flushed before it is closed automatically. I think that Jettison is dumb and prints misleading exception. It might be some special character, Jettison is not much clever in this (CRLF, TAB?). First I would try to write simple unit tests for these cases to be sure.

**Comment by pzygielo** [comment]
It seems that in failure cases, the JSON has escaped quotes, just like it's dumped in the log:
```json
{\"InstanceLogFileNames\": [\"server.log_2023-01-29T21-55-44\",\"server.log\"]}
```
while in success case it's well-formed one:
```json
{"InstanceLogFileNames": ["server.log_2023-01-29T21-55-44","server.log"]}
```

I have no 100% reproducer yet and so I don't know why that might be.

**Comment by dmatej** [comment]
Aha, I know - the REST api is wrong, I wrote that somewhere. Then result depends on the order in iteration ... because the endpoint is same for text and json response. Refactoring can fix it (and also simplify it).

**Comment by dmatej** [comment]
Or we can fix it quickly ... https://stackoverflow.com/questions/24257314/produces-annotation-in-jax-rs
Option 1: `qs` attribute
Option 2: `@HeaderParam("accept")`
Option 3: Separate text/json/xml (I would prefer this one)
But in both cases it would be good to return text ... as text (not "something like json")
