### ISSUE TITLE
Glassfish failures with CDI, BV porting kit, CDI Model, Concurrency TCK using JDK 11

### ISSUE THREAD

**Issue by gurunrao** [eclipse-ee4j/glassfish#24085]
Latest Glassfish nightly has failures with following TCK/Porting kit and JDK 11:

-     BV porting kit with 42 failures, CI run - https://ci.eclipse.org/jakartaee-tck/job/bvtck-porting/job/master/216/ 
-     CDI TCK  with 453 failures, CI run - https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-cdi-tck-glassfish-run/28/ 
-     CDI Model TCK  with 1 failures, CI run - https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-cdi-model-tck-glassfish-run/19/
-     Concurrency TCK  with 6 failures, CI run - https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-concurrency-tck-glassfish-run/110/
Please note: same tests are passing with JDK17.

**Comment by scottmarlow** [comment]
https://github.com/eclipse-ee4j/glassfish/commit/3d6a61d3895566ed16472b5ac308b2489a722deb is a recent change that seems to be throwing the above exception from https://github.com/eclipse-ee4j/glassfish/commit/3d6a61d3895566ed16472b5ac308b2489a722deb#diff-7bc18471088ed4c778c77008fea899a56bcef8c4a1e21f7c6fa6d23dff3eb20cR99

**Comment by dmatej** [comment]
> [3d6a61d](https://github.com/eclipse-ee4j/glassfish/commit/3d6a61d3895566ed16472b5ac308b2489a722deb) is a recent change that seems to be throwing the above exception from [3d6a61d#diff-7bc18471088ed4c778c77008fea899a56bcef8c4a1e21f7c6fa6d23dff3eb20cR99](https://github.com/eclipse-ee4j/glassfish/commit/3d6a61d3895566ed16472b5ac308b2489a722deb#diff-7bc18471088ed4c778c77008fea899a56bcef8c4a1e21f7c6fa6d23dff3eb20cR99)

Nice! Ok, I will fix it yet today, thank you for the investigation!
