### ISSUE TITLE
Update Notice.md to reflect GF7+ status

### ISSUE THREAD

**Issue by dmatej** [eclipse-ee4j/glassfish#24088]
It is obsoleted, see https://github.com/eclipse-ee4j/glassfish/blob/master/NOTICE.md

**Comment by hs536** [comment]
@dmatej 
Should we only update third-party content's versions? If so, I can volunteer for it this week.

**Comment by dmatej** [comment]
> @dmatej Should we only update third-party content's versions? If so, I can volunteer for it this week.

There's much more to update in documentation etc., it would be great if you can help!
