### ISSUE TITLE
Admin Console - New JDBC Connection pool page doesn't contain list of database vendors

### ISSUE THREAD

**Issue by OndroMih** [eclipse-ee4j/glassfish#24167]
## Environment Details
* GlassFish - built from the admingui7 branch on 11 Nov 2022
* JDK version: Zulu17.36+13-CA (build 17.0.4+8-LTS)
* OS: Ubuntu 22.04.1 LTS
* Database: N/A

----------

## Problem Description

When creating a new connection pool in Admin Console, the Database Driver Vendor listbox is empty and doesn't show a list of known database Vendors. It should show the list from [dbvendor.properties](https://github.com/eclipse-ee4j/glassfish/blob/571714739b23e16c4c90d5229b806433920b3bcb/appserver/jdbc/templates/src/main/resources/glassfish/lib/install/databases/dbvendormapping/dbvendor.properties)

## Steps to reproduce

Open Admin Console, Resources, JDBC, JDBC Connection Pools, click New button. 

Current behavior:

The `Database Driver Vendor` field shows an empty listbox.

Expected behavior:

The `Database Driver Vendor` field shows a list of database vendors configured in [dbvendor.properties](https://github.com/eclipse-ee4j/glassfish/blob/571714739b23e16c4c90d5229b806433920b3bcb/appserver/jdbc/templates/src/main/resources/glassfish/lib/install/databases/dbvendormapping/dbvendor.properties)

## Impact of Issue

User experience degraded. Users need to input the name of the driver manually

[//]: # "Please choose one each Type, Component, and Priority label"

Type: bug
Component: Admin Console

**Comment by OndroMih** [comment]
This bug is introduced by https://github.com/eclipse-ee4j/glassfish/issues/23641 as I explained in this comment: https://github.com/eclipse-ee4j/glassfish/issues/23641#issuecomment-1311982378

**Comment by dmatej** [comment]
Can you write some trivial test in admin-tests module which would work with templates and which would cover this scenario? Without admin-gui, just something for asadmin - it had to affect it somehow, right?
Hmmm, but I don't see any related asadmin commands ... what do you think?

**Comment by avpinchuk** [comment]
If it is acceptable yet, I can add some test cases soon. Please do not close this issue.

**Comment by OndroMih** [comment]
> EDIT: Yet another idea - there are also rest tests, I would expect there exists some related API ...

Yes, there's a REST endpoint and asadmin command `_get-database-vendor-names` that gives the list of DB vendors. The REST endpoint is used by the Admin Console: https://github.com/eclipse-ee4j/glassfish/blob/9a68cc8076d14c77aba791fd5c955b7c7a175593/appserver/jdbc/admin/src/main/java/org/glassfish/jdbc/admin/cli/internal/GetDatabaseVendorNames.java
