### ISSUE TITLE
Empty Database Driver Vendor list in New JDBC Connection Pool

### ISSUE THREAD

**Issue by johbor** [eclipse-ee4j/glassfish#24205]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"

## Environment Details
* GlassFish Version (and build number): 6.2.3, 6.2.4, 6.2.5
* JDK version: 17
* OS: MacOS
* Database: MySQL 8.0.30

----------

## Problem Description
The dropdown list with vendor database drivers is empty.

## Steps to reproduce
Choose New in JDBC Connection Pools

## Impact of Issue
Tried to use 6.2.5 web edition but can't create a connection pool

<img width="1032" alt="Screenshot 2022-12-11 at 20 25 17" src="https://user-images.githubusercontent.com/9353297/206925517-c5c9e33f-c820-49c8-a583-fad8b0826316.png">

**Comment by dmatej** [comment]
Hi, that should be already fixed  by this: 
* https://github.com/eclipse-ee4j/glassfish/issues/24167
* https://github.com/eclipse-ee4j/glassfish/pull/24168

The fix is a part of 7.0.0-M10.

**Comment by johbor** [comment]
Thanks, but does that mean that the 6.2.x version will be fixed too?

Tested to be sure also the REST url http://localhost:4848/management/domain/resources/get-database-vendor-names

vendorNames property is empty. In version 6.2.2 it is filled with database vendor names

<img width="741" alt="image" src="https://user-images.githubusercontent.com/9353297/207003914-351da307-85f4-4e17-8757-a7e116f041dd.png">
