### ISSUE TITLE
Nested ui:repeat element miscounts

### ISSUE THREAD

**Issue by helper14** [eclipse-ee4j/glassfish#24224]
Nested ui:repeat element miscounts

## Environment Details
* GlassFish Version (and build number): glassfish-6.1.0
* JDK version: openjdk-17.0.3+7
* OS: Win10
* Database:

----------

## Problem Description
A nested ui:repeat within another ui:repeat element does add 1 to the end at each loop.

## Steps to reproduce
```
<div style="display: flex; flex-direction: row; flex-wrap: nowrap;">
    <ui:repeat begin="0" end="5" step="1" var="x">
        <div style="display: flex; flex-direction: column; flex-wrap: nowrap;">
            <ui:repeat begin="0" end="5" step="1" var="y">
                <div> [#{x}|#{y}] </div>
            </ui:repeat>
        </div>
    </ui:repeat>
</div>
```
output:

![screenshot_nested_repeat](https://user-images.githubusercontent.com/83238864/210959133-8653fb4f-3d68-4936-8e05-907f0acfbcf2.png)

## Minimal Example
[uirepeat-example.zip](https://github.com/eclipse-ee4j/glassfish/files/10359492/uirepeat-example.zip)

... a maven/netbeans-project. URL: http://localhost:8080/uirepeat-example/index.xhtml

## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"

[//]: # "Please choose one each Type, Component, and Priority label"

**Comment by pzygielo** [comment]
Please prepare [MCVE](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by helper14** [comment]
I added a minimal example project to the bug-report. It is attached too.

Regards

**Comment by pzygielo** [comment]
> I added a minimal example project

Reproduced the same with GF 7.0.0.

**Comment by pzygielo** [comment]
For me it seems to be something around https://github.com/eclipse-ee4j/glassfish/blob/be8cf0734686a7f7023c4e9c4a373d341d809a1a/impl/src/main/java/com/sun/faces/facelets/component/UIRepeat.java#L99-L114

As GF integrates [Mojarra](https://github.com/eclipse-ee4j/mojarra) - I think this issue should be transferred there, to continue discussion in the upstream. (@arjantijms @m0mus @edbratt - I'm not privileged to do that.)

**Comment by pzygielo** [comment]
> As GF integrates [Mojarra](https://github.com/eclipse-ee4j/mojarra) - I think this issue should be transferred there, to continue discussion in the upstream.

@arjantijms @m0mus @edbratt - maybe it was fixed in mojarra already?

**Comment by pzygielo** [comment]
> > As GF integrates [Mojarra](https://github.com/eclipse-ee4j/mojarra) - I think this issue should be transferred there, to continue discussion in the upstream.
> 

@arjantijms @m0mus @edbratt - maybe it was fixed in mojarra already?

**Comment by arjantijms** [comment]
I do remember something like this being addresses. @balusc

**Comment by BalusC** [comment]
Was you thinking of https://github.com/jakartaee/faces/issues/1713? Not sure if related but I haven't worked on anything else ui:repeat related recently.
