### ISSUE TITLE
Broken links in the documentation page on the website

### ISSUE THREAD

**Issue by OndroMih** [eclipse-ee4j/glassfish#24265]
# Download page link broken
 
If you visit the docs page and then access another page via the tree link on the right, the URL will have /docs/ as context and you will get 404.
1. access https://glassfish.org/
2. click "Documentation"; https://glassfish.org/documentation
3. click "Current release" link;  https://glassfish.org/docs/#current
4. click "Download" -> refer https://glassfish.org/docs/download then 404

<img src="https://user-images.githubusercontent.com/2195988/214540256-962d3657-4e7b-4ca1-b8bb-84f8816feec5.png" height="300px"/>

# Links in the "latest" docs are broken

Links from the docs page to individual pages are broken. For example, there's a broken link to https://glassfish.org/docs/latest/add-on-component-development-guide/toc.html, but the correct link should be https://glassfish.org/docs/latest/add-on-component-development-guide.html as for the snapshot docs.

**Comment by dmatej** [comment]
Yet here, the Documentation link on the right side doesn't work too: https://glassfish.org/docs/
