### ISSUE TITLE
Check goals for thread safety

### ISSUE THREAD

**Issue by pzygielo** [eclipse-ee4j/glassfish#24262]
Following goals of `config-generator`:
- `:generate-injectors`
- `:generate-test-injectors`

are used by the build and cause maven to issue warning during parallel build.

Check, and if possible mark them as being `@threadSafe`.

-----

- #24258

**Comment by dmatej** [comment]
Seems this was resolved in 7.0.5 by transformation of the maven plugin to annotation processor, see https://github.com/eclipse-ee4j/glassfish/pull/24399
