### ISSUE TITLE
Looks like the glassfish 7.0.1 release artifact contains the 7.0.0 version info

### ISSUE THREAD

**Issue by pzygielo** [eclipse-ee4j/glassfish#24284]
_Originally posted by @chenrui333 in https://github.com/eclipse-ee4j/glassfish/pull/24283_

**Comment by pzygielo** [comment]
Perhaps
```xml
        <major_version>7</major_version>
        <minor_version>0</minor_version>
        <update_version>0</update_version>
```
could be determined automatically in the build time.

**Comment by dmatej** [comment]
Arrrgh, and I reviewed it in Eclipse manually, but forgot to check this property. 
There's also ./updateVersion.sh script, it could be included into that. Just simple regexp.
Or some maven plugin, btw there's yet another bug with generating build id - it generates wrong date part (2020 in my builds).

**Comment by szarza** [comment]
The "about" button in admin web application of 7.0.1 shows :
Eclipse GlassFish 7.0.0 (build master-b160-g0b1e109 2020-12-19T17:24:00+0000)

Could it be for the same reason?

**Comment by dmatej** [comment]
> The "about" button in admin web application of 7.0.1 shows : Eclipse GlassFish 7.0.0 (build master-b160-g0b1e109 2020-12-19T17:24:00+0000)
> 
> Could it be for the same reason?

Yes, this has the same reason.
