### ISSUE TITLE
Faces WebSocket TCK test fails under questionable circumstances

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/glassfish#24280]
A seemingly unrelated code cleaning seemed to fix this, but logically it should not have.

See https://github.com/eclipse-ee4j/glassfish/pull/24279

We should investigate the real cause, and find a real fix.

**Comment by dmatej** [comment]
@arjantijms  Can you confirm it is resolved now?

**Comment by arjantijms** [comment]
@dmatej I need to retest it. Could well be that the recent websocket fixes resolved it.
