### ISSUE TITLE
GlassFish 7.0.1 does not return directories any more

### ISSUE THREAD

**Issue by andresluuk** [eclipse-ee4j/glassfish#24297]
There is a regression from GlassFish 7.0.0 into GlassFish 7.0.1
If you have code that requests a directory from the ClassLoader it fails now on exploded deploy

## Environment Details
* GlassFish Version (and build number):
* 7.0.1 release
* JDK version:
* JDK 17
* OS:
* Windows/unix

----------

## Problem Description
public class MyServletextends HttpServlet {
  protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException {
    System.out.println("found url " + getClass().getClassLoader().getResource("adirectoryname"));
  }
}
The classloader returned there is WebappClassLoader that was refactored.
It works on packaged deploy and all older GF versions.

Another place we got the same issue was from Spring:
    appContext = new GenericXmlApplicationContext();
    appContext.load("conf/*-config.xml"); -- now fails because folder conf is not found from the classpath on exploded deploy.

## Steps to reproduce
Get an instance of WebappClassLoader and try to load a directory URL from there:
getResource("somerandomdirectory")

## Impact of Issue
The biggest one would be spring that tries to load all xml-s from a directory on exploded deploy.

**Comment by dmatej** [comment]
Hi, thanks for the report, can you copy the stacktrace here?

**Comment by andresluuk** [comment]
There is no stacktrace in glassfish, a method that returned non-null returns now null.
WebappClassLoader.getResource("somerandomdirectory") on exploded deploy of the application.

Just a side note, if I request for an file that exists in classpath I will still get the file as before.

**Comment by dmatej** [comment]
Thanks, I wanted to be sure. I expect it will be fixed next week, and the next version will be released in few weeks.
