### ISSUE TITLE
Links to other guides are broken in the GlassFish 7 documentation

### ISSUE THREAD

**Issue by OndroMih** [eclipse-ee4j/glassfish#24303]
## Problem Description

A lot of links that point to other guide documents are broken in the GlassFish 7 (latest) documentation: https://glassfish.org/docs/#current

For example, a link in the Installation Guide (https://glassfish.org/docs/latest/installation-guide.html) that points to the `asadmin` section in the Reference manual is broken:

![image](https://user-images.githubusercontent.com/2195988/220465496-d11d4c9f-24ae-4ba0-8c57-41410fb1dc70.png)

because it points to https://glassfish.org/docs/latest/reference-manual/asadmin.html#asadmin instead of https://glassfish.org/docs/latest/reference-manual.html#asadmin

**Comment by dmatej** [comment]
Good you did not forget :-)

**Comment by OndroMih** [comment]
Yes, I'm working on it already ;-)
