### ISSUE TITLE
set-log-attributes issue

### ISSUE THREAD

**Issue by szarza** [eclipse-ee4j/glassfish#24312]
## Problem Description

Any log attribute set overrides the previous one. For example:

If run the following sequence in admin:

```
set-log-attributes org.glassfish.main.jul.handler.GlassFishLogHandler.file=/var/log/cestel/calypso/server.log
set-log-attributes org.glassfish.main.jul.handler.GlassFishLogHandler.rotation.maxArchiveFiles=20
```

 `org.glassfish.main.jul.handler.GlassFishLogHandler.file` remains with the default value. 

After that, if `org.glassfish.main.jul.handler.GlassFishLogHandler.file` is set, `org.glassfish.main.jul.handler.GlassFishLogHandler.rotation.maxArchiveFiles` value is back to the default value.

## Environment Details
* GlassFish Version (and build number): 7.0.1
* JDK version: 17
* OS: Linux

**Comment by dmatej** [comment]
Could it be temporarily avoided by running the command just once? At least on my machine it worked ...

On the first glance the LoggingConfigImpl seems suspicious to me ... I will take a look later.

```
set-log-attributes org.glassfish.main.jul.handler.GlassFishLogHandler.file=/var/log/cestel/calypso/server.log:org.glassfish.main.jul.handler.GlassFishLogHandler.rotation.maxArchiveFiles=20
```
