### ISSUE TITLE
Glassfish interface stuck while changing server configuration

### ISSUE THREAD

**Issue by rosshkaa** [eclipse-ee4j/glassfish#24339]
## Environment Details
* GlassFish Version (and build number): 7.0.2 (build master-b41-g3aab03d)
* JDK version:  "17.0.5" GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
* OS: Windows 10

----------

## Problem Description
Got a new glassfish build, just unpacked it from the archive, there are no deployed applications.
Trying to switch JMS broker from embedded to local.
Went to localhost:4848, Configurations tab / server-config / Java Message Service.
After changing JMS Service Type from "EMBEDDED" to "LOCAL" and hitting "Save" button page shows message "A long-running process has been detected. Please wait..." for what seems like an infinite time.
Tried to wait up to 10 minutes, nothing changes, message is still there.

Same thing is happening while changing Logger Settings: switching from General tab to Log Levels tab shows the same message and the page is stuck. 

There is no log entries bound to the problem, last entry is " Admin Console: Initializing Session Attributes...".
Page can be reloaded, but the settings are unchanged.
Server restart doesn't help.

## Steps to reproduce
1. Download and unpack [latest release ](https://github.com/eclipse-ee4j/glassfish/releases/tag/7.0.2).
2. Start glassfish with asadmin start-domain.
3. Open localhost:4848 in any browser.
4. Go to Configurations tab / server-config / Java Message Service.
5. Select "LOCAL" at JMS Service Type list, click "Save" button.

Type: Bug
Priority: Annoying

**Comment by avpinchuk** [comment]
@rosshkaa, I cannot reproduce the problem. All works. Win 10, Liberica JDK 17.0.5

**Comment by avpinchuk** [comment]
I tried also GraalVM CE 22.3.0 - it's work too.

**Comment by dmatej** [comment]
What I did now:

```
mvn org.apache.maven.plugins:maven-dependency-plugin:3.1.2:get -Dartifact=org.glassfish.main.distributions:glassfish:7.0.2:zip -Dtransitive=false
cp /home/dmatej/.m2/repository/org/glassfish/main/distributions/glassfish/7.0.2/glassfish-7.0.2.zip ./
unzip glassfish-7.0.2.zip
export AS_JAVA=/usr/lib/jvm/jdk17
AS_JAVA=/usr/lib/jvm/jdk17
./glassfish7/bin/asadmin start-domain --debug
```

Then 
* I went to http://localhost:4848
* server-config > Java Message Service
* JMS Service Type changed to LOCAL
* Save

Logging:
```
[2023-03-15T10:43:23.812701+01:00] [GlassFish 7.0] [INFO] [] [org.glassfish.admingui] [tid: _ThreadID=206 _ThreadName=admin-listener(6)] [levelValue: 800] [[
Admin Console: Initializing Session Attributes...]]

[2023-03-15T10:47:41.145365+01:00] [GlassFish 7.0] [WARNING] [] [] [tid: _ThreadID=214 _ThreadName=pool-26-thread-1] [levelValue: 900] [[
Unprocessed event : UnprocessedChangeEvent{PropertyName=type, OldValue = EMBEDDED, NewValue = LOCAL, Source = GlassFishConfigBean.com.sun.enterprise.connectors.jms.config.JmsService}, reason = restart required, when = 1678873661144]]
```

Screen:
![image](https://user-images.githubusercontent.com/302904/225272208-adc8da4a-de3f-4221-820e-e1a9f7e69722.png)

Then I executed asadmin restart-domain, and verified the value is still set. My JDK:
```
openjdk version "17.0.4.1" 2022-08-12
OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)
```

**Comment by dmatej** [comment]
Which browser do you use?
