### ISSUE TITLE
Enterprise Beans deployment error

### ISSUE THREAD

**Issue by avpinchuk** [eclipse-ee4j/glassfish#24354]
## Environment Details
* GlassFish Version (and build number): 7.0.3-SNAPSHOT
* JDK version: Liberica JDK 17.0.6
* OS: Windows 10, Ubuntu 22.04
* Database: None

----------

## Problem Description

A next deployment error may occurs under some circumstances when we try to deploy an `ejb-jar`, `ear` or `war` application:

![image](https://user-images.githubusercontent.com/57197113/227778900-433c0245-896e-48c2-b771-5ba18073050a.png)

The `server log` contains next traces:

![image](https://user-images.githubusercontent.com/57197113/227778989-930514fd-5a0c-4270-b856-6faa78af2d26.png)
![image](https://user-images.githubusercontent.com/57197113/227779004-1927e902-ac61-415a-80e1-b4543138ef1f.png)

This may happens where next conditions are met:

1. An application contains Session Bean doesn't have the no-arg constructor,
2. This Session Bean have a CDI bean constructor annotated with `@Inject`, and
3. This Session Bean have an one or more "regular" constructors with parameters one or more of them have a primitive type.

## Steps to reproduce

A reproducer can be downloaded here: https://github.com/avpinchuk/reproducer-gf-ejb-deployment-error

## Impact of Issue
Application deployment failed.

**Comment by pzygielo** [comment]
> This may happens where next conditions are met:
> 
>     1. An application contains Session Bean doesn't have the no-arg constructor,
> 
>     2. This Session Bean have a CDI bean constructor annotated with `@Inject`, and
> 
>     3. This Session Bean have an one or more "regular" constructors with parameters one or more of them have a primitive type.
> 

Unclear. https://jakarta.ee/specifications/enterprise-beans/4.0/jakarta-enterprise-beans-spec-core-4.0.html#session-bean-class says

> The following are the requirements for the session bean class:
> -   The class must have a public constructor that takes no parameters. The Enterprise Beans container uses this constructor to create instances of the session bean class.

**Comment by avpinchuk** [comment]
@pzygielo, this is a CDi-related requirement.

According to https://jakarta.ee/specifications/enterprise-beans/4.0/jakarta-enterprise-beans-spec-core-4.0.html#a195, an Enterprise Beans packaged into a CDI bean archive is considered a CDI-enabled beans.

According to https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#instantiation_ee and https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#instantiation, container must call annotated constructor or no-arg constructor.

Finally, requirements for CDI beans are https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#what_classes_are_beans:

> It has an appropriate constructor - either:
> * the class has a constructor with no parameters, or
> * the class declares a constructor annotated @Inject.

Both specifications doesn't prohibit explicitly additional parameterized constructors.

**Comment by pzygielo** [comment]
I'm no EJB nor CDI expert so it's possible I'm wrong.
Thus I want to understand the case.

[ExampleBean.java](https://github.com/avpinchuk/reproducer-gf-ejb-deployment-error/blob/master/src/main/java/org/example/ExampleBean.java) is EJB Stateless.

> According to https://jakarta.ee/specifications/enterprise-beans/4.0/jakarta-enterprise-beans-spec-core-4.0.html#a195, an Enterprise Beans packaged into a CDI bean archive is considered a CDI-enabled beans.

So such Beans are still Enterprise Beans, right?

https://jakarta.ee/specifications/enterprise-beans/4.0/jakarta-enterprise-beans-spec-core-4.0.html#session-bean-class:
> The class must have a public constructor that takes no parameters.
>
> The class may have an additional constructor annotated with the Inject annotation

This sounds like having public no-arg constructor is mandatory.


> Finally, 

It's hard for me to go to the final step while I don't see initial requirement to be met.

> one of requirement for CDI beans are https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#what_classes_are_beans:
> 
> > It has an appropriate constructor - either:
> > 
> > * the class has a constructor with no parameters, or
> > * the class declares a constructor annotated @Inject.
> 

> Both specifications doesn't prohibit explicitly any number of additional constructors with parameters.

But EJB requires no-arg one.

**Comment by dmatej** [comment]
It seems Alexander's previous PR passes all TCK tests, so it seems it is alright (it did not finish yet): https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/10.0.x/

**Comment by avpinchuk** [comment]
@pzygielo, direct quotes from latest CDI spec:

> When running in Jakarta EE, the container must extend the rules defined for managed beans
> in [Injection using the bean  constructor](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#instantiation) to **EJB 
> session beans**.

This rules says:

> When the container instantiates a managed bean with a **constructor annotated @Inject**, the container calls this constructor, 
> passing an injectable reference to each parameter. If there is **no constructor annotated @Inject**, the container calls the 
> **constructor with no parameters**.

**Comment by avpinchuk** [comment]
@pzygielo, try to comment `public ExampleBean(int i) { }` in reproducer, and left only single constructor annotated with @Inject - all works in current (non-patched) version of GF. I doesn't change this behavior.

**Comment by avpinchuk** [comment]
@pzygielo, I'll try to explain how I understand it.
The EJB spec requires a no-arg constructor. At the same time the CDI spec requires EJB beans to conform to its definition of Managed Bean.  This definition implies, among other things, the requirement to have a choice between the no-arg and an annotated constructor.
I agree, the specs are unclear.
