### ISSUE TITLE
Could not initialize class org.slf4j.MDC

### ISSUE THREAD

**Issue by zistrong** [eclipse-ee4j/glassfish#24379]
## Environment Details
* GlassFish Version (and build number): 7.0.3
* JDK version: Open JDK 17
* OS: windows10
* Database: postgresql

----------

## Problem Description
throw a classdeffounderror when use slf4j
![image](https://user-images.githubusercontent.com/4328187/232662558-8cb1ac9b-9c46-4026-8fd3-8d92f91a4c97.png)

**Comment by OndroMih** [comment]
Where did you place the slf4j-api class? Is it in your application, or is it in lib or lib/ext directory? If you placed libraries in `lib/ext` directory, you have to move them to the `lib` directory. The extension mechanism for `lib/ext` directory doesn't work in Java 17 (it was removed in Java 9).

**Comment by dmatej** [comment]
I believe it duplicates #24138 . The problem is that GF uses SLF4J1 and it is mandatory because of xmlsec.
