### ISSUE TITLE
Release and integrate new versions of jsf-templating and woodstock

### ISSUE THREAD

**Issue by OndroMih** [eclipse-ee4j/glassfish#24437]
To fix https://github.com/eclipse-ee4j/glassfish/issues/24434 in GlassFish, a new version of jsf-templating (with https://github.com/eclipse-ee4j/glassfish-jsftemplating/pull/91) and a new version of woodstock (with https://github.com/eclipse-ee4j/glassfish-woodstock/pull/1438) need to be released and integrated into GlassFish.

A new version of woodstock (with https://github.com/eclipse-ee4j/glassfish-woodstock/pull/1439) would be nice also in relation to https://github.com/eclipse-ee4j/glassfish/pull/24432. Without it, Admin console shows only text without a progress icon if it takes a long time to get the status of remote instances. But this is just a small cosmetic issue, no big deal.

**Comment by arjantijms** [comment]
JSFTemplating 4.0.2 staged: https://jakarta.oss.sonatype.org/content/repositories/staging/org/glassfish/jsftemplating/jsftemplating-dt/4.0.2/
