### ISSUE TITLE
Move the suntheme module from the Woodstock repository into the GlassFish main repository (was "Remove the community-theme module")

### ISSUE THREAD

**Issue by OndroMih** [eclipse-ee4j/glassfish#24435]
## Environment Details
* GlassFish Version (and build number): 7.0.4 (and master branch)

----------

## Problem Description

<s>There's the `appserver/admingui/community-theme` module, which looks like an abandoned effort to create an alternative Admin Console theme.

We should remove this module to clean up the source code. 
</s>

We <del>could also</del> <ins>should</ins> move the suntheme module from the [Woodstock](https://github.com/eclipse-ee4j/glassfish-woodstock/tree/master/woodstock-webui-jsf-suntheme) repository into the GlassFish main repository so that it's easier to modify the theme and Admin Console together if needed. 

## Reasoning

* <del>I don't see it used anywhere: https://github.com/search?q=repo%3Aeclipse-ee4j%2Fglassfish%20community-theme&type=code</del>
* <del>I didn't find it in the GlassFish Server installation either</del>

<del>Currently, the suntheme from the [Woodstock](https://github.com/eclipse-ee4j/glassfish-woodstock/tree/master/woodstock-webui-jsf-suntheme) repository is used for Admin Console. 
</del>

<ins>Woodstock and suntheme aren't supposed to be used outside of GlassFish and it's simpler to have the theme with the rest of the Admin Console code.</ins>

## Impact of Issue

* Type: cleanup task
* Component: Admin Console
* Priority: low

**Comment by pzygielo** [comment]
> 
>     * I didn't find it in the GlassFish Server installation either
> 

What about that: `glassfish/modules/console-community-branding-plugin.jar`?

**Comment by OndroMih** [comment]
You're correct, @pzygielo , thank you for correcting me. When I remove that module in GF installation, Admin Console is broken. But I think we should still move suntheme to the main GlassFish repository to make it easier to modify the theme, so I modified this task to reflect that.

**Comment by pzygielo** [comment]
I'd rather close this issue and open new for moving suntheme than keep "was..." in the title and all that deletions in description.

**Comment by OndroMih** [comment]
OK, here it is: https://github.com/eclipse-ee4j/glassfish/issues/24495
