### ISSUE TITLE
GLASSFISH -4 Unable to update http port. Server shut down.

### ISSUE THREAD

**Issue by rlawnsxo13** [eclipse-ee4j/glassfish#24445]
## Environment Details
* GlassFish Version (and build number):
* JDK version:1.8.0.21
* OS: windows11 pro
* Database: Oracle
----------

## Problem Description

Unable to update http port. Server shut down.
Failed to save to
org.eclipse.core.runtime.CoreException: L/Servers/GlassFish 4 [domain1].server

**Comment by OndroMih** [comment]
Hello, @rlawnsxo13, can you please explain what you were doing and what happened? It's not possible to give you an advice or a fix an issue with GlassFish with this information. Thanks.

**Comment by dmatej** [comment]
Sorry, but GlassFish 4 is not a release of Eclipse GlassFish, but of it's predecessor Oracle GlassFish, which was maintained by Oracle. Can you reproduce it with GlassFish 7.0.5 and tell us how to reproduce the behavior? We have to close the issue otherwise.
