### ISSUE TITLE
Arbitrary string reported as timestamp by `version` command

### ISSUE THREAD

**Issue by pzygielo** [eclipse-ee4j/glassfish#24461]
## Environment Details
* GlassFish Version (and build number):
```
$ ./glassfish/bin/asadmin version
Version string could not be obtained from Server [localhost:4848].
(Turn debugging on e.g. by setting AS_DEBUG=true in your environment, to see the details.)
Using locally retrieved version string from version class.
Version = Eclipse GlassFish 7.0.5 (branch: master, commit: 7b49f4eaf669e9a3b4f4648254f9016872455236, timestamp: 2023-04-02T15:44:03Z)
Command version executed successfully.
```
* JDK version:
```
openjdk version "17.0.7" 2023-04-18
OpenJDK Runtime Environment (Red_Hat-17.0.7.0.7-4.fc37) (build 17.0.7+7)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.7.0.7-4.fc37) (build 17.0.7+7, mixed mode, sharing)
```
* OS: n/a
* Database: n/a

----------

## Problem Description

After
- https://github.com/eclipse-ee4j/glassfish/pull/24366

we're getting reports like this one:
- https://github.com/eclipse-ee4j/glassfish/issues/24459:

> Environment Details
>
>    GlassFish Version (and build number): 7.0.5 (branch: master, commit: https://github.com/eclipse-ee4j/glassfish/commit/7b49f4eaf669e9a3b4f4648254f9016872455236, timestamp: 2023-04-02T15:44:03Z)

The reported timestamp is not commit date, is not author date, is not build date, is not release date. It's just a string that looks like some date. I (again) propose to drop it completely from version string. This was also noted in https://github.com/eclipse-ee4j/glassfish/pull/24366#issuecomment-1493433836
> After we merge this PR, we simply have to remove also all usages from properties and the code, because it provides false information and is worthless.

but it seems it was not executed.

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"
1. unpack GF 7.0.5
2. execute `$ ./glassfish/bin/asadmin version` and check the output

## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"
It confuses me.

[//]: # "Please choose one each Type, Component, and Priority label"

**Comment by dmatej** [comment]
Yes, the timestamp and probably branch too should be removed. That is exactly why I opposed so much to those changes, but it seems they are inevitable.

**Comment by pzygielo** [comment]
- As the first step - https://github.com/eclipse-ee4j/glassfish/pull/24463
