### ISSUE TITLE
EJB Container initialization error

### ISSUE THREAD

**Issue by mheydem** [eclipse-ee4j/glassfish#24488]
A problem with EJB injection since Glassfish 7.0.4 was filed in the arquillian project:
arquillian/arquillian-core#492
But it seems like the problem is actually located in Glassfish.

**Comment by OndroMih** [comment]
It looks like an EJB proxy generated by ASM is not generated correctly. The VerifyError with message "Stack size too large" is nicely described here: https://stackoverflow.com/a/15270890/784594. This post has a code example what should be changed to fix the error: https://stackoverflow.com/a/23490448/784594.

I'm not sure what changed in GF 7.0.4 but one of these PRs is likely related to this:
* [Refactor the Enterprise Beans no-interface view bytecode generation](https://github.com/eclipse-ee4j/glassfish/pull/24363)
* [Integrate EclipseLink ASM 9.5.0](https://github.com/eclipse-ee4j/glassfish/pull/24378)

**Comment by OndroMih** [comment]
@avpinchuk , can you check if it might be caused by your PR https://github.com/eclipse-ee4j/glassfish/pull/24363?

**Comment by avpinchuk** [comment]
@OndroMih, certainly
