### ISSUE TITLE
can not create a New Resource Adapter Config from admin console

### ISSUE THREAD

**Issue by jicai** [eclipse-ee4j/glassfish#24483]
can not create a **New Resource Adapter Config** from admin console

## Environment Details
* GlassFish Version (and build number):Eclipse GlassFish 7.0.6
* JDK version:java version "17.0.7" 2023-04-18 LTS
* OS:Linux version 5.14.0-284.11.1.el9_2.x86_64
* Chrome:114.0.5735.199

----------

## Problem Description
I deployed a resource adapter through the admin console，and then I want to create a **Resource Adapter Config**，but when i select my Resource Adapter Name from the console，the page will become blank。
This issue does not exist in Payara。
![1](https://github.com/eclipse-ee4j/glassfish/assets/3412794/60bf0e87-47ea-4f50-ad1f-f1c7272f98b6)

![2](https://github.com/eclipse-ee4j/glassfish/assets/3412794/dbf18490-97e2-4a6c-ba0c-3b2c7c5ff476)

![3](https://github.com/eclipse-ee4j/glassfish/assets/3412794/778e238a-9654-4e9f-b1f4-ce69c654992b)

**Comment by avpinchuk** [comment]
Hmm, Atremis RA uses old `javax.*` namespace. Your application works? Try create RA config with `asadmin` command.
