### ISSUE TITLE
Admin Application Monitoring failed when select application or component

### ISSUE THREAD

**Issue by ArtisansADomicile01** [eclipse-ee4j/glassfish#24492]
## Environment Details
* GlassFish Version (7.0.5 and 7.0.6):
* JDK version: 17.0.7
* OS: Windows 10 / Linux

----------

## Problem Description
Activate monitoring service to LOW for all components
Go to Server / Monitor / Application or Server
Select Application or Components display a blank page

**Comment by avpinchuk** [comment]
This is fixed in eclipse-ee4j/glassfish-jsftemplating#93. This issue go away when we include new version of the JSFTemplating in GF.

**Comment by arjantijms** [comment]
I'll stage a new version of jsftemplating. 

(I do wonder if we should not include both jsftemplating and Woodstock in the admin console module inside GF, as to my knowledge nothing else uses these projects)

**Comment by avpinchuk** [comment]
Fixed by #24494.
