### ISSUE TITLE
Can't deploy app with remotely accessible bean to embedded glassfish - IllegalArgumentException xxx_Remote referenced from a method is not visible from class loader

### ISSUE THREAD

**Issue by Blavo** [eclipse-ee4j/glassfish#24521]
Can't deploy a very simple web application with a remotely-accessible bean to a running embedded glassfish instance; attempt gives an IllegalArgumentException with message '<interface name>_Remote referenced from a method is not visible from class loader'.

## Environment Details
Glassfish 7.0.6 embedded

java version "17.0.7" 2023-04-18 LTS
Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.7+8-LTS-224, mixed mode, sharing)

MacOS 12.4 (Monterey)

Database n/a

----------

Created a very simple web app with a single remotely accessible bean with one method. Deployed the app to a running non-embedded glassfish 7.0.6 successfully. Ran an SE client that looks the bean up (rather than an enterprise client that injects the bean). Successfully got a reference to the bean and accessed the bean's method.

Created another SE client that successfully starts glassfish 7.0.6 embedded and attempts to deploy the same app war prior to looking up and accessing the bean as above. Deploy fails as described. Deploy should succeed allowing the bin to be looked up and accessed. 

Problem is reliably reproducible with this and two other apps.

Stack trace and program output attached.

## Steps to reproduce
1. Compile attached RemoteCalculatorInterface.java as a class library; no library JARs required
2. Compile attached RemoteCalculatorBean as a glassfish 7 web app; requires library JARs as per in-code documentation
3. Deploy web app to a running glassfish 7 server; deploy works. 
4. Compile and run the attached GF7EmbeddedDeployReproducerRemoteClient as a Java application; requirements are documented in the code; works fine showing that the deploy worked and that bean lookup and the bean work
5. Shut down the running glassfish 7 server to prevent conflicts with the embedded server to be run in the next step
6. Compile and run the attached GF7EmbeddedDeployReproducerEmbeddedClient as a Java application; requirements are documented in the code; deploy fails as described

## Impact of Issue
16,000 man-hour project being upgraded from Java 8 / glassfish 6 / Netbeans 8 to Java 17 / glassfish 7 / Netbeans 18. This is almost a development stopper.

[Stack trace.txt](https://github.com/eclipse-ee4j/glassfish/files/12189850/Stack.trace.txt)
[GF7EmbeddedDeployReproducerEmbeddedClient.txt](https://github.com/eclipse-ee4j/glassfish/files/12190052/GF7EmbeddedDeployReproducerEmbeddedClient.txt)
[GF7EmbeddedDeployReproducerRemoteClient.txt](https://github.com/eclipse-ee4j/glassfish/files/12190053/GF7EmbeddedDeployReproducerRemoteClient.txt)
[RemoteCalculatorBean.txt](https://github.com/eclipse-ee4j/glassfish/files/12190054/RemoteCalculatorBean.txt)
[RemoteCalculatorInterface.txt](https://github.com/eclipse-ee4j/glassfish/files/12190055/RemoteCalculatorInterface.txt)

**Comment by Blavo** [comment]
Most mentions of 'IllegalArgumentException xxx_Remote referenced from a method is not visible from class loader' seem to revolve around one class being in multiple JARs in the class path. This is true here - the RemoteCalculatorInterface class is present in the war being deployed and in the class path of the GF7EmbeddedDeployReproducerEmbeddedClient deploying the war. This seems more or less inescapable - the class has to be present in the web app compilation class path to make the war and in the client class path to handle the looked up bean interface.

The specific class referenced in the IllegalArgumentException stack trace is reproducerInterfaces._RemoteCalculatorInterface_Remote which is obviously based on the replicated interface class but appears to be a glassfish created class.

**Comment by avpinchuk** [comment]
I think, this [commit](https://github.com/eclipse-ee4j/glassfish/commit/87848439e31b3552fc5c6c5f6bceb131cbbf811d) are source of this issue

**Comment by avpinchuk** [comment]
Hi, @Blavo.

Please try as temporary workaround these steps:

1. Remove `@Remote` annotation from bean
2. Add `@Remote` annotation to remote interface

**Comment by Blavo** [comment]
G'day,

I tried firstly removing @Remote from the bean and putting @Remote in the interface class. I had to include jakarta.ejb-api-4.0.1.jar in the class path for the interface class to get it to compile. When the web app ran the portable JNDI name for the remote interface had changed so I had to modify the lookup string in both the non-embedded and embedded clients. I also had to add jakarta.json-1.0.4.jar to the class path for the embedded client. Both now fail with an Underflow in BufferManagerReadStream doing the lookup. (Previously the non-embedded client worked, so this was a backward step).

Then I removed @Remote from the remote interface as well (and jakarta.ejb-api-4.0.1.jar from the class path). This portable JNDI name for the remote interface didn't change any further. Again both clients failed with an Underflow in BufferManagerReadStream doing the lookup.

**Comment by dmatej** [comment]
@avpinchuk  Are we able to create a test reproducer for this?

**Comment by dmatej** [comment]
> I think, this [commit](https://github.com/eclipse-ee4j/glassfish/commit/87848439e31b3552fc5c6c5f6bceb131cbbf811d) are source of this issue

I think it should not be, but it is related. This commit directly resolves similar issues when GlassFish could worked well on JDK11, but failed on JDK17, which has strict rules about generated classes.

**Comment by avpinchuk** [comment]
@dmatej, I'll try fix it today.

This happens because generated remote interface loaded by System CL with MH.Lookup. Rest part of EJB code loaded by WebappCL(as example) and have no access to generated remote interface.

My idea - compare runtime package of anchor class with runtime package, defined in CL that load an app. If they same - load with MH.Lookup, else - with one of CL.define() methods.

**Comment by avpinchuk** [comment]
I did some checks. At first glance it works ;)

**Comment by avpinchuk** [comment]
Yet another remark. When we package reproducer (remote interface and bean) as EJB-JAR - all works, when as a EAR or WAR - not.

**Comment by avpinchuk** [comment]
> @avpinchuk Are we able to create a test reproducer for this?

Yes, but I need help how to integrate embedded GF in current test structure ;)

**Comment by dmatej** [comment]
> > @avpinchuk Are we able to create a test reproducer for this?
> 
> Yes, but I need help(or example) how to integrate embedded GF in current test structure ;)

I would say that we can simply write tests directly in the embedded gf module, they just have to be ITests.
Embedded had bit limited classloading, but I did not use it so intensively for several years, so I forgot details... but if we would be able to improve it, it would be really awesome.

**Comment by OndroMih** [comment]
> > > @avpinchuk Are we able to create a test reproducer for this?
> > 
> > 
> > Yes, but I need help(or example) how to integrate embedded GF in current test structure ;)
> 
> I would say that we can simply write tests directly in the embedded gf module, they just have to be ITests. Embedded had bit limited classloading, but I did not use it so intensively for several years, so I forgot details... but if we would be able to improve it, it would be really awesome.

I agree with @dmatej, we can create a test suite directly in the https://github.com/eclipse-ee4j/glassfish/tree/master/appserver/extras/embedded/tests module. There's already one test to get you started. 

You can use https://github.com/eclipse-ee4j/glassfish/blob/master/nucleus/common/scattered-archive-api/src/main/java/org/glassfish/embeddable/archive/ScatteredArchive.java#L237 to assemble a test app to run with GF Embedded. Here's a code snippet with an example how to use it with GF Embedded: https://github.com/eclipse-ee4j/glassfish/releases/tag/7.0.4

**Comment by Blavo** [comment]
G’day,

In relation to:

"This happens because generated remote interface loaded by System CL with MH.Lookup. Rest part of EJB code loaded by WebappCL(as example) and have no access to generated remote interface.
My idea - compare runtime package of anchor class with runtime package, defined in CL that load an app. If they same - load with MH.Lookup, else - with one of CL.define() methods."


There might be a bit more to this than meets the eye.

My application depends on dynamic class loading so I have more familiarity with class loaders than some. My application also works with dynamic RMI and RMI has its own ways of dealing with class loaders which I’ve had to work with. So I appreciate that this is not an easy issue to work.

Now I understand that each application in glassfish has its own class loader for isolation. I also understand that glassfish itself needs to work with the system class loader. As a result care is needed which loader loads new classes. And I can see from the work you have done to date that generated classes are being loaded by the SCL but looked for in the WACL. And I understand your solution is to load these generated class with the WACL.

But, if I remember correctly, RMI within glassfish uses the system class loader. Again, if I remember correctly, this is to do with codebases. 

(To refresh your memory. If the parameter of a remotely-invocable method is an interface then the interface definition is all that needs to be in the server class path for the server code to compile. But at run time the client may pass a concrete class that implements the interface but isn’t in the server’s class path so won’t deserialise. Sun got around this (and I am regularly impressed how much vision the early Java developers had) with codebases. A codebase is a set of class definitions (a list of JARs and/or directories of .class files) published by the application or its owners and referenced by the server. If the concrete class definition is in the codebase specified to glassfish, the class definition will be found and the concrete class will deserialise. But codebase specification is done at the JVM level and codebases are accessed via the RMI class loader which is on the system class loader side, not the application class loader side. 

So, I’m not sure your solution of changing where the generated class gets loaded is going to work with codebases.

**Comment by Blavo** [comment]
G’day,

Another thought.

This issue was introduced by glassfish 7.

In glassfish 6 I would be pretty confident that the generated classes were loaded by the system class loader, for the reasons I mentioned about codebases. So the generated classes have probably always been inaccessible from the web application class loader.

So why do we now test whether the generated classes are visible to the web application class loader ? Why was the test that is now failing introduced ? Rather than change how the generated classes are loaded (which I think won’t work with codebases) can we simply not make the test for generated classes.

**Comment by avpinchuk** [comment]
Hi, we ensure that generated remote interfaces loaded by GF app classloader, not the system CL. This give visibility of these interfaces by rest of application classes.

At least, reproducer from this issue works

**Comment by avpinchuk** [comment]
GF generates remote interfaces twice - once for web app (and loaded by webapp CL), and once for you "client" part (loaded by system CL)

**Comment by avpinchuk** [comment]
Please, try with this:

https://ci.eclipse.org/glassfish/job/glassfish_build-and-test-using-jenkinsfile/job/PR-24566/3/artifact/embedded/glassfish-embedded-all.jar

**Comment by Blavo** [comment]
G’day,

That worked.

I was able to remove pfl-basic and jakarta-gson JARs from the class path of the reproducer as well.

I have yet to try with a codebase. That requires a bit more work. I’ll get back to you on that.

**Comment by Blavo** [comment]
G’day,

I am having trouble deciding whether the fix works with a codebase or not.

In the non-embedded case (ie against a running glassfish server) if you don’t set a SecurityManager in the client then the RMI class loader is disabled and what is needed from the codebase for the bean call won’t be loaded. But the message is quite clear: a ClassNotFoundException thrown by the bean call in the client with the text saying “no security manager: RMI class loader disabled”.

With a SecurityManager the bean calls work (but then they always did.)

In the embedded case if I set a SecurityManager in the client I start getting security issues immediately after. So I set the SecurityManager immediately prior to calling the bean (ie as late as possible). But the program still fails on security issues. I have set up a policy file for both the (embedded) server and the client but haven’t found a way to stop these issues yet.

If I don’t set a SecurityManager then the class I need from the codebase isn’t loaded. But the message is different from the non-embedded case above. This time it is a MarshalException saying that it could not load a class (which is the one that has to be obtained from the codebase). There is no mention of the RMI class loader being disabled.

So it is not clear whether a SecurityManager is needed in embedded mode or not.

Anyway, I’ll keep trying to resolve the security issues. But it may take a day or two - I spent most of the day on this today but I have other things I need to do for the next two days.

**Comment by dmatej** [comment]
Just a note - https://snyk.io/blog/securitymanager-removed-java/ will be removed in Java 21 and we will start to work on GF8 soon. What you describe sounds like some side effect of a bug related to the security manager.

**Comment by Blavo** [comment]
G’day,

Indeed I am painfully aware that SecurityManager has been deprecated.

One of the JEE features that the article mentions that still relies on SecurityManager is the RMI codebase feature. This allows an RMI server or client to dynamically look up concrete class definitions it needs when presented with an interface as an RMI method parameter or output type. The feature is disabled if a SecurityManager isn’t in effect. This is one of the dependencies JEP 411 will have to deal with.

**Comment by Blavo** [comment]
G’day,

I have at last resolved my SecurityManager issues and confirmed that the fix works with the codebase feature. Well done.

**Comment by avpinchuk** [comment]
@Blavo, thank you for feedback!
