### ISSUE TITLE
Glassfish server does not support multi-release JARs in WARs (if any)

### ISSUE THREAD

**Issue by shashank2337** [eclipse-ee4j/glassfish#24526]
## Environment Details
* GlassFish Version (and build number): 7.0.6
* JDK version: 17
* OS: Suse Linux 12.5
* Database: Not Applicable

----------

## Problem Description
Since Java 9 there are Multi-Release JARs ([MRJARS](https://openjdk.java.net/jeps/238)) that allow different classes for different Java versions to be included in one JAR file. I was surprised when a Glassfish 7.0.6 running on Java 17 executed Java-8-code in a JAR included in a WAR although the JAR was a MRJAR with code for Java 17.

## State if the problem is easily reproducible or happens intermittently
The problem is easily reproducible when a war is created having below dependency.
<dependency>
    <groupId>org.glassfish.jersey.ext</groupId>
    <artifactId>jersey-spring6</artifactId>
    <version>3.1.3</version>
</dependency>

## Impact of Issue
Our applications are not working after migrating to Jakarta EE 10. Dependencies mapped with @Autowired annotation failed to inject.

**Comment by arjantijms** [comment]
Thanks for the report. A while ago I briefly used multi-release JARs inside GlassFish itself, and that worked at least. We'll have to check why it wouldn't work in a war then.

**Comment by avpinchuk** [comment]
I fix this soon
