### ISSUE TITLE
Clients cannot list java:global to discover GF7 EJBs  - java.rmi.MarshalException

### ISSUE THREAD

**Issue by Blavo** [eclipse-ee4j/glassfish#24522]
An attempt by a stand alone client to list the java:global naming context with a glassfish 7 server running and having entries in that naming context fails with a java.rmi.MarshalException.

## Environment Details
Glassfish 7.0.6
java version "17.0.7" 2023-04-18 LTS
Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.7+8-LTS-224, mixed mode, sharing)
Mac OS 12.4 Monterey
Database not applicable

## Problem Description
A stand alone client should be able to discover the remotely accessible services (EJBs) of a remote glassfish server with an intent to invoke them. It does this by using the list() method of InitialContext against the java:global naming context. This should return a naming enumeration of the sub contexts of java:global. The client should be able to drill down into the sub contexts with further list() calls to discover the remotely accessible services available. It should then be able to lookup() a specific service to get a proxy through which it can invoke the methods of the remote service.

Prior to the removal of the MEJB management bean in EE 9 such a list() attempt on java:global failed because the MEJB bean in the server was not serialisable. (That fact should be irrelevant because the contract of the naming context list() method does not require the MEJB bean to be returned to the remote caller - only a list of naming sub contexts are to be returned.) This failure prevented discovery of the remotely-accessible services because they are listed under server-specific sub contexts of java:global and the list() of java:global is the only way for the remote client to discover such server-specific sub context names. This failure foils the intent of then drilling down into that sub context with sub context list() calls until leaf services are discovered).

With the removal of the MEJB bean at EE 9 the behaviour of the list() call has changed to be a java.rmi.MarshalException.

Based on experience with payara 6 I suspect that the java.rmi.MarshalException is still caused by non-serialisability but this time of a naming proxy referenced by a sub context entry in java:global. (The same deal applies - this lack of serialisability should be irrelevant, as above). 

The problem is reliably reproducible.

In glassfish 6 the problem only occurred if, in the client, during set up of the naming context used in the lookup, the server IP address and service port were given. If no server IP address was given the list() call worked. But if a server IP address was given, even if 127.0.0.1, the list() would fail. Since an IP address is necessary for a remote list() call this didn't help.

## Steps to reproduce
Compile and run the attached GFLookupReproducer meeting the requirements given in the code preamble.

## Impact of Issue
I am working on the next generation of performance testing tool. One of its features is the ability to test servers through their remotely accessible services. A pre-requisite to this is the ability to discover those services. Currently target servers have to implement a work around (that I provide) to replicate and passivate the java:global naming context in such a way that there are no non-serialisable leaf entries in the new naming context and my tool can safely list it. This work around is large, complex, and cumbersome. And in today's security-sensitive environment I wouldn't blame my customers if they weren't prepared to deploy the work around.

[Stack trace.txt](https://github.com/eclipse-ee4j/glassfish/files/12190751/Stack.trace.txt)
ent, and Priority label"

**Comment by arjantijms** [comment]
Thanks a lot for the detailed description. I'm going to take a look at it for the next (7.0.8) GF release.

**Comment by Blavo** [comment]
G'day,

You may find Payara/payara issues 6338, 6333, and 6330 relevant too.

**Comment by dmatej** [comment]
Hmmm, this goes to [glassfish-corba](https://github.com/eclipse-ee4j/orb/issues) project, probably. But it might be related to limitations of newer JDK versions, so we had to change the way we generate proxies.

```
        // IMPORTANT - read_long() will advance the position of the ByteBuffer.
        //             Hence, in the logic below, we need to reset the position
        //             back to its original location.
        if (checkForEndTag) {
            int nextLong = read_long();
            byteBuffer.position(byteBuffer.position() - 4);

            // It was an end tag, so there wasn't enough data
            // left in the valuetype's encoding on the wire
            // to read what we wanted
            if (nextLong < 0) {
                throw omgWrapper.rmiiiopOptionalDataIncompatible3();
            }
        }
```

There is also this weird comment:```

    // RMI-IIOP stream format version 2 case in which we know
    // that there is no more optional data available.  If the
    // Serializable's readObject method tries to read anything,
    // we must throw a MARSHAL with the special minor code
    // so that the ValueHandler can give the correct exception
    // to readObject.  The state is cleared when the ValueHandler
    // calls end_value after the readObject method exits.
    private boolean specialNoOptionalDataState = false;
```

Not sure what is the correct fix, I am trying to figure out what is happening there.

**Comment by Blavo** [comment]
G’day,

I think you might be off track here. What we are doing is a list() call and that is supposed to return a naming enumeration of name class pairs listing the sub contexts of the context being listed. No proxies need to be created to satisfy the contract of a list() call. (Creation of a proxy doesn't happen until we do a lookup() call based on the result of the list() call. We’ll see if that works when we figure this one out). First thing I’d do is confirm that what the server is trying to Marshall is a naming enumeration. I suspect it is not. And if it isn’t there is no need for the server to be marshalling it, since it doesn’t need to return it.

**Comment by Blavo** [comment]
Keep open please - the workaround is horrible and depends on my customer doing unnatural stuff; I would very much like to get rid of the work around

**Comment by avpinchuk** [comment]
Hi @Blavo. Can you provide a reproducer?

**Comment by Blavo** [comment]
G'day,

'How to reproduce' references a reproducer but it doesn't show in the incident.

I have reattached it. Check the comments for how to use it.

[GFLookupReproducer.txt](https://github.com/user-attachments/files/16424450/GFLookupReproducer.txt)

**Comment by Blavo** [comment]
G’day,

Done.


Ian Blavins
0408 848 548

**Comment by avpinchuk** [comment]
@Blavo, please try with [this build](https://ci.eclipse.org/glassfish/job/glassfish_build-and-test-using-jenkinsfile/job/PR-25076/1/artifact/bundles/glassfish.zip).

**Comment by avpinchuk** [comment]
Or even better with [this build](https://ci.eclipse.org/glassfish/job/glassfish_build-and-test-using-jenkinsfile/job/PR-25076/3/artifact/bundles/glassfish.zip).

**Comment by Blavo** [comment]
G’day,

Will do. Just back from a month-long road trip so one or two things to attend to first.


Ian Blavins
0408 848 548

**Comment by Blavo** [comment]
G’day,

Ported one of my big apps to the new build. Was able to list java:global to find the sub contexts and was able to list one of the sub contexts to find the beans. That is a win !.

Well done and my thanks.

Look forward to 7.0.17 and getting rid of the work around code.




G’day,

First indications look good using a very simple web app.

Will now port my main apps to the new glassfish and try a much more complex example.



Ian Blavins
