### ISSUE TITLE
Embedded glassfish cannot do context lookup() because of java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Blavo** [eclipse-ee4j/glassfish#24541]
If I deploy a very simple web app to an embedded glassfish based on glassfish-embedded-all-7.0.6.jar, and that app does a context lookup() to lookup, say, a remote EJB, the lookup will fail with a java.lang.NoSuchMethodError referencing method java.lang.Class sun.misc.Unsafe.defineClass(java.lang.String, byte[], int, int, java.lang.ClassLoader, java.security.ProtectionDomain).

## Environment Details
glassfish 7.0.6
java version "17.0.7" 2023-04-18 LTS
Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.7+8-LTS-224, mixed mode, sharing)
Mac OS 12.4 (Monterey)
Database not applicable

----------

## Problem Description

If I deploy a very simple web app to an embedded glassfish based on glassfish-embedded-all-7.0.6.jar, and that app does a context lookup() to lookup, say, a remote EJB, the lookup will fail with a java.lang.NoSuchMethodError referencing method java.lang.Class sun.misc.Unsafe.defineClass(java.lang.String, byte[], int, int, java.lang.ClassLoader, java.security.ProtectionDomain).

The lookup() call should return a proxy for the remote EJB.

The problem is reliably reproducible.

The problem is caused by org.glassfish.pfl.basic in glassfish-embedded-all-7.0.6.jar being out of date. Unsafe.defineClass was removed at JDK 9 so the org.glassfish.pfl.basic in the embedded jar should no longer be referring to it. This is proven by downloading pfl-basic-4.1.2.jar and adding it ahead of glassfish-embedded-all-7.0.6.jar in the reproducer class path. (The lookup still fails (and that is the subject of a separate issue) but the lookup() attempt gets a whole lot further.)

## Steps to reproduce

I have reproduced this problem by creating a web app as described and deploying it's war programmatically to a newly started embedded glassfish instance in the reproducer. I will if necessary provide all the artefacts which include:

- a modified domain.xml file (modified to prevent port conflicts with standard glassfish, an instance of which has to be running to populate java:global)
- the source of the web app, which does a context lookup()
- the reproducer itself which starts a remote glassfish and deploys the web app to it
- a class library that provides a remote EJB to be added to the glassfish server (to be looked up) and to the reproducer (to lookup)
- etc

but its a lot of work for both of us given that it should be clear, now pointed out, that org.glassfish.pfl.basic is out of date in the glassfish-embedded-all-7.0.6 JAR I imagine a quick check of what version of pfl-basic was used in the construction of the embedded jar will confirm that it is out of date.

However, previous experience has suggested a short cut. A context lookup() done from a POJO Java app with the embedded glassfish JAR in its class path (instead of gf-client.jar) does a lookup based on the classes in the embedded JAR and reproduces the problem. This is a whole lot easier to use as a reproducer so I have included that.

So, to reproduce (the first three steps are optional - the problem reproduces without them):
1. Start a convenient glassfish instance that contains an EJB
2. Get the portable JNDI name for an EJB from the server log
3. Modify the reproducer source to make this the value of the lookup string.
4. Compile and run the reproducer with embedded-all-7.0.6 in the class path, and, optionally, a class library that contains the class of the EJB to be looked up (it will never be used, hence the optionality); you will need the --add JVM options specified in the source of the reproducer for it to run
5. The problem reproduces
6. Download pfl-basic-4.1.2.jar 
7. Recompile and rerun the reproducer with the new library ahead of embedded-all-7.0.6 in the class path, and, optionally, the above class library (it will never be used, hence the optionality)
8. The problem transforms into a name space not found error; (this shouldn't be and is the subject of a separate issue)

## Impact of Issue
This error doesn't affect me now because I have worked around it by including pfl-basic-4.1.2.jar in my class path. The error that then results is a different matter but that is dealt with elsewhere.

[StackTrace.txt](https://github.com/eclipse-ee4j/glassfish/files/12328897/StackTrace.txt)

[reproducer.txt](https://github.com/eclipse-ee4j/glassfish/files/12328925/reproducer.txt)

**Comment by avpinchuk** [comment]
@Blavo, please try latest SNAPSHOT if you have such ability

**Comment by avpinchuk** [comment]
pfl-basic is not out-of-date, it is the Multi-Release JAR

**Comment by Blavo** [comment]
G’day,

I had a look but don’t see anything related to testing of SNAPSHOTs. I am not a contributor so this may not be available to me. If it requires Maven or Gradle or similar then I don’t have them.

**Comment by pzygielo** [comment]
Publicly available build of the latest version: https://ci.eclipse.org/glassfish/job/glassfish_build-and-test-using-jenkinsfile/job/master/lastSuccessfulBuild/artifact/bundles/

**Comment by Blavo** [comment]
G’day,

I downloaded the build you referred to but it doesn’t contain glassfish-embedded-all-7.0.6 (or successor) which is necessary for the test. It is the classes from pfl-basic in the currently released version of glassfish-embedded-all-7.0.6 that are out of date (or the whole JAR is out of date, which seems unlikely).

**Comment by pzygielo** [comment]
:disappointed: 
Looks that `embedded-all.jar` is extra, and the latest (and only) SNAPSHOT deployed to Eclipse repository was [6.1.1-SNAPSHOT](https://jakarta.oss.sonatype.org/content/repositories/staging/org/glassfish/main/extras/glassfish-embedded-all/6.1.1-SNAPSHOT/).

Can you check https://ci.eclipse.org/glassfish/job/glassfish_build-and-test-using-jenkinsfile/view/change-requests/job/PR-24551/4/artifact/embedded/ then?

**Comment by Blavo** [comment]
G’day,

This isn’t fixed.

I substituted the referenced embedded-glassfish-all for embedded-glassfish-all-7.0.6 in my reproducer and did a clean build. I got exactly the same issue.

I expanded the two JARs. The dates and byte counts for org.glassfish.pfl.basic.reflection.BridgeBase.class (the class that excepts) are the same in both so the above is as expected, if not what is wanted ie its the same class binary in both.

I also expanded pfl-basic-4.1.2. The org.glassfish.pfl.basic.reflection.BridgeBase.class there has the same byte count as both the above (7,053) but a different date so it is hard to be definitive about whether it was compiled from a different source or not (or maybe it was simply compiled under a different JVM).

 Anyway, the problem persists with the new embedded glassfish JAR.

**Comment by avpinchuk** [comment]
Hi, @Blavo. Actual classes for various Java versions places at the `META-INF\versions` directory.

 Please, try with https://ci.eclipse.org/glassfish/job/glassfish_build-and-test-using-jenkinsfile/job/PR-24554/lastCompletedBuild/artifact/embedded/glassfish-embedded-all.jar.

Thank you!

**Comment by avpinchuk** [comment]
If you interested, more info about MR-JARs: https://openjdk.org/jeps/238

**Comment by Blavo** [comment]
G’day,

The new embedded JAR at:

https://ci.eclipse.org/glassfish/job/glassfish_build-and-test-using-jenkinsfile/job/PR-24554/lastCompletedBuild/artifact/embedded/glassfish-embedded-all.jar <https://ci.eclipse.org/glassfish/job/glassfish_build-and-test-using-jenkinsfile/job/PR-24554/lastCompletedBuild/artifact/embedded/glassfish-embedded-all.jar>

fixed the problem and the lookup() in the reproducer worked. That has implications for one or more other issues that I have raised as I expected that the lookup() would fail in a different way. I will retest the other issues and update them in due course.

But for this issue, it is a win. Well done.

And thank you for the link on multi-release JARs. I wasn’t aware of this work and applaud it as a very useful step forward for developers of Java tools. I might even need to use it myself.
