### ISSUE TITLE
Glassfish 7.0.6 at Java 17 cannot pass to a remote EJB, or receive from it, a Diagnostic.Kind (enum); makes reference to class removed at Java 11

### ISSUE THREAD

**Issue by Blavo** [eclipse-ee4j/glassfish#24558]
If I call a remote EJB in a glassfish 7.0.6 server, and the output type of the method call, or one of the method parameters, is, or contains, a Diagnostic.Kind (an enum defined in javax.tools), the call will fail with a jakarta.ejb.EJBException citing a java.rmi.MarshalException with eventual message 'Could not load class javax.rmi.CORBA.EnumDesc'.

## Environment Details
glassfish 7.0.6
java version "17.0.7" 2023-04-18 LTS
Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.7+8-LTS-224, mixed mode, sharing)
Mac OS 12.4 (Monterey)
Database not relevant

----------

## Problem Description
If I call a remote EJB in a glassfish 7.0.6 server, and the output type of the method call, or one of the method parameters, is, or contains, a Diagnostic.Kind (an enum defined in javax.tools), the call will fail with a jakarta.ejb.EJBException citing a java.rmi.MarshalException with eventual message 'Could not load class javax.rmi.CORBA.EnumDesc'. 

The call should not fail. If I remove the enum using the bypass described below (ie passing the name instead of the enum and reconstructing the enum on the server side), the call succeeds.

Diagnostic.Kind is an enum defined in javax.tools.Diagnostic. An enum that is defined within the application can be safely passed as either a method parameter or received as a method output type.

If I do a google 'whichjar javax.rmi.CORBA.EnumDesc' then glassfish-corba-omgapi.jar gets a mention. But according to the stack trace entry at 'https://stackoverflow.com/questions/56327632/java-11-and-jacorb-classnotfoundexception-javax-rmi-corba-stub' the Corba module was removed at Java 11. This is hardly definitive but it looks like the glassfish code is referencing a class in a module that doesn't exist at Java 17. Begins to look like a multi-JAR issue.

The problem is reliably reproducible.

[StackTraceAndOutput.txt](https://github.com/eclipse-ee4j/glassfish/files/12435024/StackTraceAndOutput.txt)

## Steps to reproduce
1 Create an IDE Java class library project that contains the attached EOTInterface and EOTOutputType
2 Compile the project as a Java class library with jakarta.ejb-api-4.0.1.jar in the class path; note where the JAR goes
3 Create an IDE web app project that contains the attached EOTBeanSource and Initialise
4 Compile the project as a web app with the JAR from step 2 in the class path
5 Deploy the resulting war to a convenient running 7.0.6 glassfish server
6 Restart the server and check the message "Successfully made Diagnostic.Kind in @PostConstruct" appears in the server log; this establishes that Diagnostic.Kind is in the server class path
7 Obtain from the server log the portable JNDI name of EOTInterfaceBeanRemote
8 Create an IDE Java app project that contains the attached EnumTypeOutputClient
9 Edit EnumTypeOutputClient and change the value of 'lookupString' to the portable JNDI name from 7
9a Change the value of the 'org.omg.CORBA.ORBInitialPort' property to 3700
10 Compile the project as a stand alone Java application with the JAR from 2 in the class path along with 
the gf-client.jar from the glassfish 7.0.6 install; make sure the class path entry references the JAR in the install, not a copy, as lookup() calls behave differently if this JAR is not in the install directory
11 Add the 'add--'s noted in the EnumTypeOutputClient source as execution JVM options
12 Run EnumTypeOutputClient

The first two remote EJB method calls work. They show that enums in general (or at least enums defined in the project) can be passed as method call output types or as method call parameters.

The next two remote EJB method calls work. They show that using the name of Diagnostic.Kind enum can be passed as method call output types or as method call parameters.

The last two calls fail as described. One call has Diagnostic.Kind as the method call output and one has Diagnostic.Kind as a method call parameter.

## Impact of Issue
This is relatively easy to bypass if the enum occurs in a class defined within the application. Instead of passing the enum, pass the name() of the enum as a string and, in the bean code on the server, turn the name of the enum back into the enum with a valueOf() call. (The necessary classes have already to be available in the client and server.) Where the enum is in a class that is defined externally to the app, and that class if passed as the method output type, this might be a bit more challenging.

[EOTBeanSource.txt](https://github.com/eclipse-ee4j/glassfish/files/12434833/EOTBeanSource.txt)
[Initialise.txt](https://github.com/eclipse-ee4j/glassfish/files/12434834/Initialise.txt)
[EOTInterface.txt](https://github.com/eclipse-ee4j/glassfish/files/12434822/EOTInterface.txt)
[EOTOutputType.txt](https://github.com/eclipse-ee4j/glassfish/files/12434823/EOTOutputType.txt)
[EnumTypeOutputClient.txt](https://github.com/eclipse-ee4j/glassfish/files/12434876/EnumTypeOutputClient.txt)

**Comment by arjantijms** [comment]
The `EnumDesc` is referenced in `com.sun.corba.ee.impl.encoding.CDROutputStream_1_0.write_value(Serializable, String)` which is in the jar with maven coordinates `org.glassfish.corba:glassfish-corba-orb:4.2.4` and in the project https://github.com/eclipse-ee4j/orb/blob/master/orbmain/src/main/java/com/sun/corba/ee/impl/encoding/CDROutputStream_1_0.java#L734

See:

```java
@CdrWrite
    public void write_value(Serializable object, String repository_id) {
        // Handle null references
        if (object == null) {
            // Write null tag and return
            write_long(0);
            return;
        }

        Class clazz = object.getClass();
        ClassInfoCache.ClassInfo cinfo = ClassInfoCache.get(clazz);
        if (cinfo.isEnum()) {
            String enumValue = ((Enum) object).name();
            if (orb.getORBData().useEnumDesc()) {
                EnumDesc desc = getEnumDesc(clazz.getName(), enumValue);
                write_value(desc, (String) null);
```

This same source repo contains the source for `EnumDesc` as well:

https://github.com/eclipse-ee4j/orb/blob/master/omgapi/src/main/java/javax/rmi/CORBA/EnumDesc.java

The exception is indeed easy to reproduce.

**Comment by arjantijms** [comment]
After a quick observation the exception seems to occur at the client in the corresponding read method `com.sun.corba.ee.impl.encoding.CDRInputStream_1_0.read_value(Class)`

**Comment by arjantijms** [comment]
Maybe the most troublesome piece of code is this one in `com.sun.corba.ee.impl.util.Utility.loadClassOfType(String, String, ClassLoader, Class, ClassLoader)`:

```java
// If no class was loaded, or if the loaded class is not of the 
        // correct type, make a further attempt to load the correct class
        // using the classloader of the expected type.
        // _REVISIT_ Is this step necessary, or should the Util,loadClass
        // algorithm always produce a valid class if the setup is correct?
        // Does the OMG standard algorithm need to be changed to include
        // this step?
        if (loadedClass == null || !expectedType.isAssignableFrom(loadedClass)){
            if (expectedType.getClassLoader() != expectedTypeClassLoader) {
                throw new IllegalArgumentException("expectedTypeClassLoader not class loader of " +
                    "expected Type.");
            }

            if (expectedTypeClassLoader != null) {
                loadedClass = expectedTypeClassLoader.loadClass(className);
            } else {
                loadedClass = ORBClassLoader.loadClass(className);
            }
        }

        return loadedClass;
```

The `javax.rmi.CORBA.EnumDesc` type is loaded, but since it can be cast (`isAssignableFrom`) to `javax.tools.Diagnostic$Kind` it's attempted to be loaded from the class loader of `javax.tools.Diagnostic$Kind`. This is the JDK class loader, which will obviously not find it.

**Comment by arjantijms** [comment]
I did an experimental fix here: https://github.com/eclipse-ee4j/orb/compare/master...arjantijms:orb:fix_enum_read#diff-b918fc3a4402629ac8c1917ae3216f23e763a252156b3f2b7e01236fefae79d6R306

cc @dmatej what do you think?

It fixes this specific problem. I'll test whether it doesn't have any other bad side-effects.

**Comment by dmatej** [comment]
We should start writing tests for CORBA. :-D
