### ISSUE TITLE
Standalone instance fails sync if a json file is present in project

### ISSUE THREAD

**Issue by SeamonLark** [eclipse-ee4j/glassfish#24586]
## Environment Details
* GlassFish Version 7.0.7
* JDK version: 17
* OS: Windows 10
* Database:

----------

## Problem Description
A war containing a json file can by deployed to a standalone instance, but it will fail
when synchronization occurs. Problem is tied to the file extension .json.

Log message:
CLI802 Synchronization failed for directory applications, caused by:  I/O Error: org.codehaus.jettison.json.JSONException: A JSONObject text must begin with '{' at character 1 of [

## Steps to reproduce
Create project with .json file in resources.
Deploy to an inactive standalone instace. 
Start the instance. 
(or any other scenario when the synchronization occures)

## Impact of Issue
Prevents synchronization in standalone instaces.

**Comment by SeamonLark** [comment]
Min example:
https://github.com/SeamonLark/JsonWarProblem

.\asadmin create-instance --node localhost-domain1 testInstance
.\asadmin stop-instance testInstance
.\asadmin deploy --target testInstance [path]
.\asadmin start-instance testInstance

**Comment by pzygielo** [comment]
I'm getting the same with GF 7.0.8 and above `JsonWarProblem` project, which is
```
[2023-09-12T18:03:55.899763+02:00] [GF 7.0.8] [WARNING] [] [jakarta.enterprise.system.core] [tid: _ThreadID=47 _ThreadName=admin-listener(5)] [levelValue: 900] [[
  Could not start instance testInstance on node localhost-domain1 (localhost).: Command ' .../glassfish7/glassfish/lib/nadmin --_auxinput - --interactive=false start-local-instance --node localhost-domain1 --sync normal testInstance' failed on node localhost-domain1 (localhost): Command start-local-instance failed.

An unexpected exception occurred. A JSONObject text must begin with '{' at character 1 of [
...
 CLI802 Synchronization failed for directory applications, caused by:
   I/O Error: org.codehaus.jettison.json.JSONException: A JSONObject text must begin with '{' at character 1 of [
     {
       "theme_name": "black-tie",
...
```

**Comment by dmatej** [comment]
That sounds familiar - it is like those logging rest endpoints with undefined priority of plain/text vs. JSON responses. When server formats json content for the response, SOMETIMES it is wrapped as json body and the json content is escaped. And sometimes not.
See d6423f4b8920095615a8eda3d6f3ab1d6db76d41

**Comment by pzygielo** [comment]
I observe the same with GF 7.0.0
@SeamonLark do you know of any previous version that this worked for you?

**Comment by SeamonLark** [comment]
The problem is somehow tied to .json extension - if it's changed (.jsn for e.g.) synchronization works.

@pzygielo Not really I've encountered this while transforming an older project which was running on some old Payara 4 (jJava 8). It seems there was a similar issue in Payara https://github.com/payara/Payara/issues/5987#issuecomment-1285327992
