### ISSUE TITLE
stopping service won't stop the server

### ISSUE THREAD

**Issue by mirozitnansky** [eclipse-ee4j/glassfish#24587]
## Environment Details
* GlassFish Version (and build number): glassfish-7.0.8
* JDK version: OpenJDK Runtime Environment Zulu11.64+19-CA (build 11.0.19+7-LTS)
* OS: Windows 11

----------

## Problem Description
Service created by `.\asadmin.bat create-service` command is able to start domain1, but not to stop it, writing error into 
_glassfish\domains\domain1\bin\domain1Service.wrapper.log_

> 2023-09-12 13:08:03 - Started 84812
> 2023-09-12 13:08:38 - Stopping domain1
> 2023-09-12 13:08:38 - Stop exception
> Message:<stopexecutable> is missing in configuration XML
> Stacktrace:   at winsw.ServiceDescriptor.SingleElement(String tagName, Boolean optional)
>    at winsw.ServiceDescriptor.SingleElement(String tagName)
>    at winsw.ServiceDescriptor.get_StopExecutable()
>    at winsw.WrapperService.StopIt()
>    at winsw.WrapperService.OnStop()
> 

## Steps to reproduce

1. Unzip glassfish-7.0.8.zip into glassfish-7.0.8 folder
2. open glassfish-7.0.8 in powershell (cmd) **as administrator**
3. cd glassfish7\bin\
4. run `.\asadmin.bat create-service`
5. runs successfully with standard printout ending _Command create-service executed successfully._
6. start service by generated binary `glassfish7\glassfish\domains\domain1\bin\domain1Service.exe  start`
7. check log in _glassfish7\glassfish\domains\domain1\bin\domain1Service.wrapper.log_, domain server should by running on port localhost:4848
8. stop service by running _glassfish7\glassfish\domains\domain1\bin\domain1Service.exe  stop_, end without printout
9. run `\glassfish7\glassfish\domains\domain1\bin\domain1Service.exe status` pritns _Stopped_
10. domain is still running on default port 4848, service was unable to stop the server

## Impact of Issue
Behaviour is the same for standalone or cluster instances.
Server is unable to stop by executing `Stop-Service domain1` in powershell, or by any other means to stop the service.
Only way to stop instance without using `asadmin stop-instance` command is by killing java process. Command `stop-local-instance` does not detect running instance. I will create new issue for this.

**Comment by dmatej** [comment]
Note: In GF sources is some `/org.glassfish.main.admin.server-mgmt/src/main/resources/lib/winsw.exe` file, I have no idea where it has sources, how old it is and if it is compatible with current windows versions.
Also the man page mentions glassfish3 ... we should take a look on this, however I would not recommend using Windows to anyone :-) , it should work if we distribute it.

**Comment by avpinchuk** [comment]
Hmm... Newest versions of `winsw` takes ~20Mb. I'll try to play with `Apache Procrun`

**Comment by avpinchuk** [comment]
@mirozitnansky, please try with https://ci.eclipse.org/glassfish/job/glassfish_build-and-test-using-jenkinsfile/job/PR-24590/1/artifact/bundles/glassfish.zip

**Comment by mirozitnansky** [comment]
@avpinchuk stopping service is now working for domain, but not for instance.
If you create 
`.\asadmin.bat create-local-instance test` 
then service for it 
`.\asadmin.bat create-service test`
you'll be able to start by calling executing _nodes\localhost-domain1\test\bin\testService.exe  start_ or _start-service test_ but stopping service never ends.

_nodes\localhost-domain1\test\bin\testService.wrapper.log_
> 2023-09-14 11:01:33,693 INFO  - Stopping test
> 2023-09-14 11:01:33,697 INFO  - Started process 71780
> 2023-09-14 11:01:33,698 DEBUG - WaitForProcessToExit 83220+71780

powershell endlessly

> PS C:\Users\miro> stop-service test
> WARNING: Waiting for service 'test GlassFish Server (test)' to stop...
> WARNING: Waiting for service 'test GlassFish Server (test)' to stop...
> WARNING: Waiting for service 'test GlassFish Server (test)' to stop...
> WARNING: Waiting for service 'test GlassFish Server (test)' to stop...

you can only stop by killing _testService.exe_ `Stop-Process -Name testService`


Other thing I noticed is, when you create service is executable only for Administrator.
You can read it's state by user with admin rights, but you won't be able to start/stop it.

> PS C:\Users\miro> get-service test
> 
> Status   Name               DisplayName
> ------   ----               -----------
> StopPen… test               test GlassFish Server
> 
> PS C:\Users\miro> stop-service test
> Stop-Service: Service 'test GlassFish Server (test)' cannot be stopped due to the 
> following error: Cannot stop 'test' service on computer '.'.
> PS C:\Users\miro> start-service domain1
> Start-Service: Service 'domain1 GlassFish Server (domain1)' cannot be started due to the following error: Cannot open 'domain1' service on computer '.'.

**Comment by avpinchuk** [comment]
> @avpinchuk stopping service is now working for domain, but not for instance.

I think it's related to #24588

**Comment by mirozitnansky** [comment]
Yes, that might be it.

**Comment by avpinchuk** [comment]
> Other thing I noticed is, when you create service is executable only for Administrator.
> You can read it's state by user with admin rights, but you won't be able to start/stop it.

Give please SDDL output of the `sc sdshow domain1` command.

**Comment by mirozitnansky** [comment]
output for user 
```
> sc sdshow domain1
D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)
```
out as Administrator
```
> sc sdshow domain1

D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)S:(AU;FA;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;WD)
```

**Comment by avpinchuk** [comment]
Looks good. Your user in built-in admins group?
