### ISSUE TITLE
Cluster Monitoring Data values not Display on Administration Console

### ISSUE THREAD

**Issue by yoshioza** [eclipse-ee4j/glassfish#24619]
Cluster Monitoring Data values not Display on Administration Console

## Environment Details
* GlassFish Version (and build number): 7.0.9 (commit: 5860e42c2edeb9f3b46428fcf9dab95790a9a3f0)
* JDK version: 17
* OS: Windows10
* Database: -

----------

## Problem Description
I am unable to monitor the status of clusters in the Administration Console.
It is possible to check using the asadmin command.

## Steps to reproduce

1. Set up GlassFish (unzip to C:\glassfish).
2. Start GlassFish (use the command asadmin start-domain).
3. Access the Administration Console (localhost:4848).
4. Create a cluster.
5. Deploy the Sample Application to the cluster.
6. Set all Monitoring settings of the created cluster to HIGH.

![Glassfish_01_cluster_monitoringconfig](https://github.com/eclipse-ee4j/glassfish/assets/146069887/9e21217c-31cd-4b4d-bc47-0aaa33b0685b)

7. Start the cluster.
8. Display the Sample Application page.
![Glassfish_02_checksampleapp](https://github.com/eclipse-ee4j/glassfish/assets/146069887/51a02bc7-abfc-49aa-8dbb-81a3faadbc3c)

9. Attempt to check the state of Cluster instances from Monitoring Data.

Cluster Monitoring Data is not displayed.

- application
![Glassfish_03_cluster_monitoring_notdisplay_application_](https://github.com/eclipse-ee4j/glassfish/assets/146069887/880de6fd-3a04-4c8f-84d2-a531cfa4c0c1)

- server
![Glassfish_04_cluster_monitoring_notdisplay_server_](https://github.com/eclipse-ee4j/glassfish/assets/146069887/16396c68-4a46-423a-a5e4-2b3bb1f7c69f)

- resource
![Glassfish_05_cluster_monitoring_notdisplay_resource_](https://github.com/eclipse-ee4j/glassfish/assets/146069887/c1fb1442-5c56-46b7-ac9d-d07205cf9a2c)

- Monitoring Data for the DAS server is displayed.

![Glassfish_90_DasServer_monitoring_display_server](https://github.com/eclipse-ee4j/glassfish/assets/146069887/b69c0eb0-c7a0-4cdb-9e4e-c8307173ea44)

- The result of obtaining cluster information using the asadmin command.
![glassfish_06_asadmin_monitoring_data](https://github.com/eclipse-ee4j/glassfish/assets/146069887/fa186386-4aa2-4579-86f9-bbc54e4d546f)

[DAS_server.log](https://github.com/eclipse-ee4j/glassfish/files/12799872/DAS_server.log)

[testcluster01_server.log](https://github.com/eclipse-ee4j/glassfish/files/12799873/testcluster01_server.log)

## Impact of Issue
In the Administration Console, it is not possible to monitor cluster resource usage, including memory consumption.

**Comment by OndroMih** [comment]
I can reproduce on GlassFish 7.0.15-SNAPSHOT. I see the following exception in the log:

```
[#|2024-04-07T01:50:31.193947+02:00|WARNING|GF 7.0.15-SNAPSHOT|org.glassfish.jersey.server.ServerRuntime$Responder|_ThreadID=61;_ThreadName=admin-listener(2);_LevelValue=900;|
  An exception mapping did not successfully produce and processed a response. Logging the exception propagated to the default exception mapper.
java.lang.RuntimeException: java.lang.ClassNotFoundException: Provider for jakarta.ws.rs.client.ClientBuilder cannot be found
	at jakarta.ws.rs.client.ClientBuilder.newBuilder(ClientBuilder.java:75)
	at jakarta.ws.rs.client.ClientBuilder.newClient(ClientBuilder.java:86)
	at org.glassfish.admin.rest.utils.Util.getJerseyClient(Util.java:269)
	at org.glassfish.admin.rest.resources.MonitoringResource.getChildNodes(MonitoringResource.java:159)
```
