### ISSUE TITLE
Unable to build GlassFish on master out of the box

### ISSUE THREAD

**Issue by ctabin** [eclipse-ee4j/glassfish#24643]
Hello,

I just wanted to simply compile GlassFish after a fresh `git clone` as instructed in the README with `mvn clean install`, but the build immediately fails because the following artifacts are not released on Maven:
- [eclipse-ee4j/glassfish-build-maven-plugin](https://github.com/eclipse-ee4j/glassfish-build-maven-plugin/releases/tag/4.0.0-M1) 4.0.0-M1
- [eclipse-ee4j/glassfish-hk2](https://github.com/eclipse-ee4j/glassfish-hk2/releases/tag/3.0.5-RELEASE) 3.0.5
- [eclipse-ee4j/grizzly](https://github.com/eclipse-ee4j/grizzly/releases/tag/4.0.1-RELEASE) 4.0.1
- [eclipse-ee4j/wasp](https://github.com/eclipse-ee4j/wasp/releases/tag/3.2.1) 3.2.1

I had to manually clone those projects, checkout the release tag and compile them in order to build locally :-) It would be helpful to avoid those actions (or maybe add some hints in the README ?).

Thanks for the work and best regards !

**Comment by pzygielo** [comment]
https://github.com/eclipse-ee4j/glassfish#special-profiles -> activate `staging` profile

**Comment by ctabin** [comment]
Hi @pzygielo Thanks for the reply, that did the trick, hence closing this issue.
