### ISSUE TITLE
Why should I download glassfish-7.0.10 when I compile glassfish 7.0.10?

### ISSUE THREAD

**Issue by zistrong** [eclipse-ee4j/glassfish#24664]
![image](https://github.com/eclipse-ee4j/glassfish/assets/4328187/ec2082b2-01bc-4825-9bbb-aab0c34e0fbb)

**Comment by dmatej** [comment]
I noticed it too, this change came from new Eclipse Parent POM and it is for SBOM generation.
Can you take a look, please, @ivargrimstad ? Maybe we should add some additional configuration, I don't know.

**Comment by ivargrimstad** [comment]
The plugin is documented here: https://cyclonedx.github.io/cyclonedx-maven-plugin/makeAggregateBom-mojo.html

A quick fix is to disable generation with -DskipSBOM. 
Maybe we should turn it around and have it turned off by default and rather explicitly enable it when publishing?

**Comment by dmatej** [comment]
The question is why it downloads an artifact which is produced by this build?

**Comment by dmatej** [comment]
> > The question is why it downloads an artifact which is produced by this build?
> 
> I think that may be a Maven thing, if I'm not wrong? Even with the -DskipSBOM the build will download. With offline build `-o`, this is prevented.

Maybe it could be executed in later phase or as last thing in reactor (that may have other consequences), but I don't know what exactly it does and what are the requirements.
