### ISSUE TITLE
Got an exception "Could not convert socket to TLS" when sending an email

### ISSUE THREAD

**Issue by hhallenyang** [eclipse-ee4j/glassfish#24669]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"
The Glassfish Server generate an exception when the system try to send email out. 

## Environment Details
* GlassFish Version (and build number): 7.0.9
* JDK version: 17
* OS: Windows 11 Pro
* Database: SQL Server

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"

I got the "Could not convert socket to TLS" exception when I try to send an email out. I could send it out successfully with the same code and configuration from Glassfish 4 installed in the same computer. 

[//]: # "State if the problem is easily reproducible or happens intermittently"
This problem is easily reproducible.

[//]: # "Include stack traces or command outputs"

 expected resource not found: /META-INF/javamail.default.address.map|#]
  jakarta.mail.MessagingException: Could not convert socket to TLS;
  nested exception is:
	javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target|#]

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
Start the Glassfish server, configure the email connection, enter the email content and send the email out.

[//]: # "Provide sample code/application if relevant"
The same method as shown below is called from Glassfish 4 and Glassfish 7. Glassfish 4 sent the email successfully but Glassfish 7 got the exception above.

    public void sendOneEmail(String toAddr, String emailContent) {
        Properties props = new Properties();
        props.put("mail.smtp.host", "smtp.gmail.com");
        props.put("mail.smtp.port", "587");
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");

        Session emailSession = Session.getInstance(props, new Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication("MY EMAIL ADDRESS", "MY PASSWORD");
            }});

        try {
            MimeMessage message = new MimeMessage(emailSession);
            message.setFrom(new InternetAddress("MY EMAIL ADDRESS", "Tester"));
            message.setSubject("Testing");
            message.setContent(emailContent, "text/plain; charset=UTF-8");
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(toAddr.replaceAll("\\s+", "")));
            try {
                Transport.send(message);
                Thread.sleep(2000L);
            } catch (MessagingException e) {
                System.out.println(e.toString());
            }
        } catch (MessagingException | UnsupportedEncodingException | InterruptedException e) {
        }
    }

Glassfish 4: Java EE Web API Library
Glassfish 7: includes
        <dependency>
            <groupId>jakarta.mail</groupId>
            <artifactId>jakarta.mail-api</artifactId>
            <version>2.1.1</version>
            <scope>provided</scope>
        </dependency>

## Impact of Issue
[//]: # "How has this issue affected you? What are you trying to accomplish?"
Sending email is very important for the project.

[//]: # "Please choose one each Type, Component, and Priority label"
High

**Comment by OndroMih** [comment]
This is probably because in GlassFish 7 you don’t have the certificate from smtp.google.com in the trust store file cacerts.jks. You need to download it and add it there. Or copy it from the same file in GlassFish 4, where you probably installed it in the past.
