### ISSUE TITLE
Memory Leak Detected in Glassfish 7

### ISSUE THREAD

**Issue by shashank2337** [eclipse-ee4j/glassfish#24672]
We have monitored glassfish 7 for few days and we have observed that there are memory leaks. The memory leaks are more prominent during high load and the heap utilization goes 100% in 2-3 hours only. This leads to application crash.

## Environment Details
* GlassFish Version 7.0.10-SNAPSHOT
* JDK version: 17.0.1
* OS: SUSE Linux Enterprise Server 12 SP5
* Database: Oracle 19c

----------

## Problem Description
There are memory leaks over the period of time. The memory leak is more prominent when the load is high. This leads to application crash when heap usage increases to 100 percent.

The problem is easily producible with RESTful Web Services using Jersey

The memory dump analyzed by MAT shows the following

Problem Suspect 1
6,044 instances of “org.jvnet.hk2.internal.ServiceLocatorImpl”, loaded by “org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @ 0x60145a458” occupy 1,783,552,456 (46.55%) bytes. 

Problem Suspect 2
775,627 instances of “org.jvnet.hk2.internal.SystemDescriptor”, loaded by “org.apache.felix.framework.BundleWiringImpl$BundleClassLoader @ 0x60145a458” occupy 1,307,053,624 (34.11%) bytes. 

## Steps to reproduce
This issue can be reproduced by any RESTful Web Services using Jersey. We have used below artifacts.
<dependency>
	<groupId>org.glassfish.jersey.core</groupId>
	<artifactId>jersey-server</artifactId>
	<version>3.1.3</version>
	<scope>provided</scope>
</dependency>
<dependency>
	<groupId>org.glassfish.jersey.core</groupId>
	<artifactId>jersey-client</artifactId>
	<version>3.1.3</version>
	<scope>provided</scope>
</dependency>
<dependency>
	<groupId>org.glassfish.jersey.ext</groupId>
	<artifactId>jersey-spring6</artifactId>
	<version>3.1.3</version>
	<exclusions>
                .......
                .......
	</exclusions>
</dependency>

## Impact of Issue
We had upgraded our application to Glassfish 7 but we had to rollback because of the issue.

**Comment by shashank2337** [comment]
could anyone please confirm if memory leak is due to glassfish or due to libraries associated with jersey-spring6 ?

**Comment by shashank2337** [comment]
Hi @pzygielo,
This issue can be replicated when we use jakarta.ws.rs.client.WebTarget to call other rest api.
To replicate this issue I have created two rest API in this project. One rest api is calling internally the other one.
For example in this project the rest api with end point .../softwareDetails is calling end point .../nodeDetails.
If you run any script which calls endpoint ../softwareDetails continuously then you can see memory leak happening.

I have attached tar file having war which you can deploy on glassfish to replicate the issue.

[jerseyRest.zip](https://github.com/eclipse-ee4j/glassfish/files/13859767/jerseyRest.zip)

  

Please find below the main code

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.QueryParam;
import jakarta.ws.rs.client.Client;
import jakarta.ws.rs.client.ClientBuilder;
import jakarta.ws.rs.client.WebTarget;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.UriBuilder;

@Service
@Scope("request")
@Path("/obe/{phase}/{application}/{node}/application")
public class ApplicationWS {

	private static final Logger log = LoggerFactory
			.getLogger(ApplicationWS.class);

    @GET
    @Path("/nodeDetails")
    @Produces({MediaType.APPLICATION_XML})
	public List<SoftwareServer> getViewXmlState11(
			@QueryParam("phase") final String phaseString,
			@QueryParam("application") final String applicationString,
			@QueryParam("node") final String nodeString
			) throws IOException {
    	log.info(
                "WS @GET application -> (on node {}, application {}, phase {}) ",
                new Object[] {nodeString, applicationString, phaseString});
    	SoftwareServer softwareserver = new SoftwareServer();
    	softwareserver.setMag("DEV");
    	softwareserver.setHostName("obevd526");
    	softwareserver.setType("oltp");
    	List<SoftwareServer> list = new ArrayList<>();
    	list.add(softwareserver);
    	return list;
    }
    
    @GET
    @Path("/softwareDetails")
    @Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_OCTET_STREAM})
	public Object getViewXmlState4(
			@PathParam("phase") final String phaseString,
			@PathParam("application") final String applicationString,
			@PathParam("node") final String nodeString
			) throws IOException {
    	log.info(
                "WS @GET application -> (on node {}, application {}, phase {}) ",
                new Object[] {nodeString, applicationString, phaseString});
    	Client client1 = ClientBuilder.newClient();
    	String appServerUrl = "http://localhost:60251/jserseyapi/rest/obe/DEV/DUM/526_PK1_DUMD/application";
    	WebTarget service = client1.target(UriBuilder.fromUri(appServerUrl).build());
    	Map<String, String> queryParameters = new HashMap<>();
    	queryParameters.put("phase", phaseString);
    	queryParameters.put("application", applicationString);
    	queryParameters.put("node", nodeString);
    	WebTarget webTarget1 = service.path("nodeDetails");
		for (Map.Entry<String, String> entry : queryParameters.entrySet()) {
			webTarget1 = webTarget1.queryParam(entry.getKey(), entry.getValue());
		}
		
		SoftwareServer[] softwareServers = (SoftwareServer[])webTarget1.request().accept(MediaType.APPLICATION_XML).get(SoftwareServer[].class);
		
		System.out.println("SoftwareServer "+softwareServers);
		client1.close();
		return String.valueOf(softwareServers.length);
    }
}

**Comment by ramakrishna90** [comment]
Hi @dmatej @pzygielo ,
  I work with @shashank2337. This is a very serious bug, and a very basic one. Could you please prioritize this?
Thanks

**Comment by shashank2337** [comment]
Hi @pzygielo, @dmatej , @arjantijms 
We tried Rest Easy which is one more implementation of jakarta.ws.rs.client.Client. We did not find any memory leak with it. Could you please acknowledge the issue and timeline by which it could be fixed.
Regards,
Shashank

**Comment by dmatej** [comment]
Could you first fix your reproducer? 
Because `Client client1 = ClientBuilder.newClient();` should be in `try-with` block - basically you don't close your client instances if anything between their creation and `client1.close()` throws an exception.

```
public interface Client extends Configurable<Client>, AutoCloseable {
```

```
   /**
     * <p>
     * Close client instance and all it's associated resources. Subsequent calls have no effect and are ignored. Once the
     * client is closed, invoking any other method on the client instance would result in an {@link IllegalStateException}
     * being thrown.
     * </p>
     * Calling this method effectively invalidates all {@link WebTarget resource targets} produced by the client instance.
     * Invoking any method on such targets once the client is closed would result in an {@link IllegalStateException} being
     * thrown.
     */
    @Override
    public void close();
```

**Comment by shashank2337** [comment]
Hi @dmatej,

I have fixed the reproducer as per your comment and tested it. I can see that memory leak still exists. Please find below stats from jstat.

Every 2.0s: /java/jdk-17.0.1/bin/jstat -gc 510049                                                                                                                                                       Fri Jan 12 08:50:25 2024

    S0C         S1C         S0U         S1U          EC           EU           OC           OU          MC         MU       CCSC      CCSU     YGC     YGCT     FGC    FGCT     CGC    CGCT       GCT
        0.0         0.0         0.0         0.0       2048.0          0.0     522240.0     522166.6   118400.0   114516.6   14848.0   13126.7    887     5.943   408   299.436    80     0.809   306.187

Here we have defined max memory for the application as 512 MB (-Xmx512m). We have added continuous load of 5 transactions per second. As time progresses we can see there is gradual increase in OC and OU. When all memory is used up there is rapid increase in full garbage collection (FGC). Here we can see FGC value 408 at the end of load which is very high.

Please find below updated code of reproducer used.

package com.restapi.ws;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Service;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.PathParam;
import jakarta.ws.rs.Produces;
import jakarta.ws.rs.QueryParam;
import jakarta.ws.rs.client.Client;
import jakarta.ws.rs.client.ClientBuilder;
import jakarta.ws.rs.client.WebTarget;
import jakarta.ws.rs.core.MediaType;
import jakarta.ws.rs.core.UriBuilder;

@Service
@Scope("request")
@Path("/{param1}/{param2}/{param3}/application")
public class ApplicationWS {

	private static final Logger log = LoggerFactory
			.getLogger(ApplicationWS.class);

    @GET
    @Path("/service1")
    @Produces({MediaType.APPLICATION_XML})
	public List<XMLObject> getViewXmlState11(
			@QueryParam("param1") final String phaseString,
			@QueryParam("param2") final String applicationString,
			@QueryParam("param3") final String nodeString
			) throws IOException {
    	log.info(
                "WS @GET application -> (on node {}, application {}, phase {}) ",
                new Object[] {nodeString, applicationString, phaseString});
    	XMLObject xmlObject = new XMLObject();
    	xmlObject.setName("name");
    	xmlObject.setHostName("hostname");
    	xmlObject.setType("type");
    	List<XMLObject> list = new ArrayList<>();
    	list.add(xmlObject);
    	return list;
    }
    
    @GET
    @Path("/service2")
    @Produces({MediaType.APPLICATION_XML, MediaType.APPLICATION_OCTET_STREAM})
	public Object getViewXmlState4(
			@PathParam("path1") final String path1,
			@PathParam("path2") final String path2,
			@PathParam("path3") final String path3
			) throws IOException {
    	log.info(
                "WS @GET application -> (on node {}, application {}, phase {}) ",
                new Object[] {path1, path2, path3});
    	
    	XMLObject[] xmlObject = null;
    	
    	try (Client client1 = ClientBuilder.newClient()){
    		String appServerUrl = "http://localhost:60251/jserseyapi/rest/param1/param2/param3/application";
        	WebTarget service = client1.target(UriBuilder.fromUri(appServerUrl).build());
        	Map<String, String> queryParameters = new HashMap<>();
        	queryParameters.put("param1", path1);
        	queryParameters.put("param2", path2);
        	queryParameters.put("param3", path3);
        	WebTarget webTarget1 = service.path("service1");
    		for (Map.Entry<String, String> entry : queryParameters.entrySet()) {
    			webTarget1 = webTarget1.queryParam(entry.getKey(), entry.getValue());
    		}
    		//This line is causing memory leak. If we read response as a normal string it does not cause any memory leak. Only when it is deserialized to jaxb objects its causing memory leak.
    		xmlObject = (XMLObject[])webTarget1.request().accept(MediaType.APPLICATION_XML).get(XMLObject[].class);
    		System.out.println("XMLObject "+xmlObject);
    	}
		return String.valueOf(xmlObject.length);
    }
}

**Comment by shashank2337** [comment]
Hi @dmatej ,

One more thing i would like to update here is that we were getting below failure response in between during the load test.

HTTP Status 500 - Internal Server Error
type Exception report

messageInternal Server Error

descriptionThe server encountered an internal error that prevented it from fulfilling this request.

exception

jakarta.servlet.ServletException: jakarta.ws.rs.ProcessingException: java.net.SocketException: Unexpected end of file from server
root cause

jakarta.ws.rs.ProcessingException: java.net.SocketException: Unexpected end of file from server
root cause

java.net.SocketException: Unexpected end of file from server
note The full stack traces of the exception and its root causes are available in the Eclipse GlassFish 7.0.11 logs.

Eclipse GlassFish 7.0.11



Regards,
Shashank

**Comment by avpinchuk** [comment]
@shashank2337, can you build glassfish-hk2 and GlassFish from sources?

**Comment by shashank2337** [comment]
Hi @avpinchuk ,

Could you please share the glassfish and glassfish-hk2.
Could you please let us know the versions in which these fixes would be released.

Best Regards,
Shashank

**Comment by avpinchuk** [comment]
Master branches of GlassFish and HK2.

```
git clone https://github.com/eclipse-ee4j/glassfish-hk2
mvn clean install -DskipTests

git clone https://github.com/eclipse-ee4j/glassfish
mvn clean install -Pstaging,fastest -T4C -Dhk2.version=3.0.6-SNAPSHOT
```

**Comment by ramakrishna90** [comment]
@avpinchuk , thanks for the prompt action and doing the fix. 👍

**Comment by avpinchuk** [comment]
@ramakrishna90, my pleasure. Is your problem solved?

**Comment by shashank2337** [comment]
Hi @avpinchuk , @ramakrishna90 ,

I have tested new glassfish build. The issue is fixed now. Thank You very much for fixing the issue. 

Thanks,
Shashank

**Comment by dmatej** [comment]
That is great, then we should release the HK2 soon!

**Comment by arjantijms** [comment]
@dmatej @avpinchuk I'll stage 3.0.6 and will try to also merge into the 4.0 branch of hk2.

**Comment by avpinchuk** [comment]
Completed in #24766
