### ISSUE TITLE
WebConfiguration.BooleanWebContextInitParameter.EnableAgressiveSessionDirtying is not used anymore

### ISSUE THREAD

**Issue by BalusC** [eclipse-ee4j/glassfish#24681]
As per https://github.com/eclipse-ee4j/mojarra/issues/5331 the `WebConfiguration.BooleanWebContextInitParameter.EnableAgressiveSessionDirtying` turns out to not be used anymore since about halfway Mojarra 2.3. It's under the covers basically replaced by `WebConfiguration.BooleanWebContextInitParameter.EnableDistributable` which also automatically considers `web.xml` distributable when not set. Hence the `EnableAgressiveSessionDirtying` was removed in Mojarra 4.0.5.

However when running Mojarra 4.0.5 TCK against GlassFish 7.0.10 it fails with a `NoSuchFieldError` on `EnableAgressiveSessionDirtying`. It turns out that it's being referenced in https://github.com/eclipse-ee4j/glassfish/blob/114342a066ac56d25ece76abbbf9715a166813b4/appserver/web/jsf-connector/src/main/java/org/glassfish/faces/integration/GlassFishInjectionProvider.java#L394

It shall need to be replaced by `EnableDistributable`.

**Comment by BalusC** [comment]
Supposedly already fixed by @arjantijms.

**Comment by arjantijms** [comment]
Indeed already fixed by https://github.com/eclipse-ee4j/glassfish/pull/24682
