### ISSUE TITLE
java.util.ServiceConfigurationError: jakarta.servlet.ServletContainerInitializer: Provider org.omnifaces.jwt.servlet.RolesDeclarationInitializer not found

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/glassfish#24716]
## Environment Details
* GlassFish Version (and build number): 8.0.0-M1
* JDK version: 21
* OS: Windows 10 Pro 64bit
* Database:

In the server.log there is an exception like this.

```bash
  Could not call next! The initializer could not be created. Skipped ...
java.util.ServiceConfigurationError: jakarta.servlet.ServletContainerInitializer: Provider org.omnifaces.jwt.servlet.RolesDeclarationInitializer not found
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nex


``` 

Check the complete server.log file.

[server.log](https://github.com/eclipse-ee4j/glassfish/files/13768499/server.log)

**Comment by arjantijms** [comment]
Thanks, it's a known issue though. JWT / MP has not yet been updated / patched for EE 11.

It was undoable to get everything 100% for a milestone.

**Comment by arjantijms** [comment]
Fixed by https://github.com/eclipse-ee4j/glassfish/pull/24719
