### ISSUE TITLE
Jakarta Faces version is inconsistent in Jakarta EE pages

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/glassfish#24717]
In the Jakarta Faces development page, the next version is 5.0,https://jakarta.ee/specifications/faces/5.0/

But in the Jakarta EE 11 plan page, Jakarta Faces is 4.1 https://jakartaee.github.io/platform/jakartaee11/JakartaEE11ReleasePlan

In the Glassfish 8.0.0-M1, it includes Mojarra 4.1.0-M1, and there is a deprecation message for my example project like this. `The configuration 'jakarta.faces.PARTIAL_STATE_SAVING' is deprecated as of Faces 4.1 and should not longer be used.]]` where uses Faces 4.1.

**Comment by arjantijms** [comment]
> 'jakarta.faces.PARTIAL_STATE_SAVING' is deprecated as of Faces 4.1

This message is correct. PARTIAL_STATE_SAVING is deprecated, because it will be the only state saving method after 4.1.

**Comment by arjantijms** [comment]
> In the Jakarta Faces development page, the next version is 5.0,https://jakarta.ee/specifications/faces/5.0/

Thanks for the reminder. Should be fixed by this PR: https://github.com/jakartaee/specifications/pull/690

**Comment by arjantijms** [comment]
Next version is now https://jakarta.ee/specifications/faces/4.1/
