### ISSUE TITLE
Faces 5.0 schema version is not updated to 5.0

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/glassfish#24715]
## Environment Details
* GlassFish Version (and build number): 8.0.0-M1
* JDK version: 21
* OS: Windows 10 pro 64 bit
* Database:

----------

## Problem Description
According to the changelog, 8.0.0-M1 should includes the effort of Faces 5.0, but when I tried to update the `version` to `5.0` in the *faces-config.xml* and got the following exception. 

```bash
nable to parse document 'file:/D:/hantsylabs/jakartaee11-sandbox/faces/target/glassfish7x-home/cargo-domain/applications/faces-examples/WEB-INF/faces-config.xml': Unknown Schema version: 5.0. Please see server.log for more details.
```

**Comment by arjantijms** [comment]
8.0.0-M1 includes Faces 4.1.0-M1, see https://github.com/eclipse-ee4j/glassfish/releases

We decided to go for a 4.1.0 version number instead of a 5.0.0 for Faces.Next.
