### ISSUE TITLE
Rest Desearialization Issue

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/glassfish#24718]
## Environment Details
* GlassFish Version (and build number): 8.0.0-M1
* JDK version: 21
* OS: Windows 10 Pro 64bit
* Database:

----------

Run the simple REST greeting example on Glassfish 8.0.0-M1, and get an error like this. Obviously, it does not use JSONB to deserailize the entity and skip my JSONB config at all in the example project.

The example project: https://github.com/hantsy/jakartaee11-sandbox/tree/master/rest

```bash 
Java 8 date/time type `java.time.LocalDateTime` not supported by default: 
add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to 
enable handling (through reference chain: com.example.GreetingRecord["sentAt"])
```

On Glassfish v7, it picks up the JSONB config, and desearilize the Java 8 DateTime as expected.

**Comment by arjantijms** [comment]
Thanks for the report.

I quickly tried to run the example, but did not get to see the error you mentioned. Where did you see it?

I cloned your sandbox project, cd'ed into the rest folder and executed:

```
mvn clean install -Parq-glassfish-managed 
```

The result is:

```
INFO: Get greeting response status: 404
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 7.900 s <<< FAILURE! -- in com.example.it.GreetingResourceTest
[ERROR] com.example.it.GreetingResourceTest.testGetPerson -- Time elapsed: 0.075 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <200> but was: <404>
	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:531)
	at com.example.it.GreetingResourceTest.testGetPerson(GreetingResourceTest.java:102)
```

That said, Jersey consists out of dozens upon dozens of individual jar files, and they all need to be patched. Might well be that whatever jar responsible in Jersey for handling the type of JSON used here hasn't been patched. A better solution would probably be to build a milestone version of Jersey that has Jakarta Common Annotations 3 as a dependency.

See https://github.com/eclipse-ee4j/jersey/issues/5492

**Comment by hantsy** [comment]
1. Run the example `mvn clean package cargo:run -Pglassfish`.
2. Access `GreetingResource` endpoint, `curl http://localhost:<port>/rest-examples/api/greeting/JakartaEE`

Check the port from the log, I used a `offset` for the port number assignment. https://github.com/hantsy/jakartaee11-sandbox/blob/master/rest/pom.xml#L123

**Comment by arjantijms** [comment]
Ah, I see, the test is wrong, and a name is required.

Updating GF 8 with a quick rebuild of Jersey (only dependencies updated) results in:

```
curl http://localhost:8080/rest-examples/api/greeting/JakartaEE
{
    "name": "JakartaEE",
    "sent_at": "2024-01-07T20:43:07.635157"
}%                                  
```

**Comment by arjantijms** [comment]
fixed by: https://github.com/eclipse-ee4j/glassfish/pull/24732
