### ISSUE TITLE
Remove jersey-media-moxy.jar from glassfish.

### ISSUE THREAD

**Issue by jansupol** [eclipse-ee4j/glassfish#24749]
Since Moxy has been removed from Glassfish, the Jersey-Moxy integration module should not be there either as it potentially causes classloading (OSGi) issues.

Applies to GF 7.

**Comment by arjantijms** [comment]
Thanks for creating this issue, I'll take a look at it!

**Comment by jansupol** [comment]
GF 8.0.0-M3 still has it
