### ISSUE TITLE
WebSocket initializer should run before the Faces one.

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/glassfish#24756]
Due to a complex interaction between WebSocket and Faces, we need to make sure the WebSocket initializer runs before the Faces one.

The "problem" is that this is almost always the case by chance (the list of initializers is unordered), but ever so now and often the Faces one is executed first. If then both WebSocket and Faces have endpoints to process, some get overwritten. Faces is aware that WebSocket exists, but WebSocket is not aware the other way around and will bounty remove what Faces did.

When that happens endpoints fail to connect, and the "fix" is to simply restart GlassFish or redeploy the app (sometimes a couple of times, until by chance the order is right again).

This should be fixed in a more robust way.

**Comment by szarza** [comment]
Perhaps this issue is related to #24712?
