### ISSUE TITLE
doc: broken link to hello.war

### ISSUE THREAD

**Issue by libnoon** [eclipse-ee4j/glassfish#24801]
## Environment Details
Glassfish master branch as of 2024-02-10

## Problem Description
In the documentation:
https://glassfish.org/docs/latest/quick-start-guide.html#to-obtain-the-sample-application
the link to hello.war results in a file not found error.

## Steps to reproduce
$ curl -vw\\n https://github.com/eclipse-ee4j/glassfishdownloads/quickstart/hello.war
[...]
* Connected to github.com (140.82.121.3) port 443
[...]
> GET /eclipse-ee4j/glassfishdownloads/quickstart/hello.war HTTP/2
[...]
< HTTP/2 404 
[...]
Not Found

## Impact of Issue
The tutorial cannot be performed.

**Comment by libnoon** [comment]
To be fixed by #24802

**Comment by OndroMih** [comment]
The original file is still here: https://javaee.github.io/glassfish/downloads/quickstart/hello.war
It's very simple, just 2 simple JSP pages and one GIF with Duke. It should easy to create a similar app. 

Here's what I suggest:

1. Create a hello WAR maven project in https://github.com/eclipse-ee4j/glassfish/blob/master/docs directory and add it to the maven build (as module of the parent project)
2. Add the hello.war to the glassfish.org page, e.g. to glassfish.org/downloads - in the https://github.com/eclipse-ee4j/glassfish/blob/master/docs/publish/pom.xml, the web site build needs to pull the hello.war maven dependency and place it in `${site.output.dir}/downloads/quickstart`
3. Fix the link in the Quick Start guide to point to https://glassfish.org/downloads/quickstart/hello.war
