### ISSUE TITLE
Release and integrate next minor version of HK2

### ISSUE THREAD

**Issue by avpinchuk** [eclipse-ee4j/glassfish#24832]
I have noticed that we forgot to integrate fixes from glassfish-hk2.

Since the last release a several concurrency issues have been fixed.

**Comment by dmatej** [comment]
Do you agree to merge the reentrant lock branch too? I planned to test it with current GlassFish master by the end of the week. But maybe I could do that now too.
https://github.com/eclipse-ee4j/glassfish-hk2/pull/979

**Comment by avpinchuk** [comment]
Of course! 

This is just a reminder so don't lose sight of it.

**Comment by arjantijms** [comment]
This was done in https://github.com/eclipse-ee4j/glassfish/pull/24834
