### ISSUE TITLE
Clean code: add checkstyle rule to prevent unused imports

### ISSUE THREAD

**Issue by escay** [eclipse-ee4j/glassfish#24845]
Add the rule:
`<module name="UnusedImports" />`
to:

https://github.com/eclipse-ee4j/glassfish/blob/5829ac5e2aed76402d08dc51752223ccb72ff4ae/qa/src/main/resources/org/glassfish/qa/config/checkstyle/checkstyle.xml#L82C1-L85C42

and clean up relevant source files.

**Comment by dmatej** [comment]
Ah, I was looking forward for this, don't tell me you already started! If you did, I will wait :-)

**Comment by escay** [comment]
I already tried, but I made a mistake of not testing using the full build profile. Need to undo some test class changes. I suspect it is almost done.
