### ISSUE TITLE
GlassFish doesn't pass the Concurrency TCK since 7.0.10

### ISSUE THREAD

**Issue by dmatej** [eclipse-ee4j/glassfish#24840]
7.0.7 PASSED
7.0.8 PASSED
7.0.9 PASSED
7.0.10 FAILED 58 tests with HTTP 500 (but no stacktrace in server.log)
7.0.11 FAILED the same as 7.0.10
7.0.12 FAILED the same
7.0.13 FAILED the same
master FAILED (commit 0ed4ac58e006637e16277e00e2ece585e14f012f )

The failure was introduced between these commits:
ef006f741fd83a1ff4af5c749a3772aff5385f2e PASSED
4c52257e64c7ebc8a43111b3041d0cae8c5f09b4 FAILED
So it seems it was introduced in my #24225 

## Environment Details
* GlassFish Version 7.0.10+
* JDK version: Temurin 17.0.10
* OS: Kubuntu 22.04.4

----------

## Steps to reproduce
`mvn clean install -Ptck -pl :glassfish-external-tck-concurrency -Dglassfish.version=7.0.11`

## The Eclipse CI 
* https://ci.eclipse.org/jakartaee-tck/view/EFTL-Certification-Jobs-10/job/10/job/jakarta-concurrency-tck-glassfish/
* For some reason the Eclipse CI executes less tests (148) than the TCK integrated to GlassFish (196), and it still passes.

**Comment by arjantijms** [comment]
The one on the CI does pass

https://ci.eclipse.org/jakartaee-tck/view/EFTL-Certification-Jobs-10/job/jakarta-concurrency-tck-glassfish/

**Comment by dmatej** [comment]
> The one on the CI does pass
> 
> https://ci.eclipse.org/jakartaee-tck/view/EFTL-Certification-Jobs-10/job/jakarta-concurrency-tck-glassfish/

For some reason executed just 148 tests while our build runs 196.

**Comment by dmatej** [comment]
Fortunately it was caused just by test settings which had transitive dependency on slf4j - and slf4j was removed from gf in 7.0.10.
