### ISSUE TITLE
Glassfish 8.0.0-M* use Expressly 6.0.0-M1 not available in Maven Central

### ISSUE THREAD

**Issue by hboutemy** [eclipse-ee4j/glassfish#24867]
## Environment Details
* GlassFish Version (and build number): 8.0.0-M1 to M3

----------

## Problem Description
rebuilding releases (for Reproducible Builds), build fails with:
```
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: org.glassfish.expressly:expressly:jar:6.0.0-M1 was not found in https://repo.maven.apache.org/maven2 during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of central has elapsed or updates are forced
```
only version 5.0.0 is in Maven Central: https://repo.maven.apache.org/maven2/org/glassfish/expressly/expressly/

6.0.0-M1 has been tagged but not deployed to Maven Central: https://github.com/eclipse-ee4j/expressly/tags

notice that Expressly build looks reproducible, then rebuilding from the Git tag with the same JDK should give the same output jar

notice 2: building locally Expressly, I get the same issue with Exousia, then Epicryo: I stopped following the list of updated dependencies

## Steps to reproduce

https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/glassfish/main/README.md

using reproducible-central, `./rebuild.sh content/org/glassfish/main/glassfish-8.0.0-M1.buildspec` shows the issue

## Impact of Issue
cannot rebuild milestones of Glassfish 8

**Comment by arjantijms** [comment]
This was done a little intentionally, as especially the first two milestones were more like glorified snapshots.

The build should be reproducible by using the -Pstaging parameter, as the milestone components are all available in staging.

**Comment by hboutemy** [comment]
ok, I see: thanks for the `staging` profile, it works as expected
