### ISSUE TITLE
On Jersey 4.0.0 changes

### ISSUE THREAD

**Issue by jansupol** [eclipse-ee4j/glassfish#24874]
Jersey plans to publish 4.0.0-M1 in a couple of hours. 

Compatible with the previous API:
-------------------------------------

- Jersey 4.0.0-M1 is planned to support both Jakarta REST 4.0.0 and Jakarta REST 3.1.0 APIs to make easier integration with Glassfish.

However: 
----------

- Jersey comes with some internal changes that would affect GF, especially the Jersey-EJB module. With a planned transition of the injection framework from HK2 to CDI (which originally was a part of Jakarta REST 4.0, but the migration was postponed to EE 12 timeframe), Jersey won't be able to support the `AbstractBinder` with the CDI. For this, Jersey wants the customer to understand the `AbstractBinder` feature is bound to HK2, so `AbstractBinder` is no longer a part of the Jersey common module.  
- `AbstractBinder` is now in the jersey-hk2 module, in a `org.glassfish.jersey.inject.hk2` package.
- The `Bindings` class (used in the GF EJB module) is also moved to `org.glassfish.jersey.inject.hk2`. (There is also one in the `innate` package, please do not use that one, since it will be restricted from the module path in the future)
- `ClassBinding` and `InstanceBinding` are no longer available to the customers. The `Bindings` class works with a common super-class, the `Binding`.
- Optionally, the original HK2 `AbstractBinder` can be used, too.

**Comment by jansupol** [comment]
Jersey 4.0.0-M1 is in maven central.

**Comment by arjantijms** [comment]
Incorporated in GlassFish 8 M4 (now staged), thanks @jansupol !

**Comment by arjantijms** [comment]
I think we can close this, once again thanks @jansupol
