### ISSUE TITLE
The master release doesn't deploy the CycloneDX files

### ISSUE THREAD

**Issue by dmatej** [eclipse-ee4j/glassfish#25026]
See
* https://repo1.maven.org/maven2/org/glassfish/main/common/glassfish-api/8.0.0-M6/ - CycloneDX files are there
* https://repo1.maven.org/maven2/org/glassfish/main/common/glassfish-api/7.0.15/ - Here they don't

Note that in #24997 is another change that might be related in the future. Also I am not sure what are standard rules for this, we should read some docs about it.

**Comment by avpinchuk** [comment]
One difference between 7.x and 8.x:

7.x:
https://github.com/eclipse-ee4j/glassfish/blob/1d3efd38c4ba219fa445ed32025f4cdc5c17fc69/nucleus/parent/pom.xml#L27

8.x:
https://github.com/eclipse-ee4j/glassfish/blob/59fdd9b172310c2423be2126b4df030c1776dd71/nucleus/parent/pom.xml#L27

Therefore, the assembly of the GF8 gives us a lot of CycloneDX warnings.

**Comment by dmatej** [comment]
The fastest profile is used in the release process 
* Because of the parent from Eclipse (1.0.8 vs 1.0.9) it differs between master and 8.0. 
* The CycloneDX significantly slows down depeloper builds with fastest; developers usually don't care about CycloneDX.
* The target of fastest is to create all deployables asap, so here we have some controversy.

Also developers can have own profiles in settings.xml. Maybe there is a better place for the cyclone. Or we need another profile for the release process. However at some point it would be useful to have the OWASP check locally too, but that is different plugin.

Hmmm, they have different targets. Probably the CycloneDX could be executed really just for releases + explicitly.
* https://github.com/CycloneDX/cyclonedx-maven-plugin
* https://jeremylong.github.io/DependencyCheck/dependency-check-maven/index.html

**Comment by dmatej** [comment]
Yet one idea - we can also push the cyclonedx plugin execution to the deploy phase.

**Comment by pzygielo** [comment]
Maybe in release job, where `fastest` profile is activated, the `sbom` profile from parent could also be activated explicitly?
