### ISSUE TITLE
Support for Weld setting emptyBeansXmlModeAll in Glassfish 7

### ISSUE THREAD

**Issue by bvfalcon** [eclipse-ee4j/glassfish#25034]
# Impossible to set Weld configuration setting emptyBeansXmlModeAll

## Environment Details
* Eclipse GlassFish 7.0.15 (commit: 6f2f4c26b0f825d36b45ef39f6f83ac6b56d438c)
* JDK version: 17.0.10
* OS: Microsoft Windows 10

----------

## Problem Description
Glassfish 7 has Weld 5.1.2 as a CDI implementation. Weld has [a feature](https://docs.jboss.org/weld/reference/5.1.2.Final/en-US/html_single/#legacy-empty-beans-xml) which simplifies migration from CDI **3**.0 (Glassfish 6) to CDI **4**.0 (Glassfish 7). But this feature is inacceessible in Glassfish 7.

## Steps to reproduce
Project with [demonstartion](https://github.com/bvfalcon/glassfish-7-emptyBeansXmlModeAll-test) of problem

## Impact of Issue
Webapp project contains CDI-modules in separate jars (located in WEB-INF/lib). It is necessary to add `bean-discovery-mode="all"` into beans.xml for _each_ module. Modules are developed by different providers and in some cases changes cannot be done. This [Weld feature](https://docs.jboss.org/weld/reference/5.1.2.Final/en-US/html_single/#legacy-empty-beans-xml) gives a possibility to make changes only in one webapp, not in each module. Absence of support this Weld feature blocks a migration into Glassfish 7.

PS.
1) Weld has [three possibility](https://docs.jboss.org/weld/reference/5.1.2.Final/en-US/html_single/#weld_configuration) to set settings. Two of them are shown in demo project. Has Glassfish any integration setting to provide this feature for Weld? How Glassfish use Weld: as Weld SE, Weld Servlet or any other way?
2) Problem reproduces also for Wildfly 31. It is very possible, this is not a Glassfish-specific issue. [Issue for Weld](https://issues.redhat.com/browse/WELD-2792) project also created.

**Comment by arjantijms** [comment]
Good point, we should indeed do this. 

We mainly use the weld-osgi-bundle, and use Weld in deep integration mode, where large parts of the Weld code are replaced / augmented by GlassFish specific code. Most of that can be found here: https://github.com/eclipse-ee4j/glassfish/tree/master/appserver/web/weld-integration/src/main/java/org/glassfish/weld

**Comment by manovotn** [comment]
FTR, I added a comment to the [Weld issue](https://issues.redhat.com/browse/WELD-2792) - EE integrators fully control the bootstrap of Weld so they need to have their own config option for this. WFLY already supports it.

**Comment by bvfalcon** [comment]
With help of @manovotn we cleared situation. This is not a bug, but kind of disturbing twist in CDI development: in migration from cdi 3.0 to 4.0 backwards compatibility was lost (discussions [here](https://github.com/jakartaee/cdi/issues/500), [here](https://github.com/jakartaee/cdi/issues/659) and [here](https://www.eclipse.org/lists/cdi-dev/msg00693.html)).
For our aims we have found a solution, but it will be more civilized to have any setting/option, which give **backwards compatibility** to users who are really need it.

**Comment by manovotn** [comment]
To be exact, as I stated in the [Weld issue](https://issues.redhat.com/browse/WELD-2792?focusedId=25105821&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-25105821), the reproducer has technically invalid `beans.xml` as according to the XSD file, the `bean-discovery-mode` attribute is **required**.
Fixing that will also fix the deployment issues @bvfalcon is having.

That being said, GF is still required to provide a switch for legacy behavior of actually empty beans.xml file.

**Comment by arjantijms** [comment]
> That being said, GF is still required to provide a switch for legacy behavior of actually empty beans.xml file.

Yes, i remember we had this on the TODO somewhere back then, but it was missed.
