### ISSUE TITLE
Injecting ManagedExectuorService by custom Quarlifier does not work

### ISSUE THREAD

**Issue by hantsy** [eclipse-ee4j/glassfish#25048]
## Environment Details
* GlassFish Version (and build number):v8.0.0-M6
* JDK version: 21
* OS: Windows 10
* Database: built-in DB(not used in this example project)

----------

## Problem Description

Startup exceptions like this,

```bash 
CDI deployment failure:WELD-001408: Unsatisfied dependencies for type ManagedExecutorService with qualifiers @MyQualifier
  at injection point [BackedAnnotatedField] @Inject @MyQualifier private com.example.GreetingService.executor
  at com.example.GreetingService.executor(GreetingService.java:0)
. Please see server.log for more details.
```

## Steps to reproduce

Define a ExecutorService definition like this.

```java 
@ManagedExecutorDefinition(
        name = "java:comp/MyExecutor",
        maxAsync = 10,
        context = "java:comp/MyContextService",
        virtual = true,
        qualifiers = {MyQualifier.class}
)
....
@ApplicationScoped
class AsyncConfig{}
```

```java
@ApplicationScoped
public class GreetingService {
    private final static Logger LOGGER = Logger.getLogger(GreetingService.class.getName());

    @Inject
    @MyQualifier
    private ManagedExecutorService executor;

```

It seems the concurrency is stable, according to the documentation of Concurrency, it should work.

**Comment by arjantijms** [comment]
If I'm not mistaken, this only works in the later builds. Would be great if you you give the following a try:

 https://ci.eclipse.org/glassfish/job/glassfish_build-and-test-using-jenkinsfile/job/PR-25036/7/artifact/bundles/glassfish.zip

**Comment by OndroMih** [comment]
Hi @hantsy , can you check it this works in the latest build? So that we can close this issue if it does.

**Comment by hantsy** [comment]
Confirmed, it worked now.
