### ISSUE TITLE
java.lang.NoClassDefFoundError: org/glassfish/flashlight/provider/ProbeRegistry in a fresh 7.0.17 install

### ISSUE THREAD

**Issue by szarza** [eclipse-ee4j/glassfish#25126]
## Environment Details
* GlassFish Version (and build number): 7.0.17
* JDK version: 21 (java-21-openjdk-21.0.4.0.7-2.fc40.x86_6)
* OS: Fedora 40

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"
The next log fragment of server.log. is showed in a fresh new installation of 7.0.17 (this exception is thrown 65 times):

`
[2024-09-02T10:27:39.195028+02:00] [GF 7.0.17] [WARNING] [] [org.glassfish.grizzly.threadpool.AbstractThreadPool] [tid: _ThreadID=73 _ThreadName=http-listener-1(13)] [levelValue: 900] [[
  GRIZZLY0011: Uncaught exception on thread Thread[#73,http-listener-1(13),5,main]
java.lang.NoClassDefFoundError: org/glassfish/flashlight/provider/ProbeRegistry
	at com.sun.enterprise.v3.services.impl.monitor.probes.ThreadPoolProbeProvider.threadReleasedEvent(ThreadPoolProbeProvider.java)
	at com.sun.enterprise.v3.services.impl.monitor.ThreadPoolMonitor.onThreadReleaseEvent(ThreadPoolMonitor.java:73)
	at org.glassfish.grizzly.threadpool.ProbeNotifier.notifyThreadReleased(ProbeNotifier.java:82)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool.onWorkerExit(AbstractThreadPool.java:397)
	at org.glassfish.grizzly.threadpool.SyncThreadPool.onWorkerExit(SyncThreadPool.java:111)
	at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:517)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: org.glassfish.flashlight.provider.ProbeRegistry not found by org.glassfish.main.core.kernel [217]
	... 7 more
]]
`

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"
Install a new GF 7.0.17

## Impact of Issue
Unknown.

**Comment by pzygielo** [comment]
I cannot observe that on fresh 7.0.17 installation and starting `domain1`. Do you perform some other steps?

**Comment by szarza** [comment]
Please, find attached the configuration applied. 
May be the problem be due to Java 21, because with Java 17 the exception isn't thrown.

[calypso.config7.txt](https://github.com/user-attachments/files/16835428/calypso.config7.txt)

**Comment by pzygielo** [comment]
1. I used 21 on first try, and saw no grizzly warning in the log.
2. So it isn't just _new GF 7.0.17_
3. I applied attached config with following reported for some entries:
```
> set server-config.ejb-container.steady-pool-size=16
remote failure: No configuration found for server-config.ejb-container
...
> set server-config.ejb-container.max-pool-size=96
remote failure: No configuration found for server-config.ejb-container
...
> set resources.managed-scheduled-executor-service.concurrent/__defaultManagedScheduledExecutorService.core-pool-size=1
remote failure: Cannot change the element: HV000028: Unexpected exception during isValid call.
HV000028: Unexpected exception during isValid call.
...
set resources.managed-executor-service.concurrent/__defaultManagedExecutorService.core-pool-size=1
remote failure: Cannot change the element: HV000028: Unexpected exception during isValid call.
HV000028: Unexpected exception during isValid call.
```

The only grizzly logs I've got:
```
$ grep -i grizz glassfish/domains/domain1/logs/server.log 
  Grizzly Framework 4.0.2 started in: 33 ms - bound to [/0.0.0.0:8080]]]
  Grizzly Framework 4.0.2 started in: 2 ms - bound to [/0.0.0.0:8181]]]
  Grizzly Framework 4.0.2 started in: 2 ms - bound to [/0.0.0.0:4848]]]
  Grizzly Framework 4.0.2 started in: 1 ms - bound to [/0.0.0.0:3700]]]
  Grizzly Framework 4.0.2 started in: 1 ms - bound to [/0.0.0.0:7676]]]
  Grizzly Framework 4.0.2 started in: 1 ms - bound to [/0.0.0.0:8080]]]
  Grizzly Framework 4.0.2 started in: 1 ms - bound to [/0.0.0.0:8181]]]
  Grizzly Framework 4.0.2 started in: 1 ms - bound to [/0.0.0.0:8181]]]
  Grizzly Framework 4.0.2 started in: 3 ms - bound to [/0.0.0.0:8080]]]
  Grizzly Framework 4.0.2 started in: 3 ms - bound to [/0.0.0.0:8181]]]
  Grizzly Framework 4.0.2 started in: 5 ms - bound to [/0.0.0.0:8080]]]
  Grizzly Framework 4.0.2 started in: 3 ms - bound to [/0.0.0.0:8181]]]
  Grizzly Framework 4.0.2 started in: 2 ms - bound to [/0.0.0.0:8080]]]
  Grizzly Framework 4.0.2 started in: 3 ms - bound to [/0.0.0.0:8181]]]
```

**Comment by pzygielo** [comment]
- https://github.com/eclipse-ee4j/glassfish/issues/25129
