### ISSUE TITLE
Asadmin configuration commands errors after "./asadmin start-domain"

### ISSUE THREAD

**Issue by szarza** [eclipse-ee4j/glassfish#25129]
[//]: # "Please remove these comments"
[//]: # "Provide a general summary of the issue in the Title above"
[//]: # "If you are reporting a security issue or vulnerability, please contact the Eclipse Foundation Security Team instead of creating a GitHub issue."
[//]: # "  - Security policy: https://github.com/eclipse-ee4j/glassfish/security/policy"

## Environment Details
* GlassFish Version (and build number): 7.0.17
* JDK version: 17 and 21
* OS: RHEL 8

----------

## Problem Description
During startup, in a fresh installation without any application deployed the following commands show errors:

```
asadmin> set server-config.ejb-container.steady-pool-size=16
remote failure: No configuration found for server-config.ejb-container
Command set failed.
asadmin> set server-config.ejb-container.max-pool-size=96
remote failure: No configuration found for server-config.ejb-container
Command set failed.
asadmin> set resources.managed-scheduled-executor-service.concurrent/__defaultManagedScheduledExecutorService.core-pool-size=10
remote failure: Cannot change the element: HV000028: Unexpected exception during isValid call.
HV000028: Unexpected exception during isValid call.
Command set failed.
asadmin> set resources.managed-executor-service.concurrent/__defaultManagedExecutorService.core-pool-size=10
remote failure: Cannot change the element: HV000028: Unexpected exception during isValid call.
HV000028: Unexpected exception during isValid call.
Command set failed.
```

These commands are accepted without errors in Glassfish 6.2.5 and in Glassfish 7.0.17 **after** my .ear application is deployed

## Steps to reproduce
Unzip glassfish and reproduce commands

## Impact of Issue
My install/configuration script fail.

**Comment by pzygielo** [comment]
- https://github.com/eclipse-ee4j/glassfish/issues/25126

**Comment by OndroMih** [comment]
I was able to reproduce only during GlassFish startup. The behavior is the same as in GlassFish 7.0.16 and in 7.0.9, and probably also in older versions. Once GlassFish is fully started, the commands complete successfully.

If it's still an issue, please change the title and description of the issue to clarify that this happens only during GlassFish startup, or that it happens when the commands are executed right after asadmin start-domain, or something similar.
