### ISSUE TITLE
Force generating XJC code with specific language

### ISSUE THREAD

**Issue by Thihup** [eclipse-ee4j/glassfish#25184]
Currently, trying to build Glassfish can fail if other locale is used as the generated source of the XJC can be with an encoding that is not valid UTF-8.

There are two places were it would be required to change: `/nucleus/admin/server-mgmt/pom.xml` and `appserver/appclient/client/acc-config/pom.xml`

```diff
                               <xjc destdir="${dest}"
                                     schema="${project.basedir}/src/main/resources/xsd/schema/stringsubs.xsd"
-                                    package="com.sun.enterprise.admin.servermgmt.xml.stringsubs" />
+                                    package="com.sun.enterprise.admin.servermgmt.xml.stringsubs">
+                                    <jvmarg value="-Duser.language=en" />
+                                    <jvmarg value="-Duser.country=US" />
```

**Comment by pzygielo** [comment]
> can fail if other locale

Please suggest the settings - I'd like to observe the failure.

**Comment by Thihup** [comment]
My machine is running Windows 11 Home Single Language - Brazillian Portuguese. I'm not able to change it to English to allow me to build it without any changes to the source code. Probably with Linux it would be possible to replicate the failure by setting the `LC_ALL` environment variable to `pt_BR.UTF-8`.

**Comment by Thihup** [comment]
Without the fix

```
[ERROR] /C:/workspace/glassfish/nucleus/admin/server-mgmt/target/generated-sources/xjc/com/sun/enterprise/admin/servermgmt/xml/domaininfo/DomainInfo.java:[4,21] unmappable character (0xE7) for encoding UTF-8
[ERROR] /C:/workspace/glassfish/nucleus/admin/server-mgmt/target/generated-sources/xjc/com/sun/enterprise/admin/servermgmt/xml/domaininfo/DomainInfo.java:[4,22] unmappable character (0xF5) for encoding UTF-8
[ERROR] /C:/workspace/glassfish/nucleus/admin/server-mgmt/target/generated-sources/xjc/com/sun/enterprise/admin/servermgmt/xml/domaininfo/DomainInfo.java:[4,43] unmappable character (0xE3) for encoding UTF-8
[ERROR] /C:/workspace/glassfish/nucleus/admin/server-mgmt/target/generated-sources/xjc/com/sun/enterprise/admin/servermgmt/xml/domaininfo/DomainInfo.java:[4,57] unmappable character (0xF3) for encoding UTF-8
```

Generated source code:

```
//
// Este arquivo foi gerado pela Eclipse Implementation of JAXB, v4.0.5 
// Consulte https://eclipse-ee4j.github.io/jaxb-ri 
// Todas as modifica��es neste arquivo ser�o perdidas ap�s a recompila��o do esquema de origem. 
//
```

**Comment by pzygielo** [comment]
Not saying we can't do the change from the linked PR. Just adding for completeness.

From my run (Linux with `LC_ALL=pt_BR.UTF-8`), which is fine, for `head -5 nucleus/admin/server-mgmt/target/generated-sources/xjc/com/sun/enterprise/admin/servermgmt/xml/domaininfo/DomainInfo.java` I get:
```
//
// Este arquivo foi gerado pela Eclipse Implementation of JAXB, v4.0.5 
// Consulte https://eclipse-ee4j.github.io/jaxb-ri 
// Todas as modificações neste arquivo serão perdidas após a recompilação do esquema de origem. 
//
```

Not saying it's Windows. But it doesn't seem to be due to the specific language.

**Comment by Thihup** [comment]
Compiling with JDK 17 (which was my case) was using the Windows encoding by default (Windows-1252) and the result file contained invalid UTF-8 bytes. JDK 18+ fixes this issue (https://openjdk.org/jeps/400)

There are two ways to fix it in JDK 17:

- Changing the generated source code to be ASCII compatible (using the `user.language` and `user.country`)
- Changing the output of generated source code to be UTF-8 (using `file.encoding=UTF-8`)

The last one it is enough to fix the issue, but probably it would be better if the output was consistent across different environments, so setting the `user.language` could be an useful addition.

**Comment by pzygielo** [comment]
I think this should also be reported to [ee4j.jaxb-impl](https://projects.eclipse.org/projects/ee4j.jaxb-impl/)/[jaxb-ri](https://github.com/eclipse-ee4j/jaxb-ri), that the `xjc` generates such badly encoded files in non-UTF8 environment.

**Comment by Thihup** [comment]
Well, actually XJC is not generating wrong source code, it is generating correct source code with Windows-1252 encoding. When a program tries to read the Windows-1252 encoding as UTF-8, it does not recognizes a few caracters (like ç, ã, õ).
This is why the compiler was failing to compile, because the Glassfish project compiles the source code with UTF-8, and on Windows and JDK 17 it is generating an file with an incorrect encoding for the project to compile.

When using `user.language`, it forced the XJC to generate only English comments, and all English characters are valid UTF-8, so that's why it worked as my first suggested fix.

Using JDK 18+ or specifying the `file.encoding=UTF-8` should bulletproof against this type of error - as it will force the XJC to generate a source code with an encoding that Glassfish expects, or just wait to Glassfish to bump the requirement of the JDK to compile to be JDK 21.

**Comment by pzygielo** [comment]
>  specifying the `file.encoding=UTF-8`

Could the property
https://github.com/eclipse-ee4j/glassfish/blob/9ef2d2f9de50d62e96a190e292b438f34d59cecb/nucleus/parent/pom.xml#L161
propagate to XJC configuration (instead of country/language)?

**Comment by Thihup** [comment]
How about using this?

```xml
<jvmarg value="-Dfile.encoding=${project.build.sourceEncoding}" />
```

**Comment by pzygielo** [comment]
> How about using this?
> 
> ```
> <jvmarg value="-Dfile.encoding=${project.build.sourceEncoding}" />
> ```

If it works for you, this would be perfect.
