### ISSUE TITLE
Unsecure default of `maxSize` in admin gui app

### ISSUE THREAD

**Issue by pzygielo** [eclipse-ee4j/glassfish#25285]
https://github.com/eclipse-ee4j/glassfish/blob/069386406d4d63042dd913227eb2878c0cbe866d/appserver/admingui/war/src/main/webapp/WEB-INF/web.xml#L63-L70

https://github.com/eclipse-ee4j/glassfish/blob/8a02726675e9f2c3b7bd0eb13ab81b123f45f5a2/woodstock-webui-jsf/src/main/java/com/sun/webui/jsf/util/UploadFilter.java#L176-L178

Perhaps it could be modified here or comment in `UploadFilter` reevaluated.

**Comment by OndroMih** [comment]
Does it make sense to limit file upload if the feature is only accessible to admins? If we want to limit file uploads, I would at least make it configurable, with server restart.

**Comment by OndroMih** [comment]
There actually is already a limit on size of uploaded package files: https://github.com/eclipse-ee4j/glassfish/pull/25284. Is it important to limit it also in the web.xml descriptor?

**Comment by pzygielo** [comment]
> Does it make sense to limit file upload if the feature is only accessible to admins?

I don't know now.

> There actually is already a limit on size of uploaded package files: #25284.

The descriptor in domain1 from gf7-distribution zip holds the value of -1.
For #25284 it was set to 20. Do you think the limit of __20 bytes__ would be reasonable one?

> Is it important to limit it also in the web.xml descriptor?

Where else it is limited?

**Comment by dmatej** [comment]
> For #25284 it was set to 20. Do you think the limit of 20 bytes would be reasonable one?

It was just as an experiment to see the error message. There is no such change in diff, or did I miss something?

**Comment by dmatej** [comment]
About the necessity of the limit - does server process multipart HTTP request when user is not authenticated yet? If the user is forwarded to the login form without parsing whole request, I don't think we need to limit the file size.

**Comment by dmatej** [comment]
About the necessity of the limit - does server process multipart HTTP request when user is not authenticated yet? If the user is forwarded to the login form without parsing whole request, I don't think we need to limit the file size.

**Comment by pzygielo** [comment]
> > For #25284 it was set to 20. Do you think the limit of 20 bytes would be reasonable one?
> 
> It was just as an experiment to see the error message. There is no such change in diff, or did I miss something?

Indeed. In master - it is `-1` and was `-1` (== no limit), nothing changed there, but this was claimed:

> There actually is already a limit on size of uploaded package files: #25284. 

which I believe is not completely true. The limit is set to not limit the size of uploaded package.

> If the user is forwarded to the login form without parsing whole request, I don't think we need to limit the file size.

I such case, please close as not planned, and I'll be fine with that.

Thanks all for checking.

**Comment by OndroMih** [comment]
>> There actually is already a limit on size of uploaded package files: #25284. 

> which I believe is not completely true. The limit is set to not limit the size of uploaded package.

You might be right. I just assumed there's some other limit somewhere when I saw the screenshot. Now it seems that the author of the screenshot modified the web.xml to change the limit to from -1 to 20. Anyway, I think it's OK to leave it at -1 because only authenticated users can upload files, and some people have really big deployables.
